(function () {
  "use strict";

  const config = window.asciiUnicodeI18n;
  if (!config) return;

  const page = {
    zh: {
      topLabel: "顶部", topAriaLabel: "返回顶部", navHow: "转换方法", navCode: "代码", navBoundary: "ASCII 与 UTF-8", languageLabel: "选择语言", languageMenuLabel: "语言", breadcrumbLabel: "面包屑导航", breadcrumbHome: "ASCII to Unicode", breadcrumbCurrent: "Hex to ASCII 转换器",
      heroEyebrow: "免费的浏览器十六进制解码工具", heroTitle: "Hex to ASCII 转换器", heroLede: "将十六进制字节转换为可读文本。00 到 7F 的字节可用标准 ASCII；多语言文本、符号和 emoji 请选 UTF-8。", proofLabel: "转换器特点",
      toolTitle: "将十六进制字节解码为文本", formatLabel: "文本编码", formatUtf8: "UTF-8 文本", formatAscii: "标准 ASCII", formatHelp: "支持空格、换行、逗号、冒号、连字符、0x 前缀和 \\x 字节转义。每个字节必须有两位十六进制数字。",
      inputLabel: "Hex 输入", inputPlaceholder: "48 65 6C 6C 6F", inputHelp: "粘贴连续或带分隔符的十六进制字节。", outputLabel: "文本输出", outputPlaceholder: "Hello", examplesLabel: "尝试示例",
      warningInvalidHex: "只能使用十六进制数字。支持分隔符以及 0x 或 \\x 前缀。", warningOddHex: "一个字节需要两位十六进制数字，请补齐后重试。", warningInvalidUtf8: "这些字节不是完整有效的 UTF-8，替换字符标出了无效序列。", warningNonAsciiHex: "高于 7F 的字节不属于标准 ASCII，已显示为 ?。如果字节表示多语言文本，请选择 UTF-8。",
      howEyebrow: "转换指南", howTitle: "Hex to ASCII 转换原理", howP1: "十六进制用 <code>00</code> 到 <code>FF</code> 的两位数字表示一个字节。解码 ASCII 时，把每一对数字解析为字节，再将 <code>00</code> 到 <code>7F</code> 映射到对应字符。十六进制 <code>48</code> 是十进制 <code>72</code>，代表 <code>H</code>。", howP2: "因此 <code>48 65 6C 6C 6F</code> 会得到 <code>Hello</code>。分隔符只用于看清字节边界；连续输入 <code>48656C6C6F</code> 的结果相同。",
      thHex: "Hex 字节", thDecimal: "十进制", thCharacter: "ASCII 字符", spaceCharacter: "空格",
      codeTitle: "JavaScript 中的 Hex to ASCII", codeP1: "处理标准 ASCII 时，把十六进制拆成两位一组，用 <code>parseInt(pair, 16)</code> 解析，拒绝高于 <code>0x7F</code> 的值，再用 <code>String.fromCharCode</code> 得到字符。", pythonTitle: "Python 中的 Hex to ASCII", pythonP1: "Python 的 <code>bytes.fromhex</code> 支持空格分隔或连续的十六进制。严格标准 ASCII 使用 <code>\"ascii\"</code> 解码；字节流表示多语言 Unicode 文本时使用 <code>\"utf-8\"</code>。",
      boundaryTitle: "Hex 字节：标准 ASCII 与 UTF-8", boundaryP1: "标准 ASCII 只定义 <code>00</code> 到 <code>7F</code>。<code>80</code> 到 <code>FF</code> 的字节本身不是标准 ASCII，它可能属于 UTF-8、Latin-1、Windows-1252 或其他编码。", boundaryP2: "字节来自现代网页、JSON、API 或 UTF-8 文件时选择 <strong>UTF-8 文本</strong>。例如 <code>E4 BD A0 E5 A5 BD</code> 是 <code>你好</code> 的 UTF-8 字节。要求每个字节都在 <code>00-7F</code> 时选择 <strong>标准 ASCII</strong>。", boundaryNoteTitle: "Hex 描述字节值，不描述文本编码。", boundaryNoteText: "同一个高于 7F 的字节在不同编码中可能代表不同字符，请选择与数据来源一致的编码。",
      invalidTitle: "无效 Hex 与不完整字节", invalidP1: "每个字节必须恰好有两位十六进制数字。<code>486</code> 不完整，<code>0-9</code> 和 <code>A-F</code> 以外的字符无效。转换器会明确提示，而不会悄悄改变字节流。", invalidP2: "标准 ASCII 模式会把高于 <code>7F</code> 的字节显示为 <code>?</code> 并给出警告。UTF-8 模式会用替换字符 <code>�</code> 标出错误字节序列，提醒你核对原始编码。",
      relatedEyebrow: "相关转换器", relatedTitle: "继续转换 ASCII 和 Unicode", relatedText: "根据反向转换、二进制输出或 Unicode 转义处理的需求选择专用工具。", relatedHomeTitle: "ASCII to Unicode 转换器", relatedHomeText: "解码 ASCII-safe 转义和 Unicode 表示。", relatedBinaryTitle: "ASCII to Binary 转换器", relatedBinaryText: "将 ASCII 字符转换为固定 8 位二进制组。", relatedUnicodeTitle: "Unicode to ASCII 转换器", relatedUnicodeText: "转义、转写、替换或移除非 ASCII 字符。"
    },
    es: {
      topLabel: "ARRIBA", topAriaLabel: "Volver arriba", navHow: "Cómo funciona", navCode: "Código", navBoundary: "ASCII y UTF-8", languageLabel: "Elegir idioma", languageMenuLabel: "Idioma", breadcrumbLabel: "Ruta de navegación", breadcrumbHome: "ASCII to Unicode", breadcrumbCurrent: "Convertidor Hex to ASCII",
      heroEyebrow: "Decodificador hexadecimal gratuito en el navegador", heroTitle: "Convertidor Hex to ASCII", heroLede: "Convierte bytes hexadecimales en texto legible. Usa ASCII estándar para bytes de 00 a 7F o UTF-8 para texto multilingüe, símbolos y emoji.", proofLabel: "Ventajas del convertidor",
      toolTitle: "Decodificar bytes hexadecimales como texto", formatLabel: "Codificación de texto", formatUtf8: "Texto UTF-8", formatAscii: "ASCII estándar", formatHelp: "Acepta espacios, saltos de línea, comas, dos puntos, guiones y prefijos 0x o \\x. Cada byte necesita dos dígitos hexadecimales.",
      inputLabel: "Entrada Hex", inputPlaceholder: "48 65 6C 6C 6F", inputHelp: "Pega bytes hexadecimales compactos o separados.", outputLabel: "Salida de texto", outputPlaceholder: "Hello", examplesLabel: "Probar ejemplos",
      warningInvalidHex: "Usa solo dígitos hexadecimales. Se admiten separadores y prefijos 0x o \\x.", warningOddHex: "Un byte necesita dos dígitos hexadecimales. Añade el dígito que falta.", warningInvalidUtf8: "Los bytes no forman UTF-8 válido por completo. Los caracteres de sustitución marcan las secuencias inválidas.", warningNonAsciiHex: "Los bytes superiores a 7F no son ASCII estándar y aparecen como ?. Elige UTF-8 para texto multilingüe.",
      howEyebrow: "Guía de conversión", howTitle: "Cómo funciona la conversión Hex to ASCII", howP1: "El hexadecimal representa cada byte con dos dígitos de <code>00</code> a <code>FF</code>. Para decodificar ASCII, convierte cada par en un byte y asigna los valores <code>00</code> a <code>7F</code> al carácter correspondiente. <code>48</code> hexadecimal es <code>72</code> decimal y representa <code>H</code>.", howP2: "Por eso <code>48 65 6C 6C 6F</code> se convierte en <code>Hello</code>. Los separadores solo aclaran los límites; <code>48656C6C6F</code> produce el mismo resultado.",
      thHex: "Byte Hex", thDecimal: "Decimal", thCharacter: "Carácter ASCII", spaceCharacter: "Espacio",
      codeTitle: "Hex to ASCII en JavaScript", codeP1: "Para ASCII estándar, divide el hex en pares, usa <code>parseInt(pair, 16)</code>, rechaza valores superiores a <code>0x7F</code> y convierte el resto con <code>String.fromCharCode</code>.", pythonTitle: "Hex to ASCII en Python", pythonP1: "<code>bytes.fromhex</code> acepta hexadecimal compacto o separado. Decodifica con <code>\"ascii\"</code> para ASCII estricto o con <code>\"utf-8\"</code> para texto Unicode multilingüe.",
      boundaryTitle: "Bytes Hex: ASCII estándar y UTF-8", boundaryP1: "ASCII estándar define solo <code>00</code> a <code>7F</code>. Un byte entre <code>80</code> y <code>FF</code> puede pertenecer a UTF-8, Latin-1, Windows-1252 u otra codificación.", boundaryP2: "Elige <strong>Texto UTF-8</strong> para bytes de una web moderna, JSON, una API o un archivo UTF-8. <code>E4 BD A0 E5 A5 BD</code> representa <code>你好</code>. Elige <strong>ASCII estándar</strong> si todos los bytes deben estar entre <code>00-7F</code>.", boundaryNoteTitle: "Hex describe valores de bytes, no la codificación del texto.", boundaryNoteText: "Un mismo byte superior a 7F puede representar caracteres distintos. Usa la codificación de los datos de origen.",
      invalidTitle: "Hex inválido y bytes incompletos", invalidP1: "Cada byte necesita exactamente dos dígitos. <code>486</code> está incompleto y cualquier carácter fuera de <code>0-9</code> y <code>A-F</code> es inválido. La herramienta lo informa sin alterar los bytes.", invalidP2: "En ASCII estándar, los bytes sobre <code>7F</code> aparecen como <code>?</code>. En UTF-8, las secuencias mal formadas usan <code>�</code> y muestran un aviso.",
      relatedEyebrow: "Convertidores relacionados", relatedTitle: "Seguir convirtiendo ASCII y Unicode", relatedText: "Elige otra herramienta para la dirección inversa, salida binaria o escapes Unicode.", relatedHomeTitle: "Convertidor ASCII to Unicode", relatedHomeText: "Decodifica escapes seguros para ASCII y representaciones Unicode.", relatedBinaryTitle: "Convertidor ASCII to Binary", relatedBinaryText: "Convierte caracteres ASCII en grupos binarios de 8 bits.", relatedUnicodeTitle: "Convertidor Unicode to ASCII", relatedUnicodeText: "Escapa, translitera, sustituye o elimina caracteres no ASCII."
    },
    pt: {
      topLabel: "TOPO", topAriaLabel: "Voltar ao topo", navHow: "Como funciona", navCode: "Código", navBoundary: "ASCII e UTF-8", languageLabel: "Escolher idioma", languageMenuLabel: "Idioma", breadcrumbLabel: "Navegação estrutural", breadcrumbHome: "ASCII to Unicode", breadcrumbCurrent: "Conversor Hex to ASCII",
      heroEyebrow: "Decodificador hexadecimal gratuito no navegador", heroTitle: "Conversor Hex to ASCII", heroLede: "Converta bytes hexadecimais em texto legível. Use ASCII padrão para bytes de 00 a 7F ou UTF-8 para texto multilíngue, símbolos e emoji.", proofLabel: "Destaques do conversor",
      toolTitle: "Decodificar bytes hexadecimais em texto", formatLabel: "Codificação de texto", formatUtf8: "Texto UTF-8", formatAscii: "ASCII padrão", formatHelp: "Aceita espaços, quebras de linha, vírgulas, dois-pontos, hífens e prefixos 0x ou \\x. Cada byte precisa de dois dígitos hexadecimais.",
      inputLabel: "Entrada Hex", inputPlaceholder: "48 65 6C 6C 6F", inputHelp: "Cole bytes hexadecimais compactos ou separados.", outputLabel: "Saída de texto", outputPlaceholder: "Hello", examplesLabel: "Testar exemplos",
      warningInvalidHex: "Use apenas dígitos hexadecimais. Separadores e prefixos 0x ou \\x são aceitos.", warningOddHex: "Um byte precisa de dois dígitos hexadecimais. Adicione o dígito ausente.", warningInvalidUtf8: "Os bytes não formam UTF-8 totalmente válido. Caracteres de substituição marcam sequências inválidas.", warningNonAsciiHex: "Bytes acima de 7F não são ASCII padrão e aparecem como ?. Escolha UTF-8 para texto multilíngue.",
      howEyebrow: "Guia de conversão", howTitle: "Como funciona a conversão Hex to ASCII", howP1: "Hexadecimal representa cada byte com dois dígitos de <code>00</code> a <code>FF</code>. Para decodificar ASCII, converta cada par em byte e associe valores de <code>00</code> a <code>7F</code> ao caractere correspondente. Hex <code>48</code> é decimal <code>72</code> e representa <code>H</code>.", howP2: "Assim, <code>48 65 6C 6C 6F</code> vira <code>Hello</code>. Separadores apenas mostram os limites; <code>48656C6C6F</code> gera o mesmo resultado.",
      thHex: "Byte Hex", thDecimal: "Decimal", thCharacter: "Caractere ASCII", spaceCharacter: "Espaço",
      codeTitle: "Hex to ASCII em JavaScript", codeP1: "Para ASCII padrão, divida o hex em pares, use <code>parseInt(pair, 16)</code>, rejeite valores acima de <code>0x7F</code> e converta os demais com <code>String.fromCharCode</code>.", pythonTitle: "Hex to ASCII em Python", pythonP1: "<code>bytes.fromhex</code> aceita hexadecimal compacto ou separado. Decodifique com <code>\"ascii\"</code> para ASCII estrito ou <code>\"utf-8\"</code> para texto Unicode multilíngue.",
      boundaryTitle: "Bytes Hex: ASCII padrão e UTF-8", boundaryP1: "ASCII padrão define somente <code>00</code> a <code>7F</code>. Um byte de <code>80</code> a <code>FF</code> pode pertencer a UTF-8, Latin-1, Windows-1252 ou outra codificação.", boundaryP2: "Escolha <strong>Texto UTF-8</strong> para bytes de páginas modernas, JSON, APIs ou arquivos UTF-8. <code>E4 BD A0 E5 A5 BD</code> representa <code>你好</code>. Escolha <strong>ASCII padrão</strong> quando todos os bytes devem ficar em <code>00-7F</code>.", boundaryNoteTitle: "Hex descreve valores de bytes, não a codificação do texto.", boundaryNoteText: "O mesmo byte acima de 7F pode representar caracteres diferentes. Use a codificação da fonte.",
      invalidTitle: "Hex inválido e bytes incompletos", invalidP1: "Cada byte precisa de exatamente dois dígitos. <code>486</code> está incompleto e caracteres fora de <code>0-9</code> e <code>A-F</code> são inválidos. A ferramenta informa o problema sem alterar os bytes.", invalidP2: "Em ASCII padrão, bytes acima de <code>7F</code> aparecem como <code>?</code>. Em UTF-8, sequências malformadas usam <code>�</code> e exibem um aviso.",
      relatedEyebrow: "Conversores relacionados", relatedTitle: "Continuar convertendo ASCII e Unicode", relatedText: "Escolha outra ferramenta para a direção inversa, saída binária ou escapes Unicode.", relatedHomeTitle: "Conversor ASCII to Unicode", relatedHomeText: "Decodifique escapes seguros para ASCII e representações Unicode.", relatedBinaryTitle: "Conversor ASCII to Binary", relatedBinaryText: "Converta caracteres ASCII em grupos binários de 8 bits.", relatedUnicodeTitle: "Conversor Unicode to ASCII", relatedUnicodeText: "Escape, translitere, substitua ou remova caracteres não ASCII."
    },
    fr: {
      topLabel: "HAUT", topAriaLabel: "Retour en haut", navHow: "Fonctionnement", navCode: "Code", navBoundary: "ASCII et UTF-8", languageLabel: "Choisir la langue", languageMenuLabel: "Langue", breadcrumbLabel: "Fil d'Ariane", breadcrumbHome: "ASCII to Unicode", breadcrumbCurrent: "Convertisseur Hex to ASCII",
      heroEyebrow: "Décodeur hexadécimal gratuit dans le navigateur", heroTitle: "Convertisseur Hex to ASCII", heroLede: "Convertissez des octets hexadécimaux en texte lisible. Utilisez ASCII standard pour 00 à 7F ou UTF-8 pour le texte multilingue, les symboles et les emoji.", proofLabel: "Points forts du convertisseur",
      toolTitle: "Décoder des octets hexadécimaux en texte", formatLabel: "Encodage du texte", formatUtf8: "Texte UTF-8", formatAscii: "ASCII standard", formatHelp: "Les espaces, retours à la ligne, virgules, deux-points, tirets et préfixes 0x ou \\x sont acceptés. Chaque octet exige deux chiffres hexadécimaux.",
      inputLabel: "Entrée Hex", inputPlaceholder: "48 65 6C 6C 6F", inputHelp: "Collez des octets hexadécimaux compacts ou séparés.", outputLabel: "Sortie texte", outputPlaceholder: "Hello", examplesLabel: "Essayer des exemples",
      warningInvalidHex: "Utilisez uniquement des chiffres hexadécimaux. Les séparateurs et préfixes 0x ou \\x sont acceptés.", warningOddHex: "Un octet exige deux chiffres hexadécimaux. Ajoutez le chiffre manquant.", warningInvalidUtf8: "Les octets ne forment pas un UTF-8 entièrement valide. Les caractères de remplacement indiquent les séquences incorrectes.", warningNonAsciiHex: "Les octets supérieurs à 7F ne sont pas ASCII standard et sont affichés par ?. Choisissez UTF-8 pour le texte multilingue.",
      howEyebrow: "Guide de conversion", howTitle: "Fonctionnement de la conversion Hex to ASCII", howP1: "L'hexadécimal écrit chaque octet avec deux chiffres de <code>00</code> à <code>FF</code>. Pour décoder ASCII, analysez chaque paire et associez les valeurs <code>00</code> à <code>7F</code> au caractère correspondant. <code>48</code> en hexadécimal vaut <code>72</code> et représente <code>H</code>.", howP2: "<code>48 65 6C 6C 6F</code> devient donc <code>Hello</code>. Les séparateurs ne font qu'indiquer les limites ; <code>48656C6C6F</code> donne le même résultat.",
      thHex: "Octet Hex", thDecimal: "Décimal", thCharacter: "Caractère ASCII", spaceCharacter: "Espace",
      codeTitle: "Hex to ASCII en JavaScript", codeP1: "Pour ASCII standard, divisez l'hexadécimal en paires, utilisez <code>parseInt(pair, 16)</code>, refusez les valeurs supérieures à <code>0x7F</code> puis convertissez avec <code>String.fromCharCode</code>.", pythonTitle: "Hex to ASCII en Python", pythonP1: "<code>bytes.fromhex</code> accepte l'hexadécimal compact ou séparé. Décodez avec <code>\"ascii\"</code> pour ASCII strict ou <code>\"utf-8\"</code> pour le texte Unicode multilingue.",
      boundaryTitle: "Octets Hex : ASCII standard et UTF-8", boundaryP1: "ASCII standard ne définit que <code>00</code> à <code>7F</code>. Un octet entre <code>80</code> et <code>FF</code> peut appartenir à UTF-8, Latin-1, Windows-1252 ou un autre encodage.", boundaryP2: "Choisissez <strong>Texte UTF-8</strong> pour des octets provenant du Web moderne, de JSON, d'une API ou d'un fichier UTF-8. <code>E4 BD A0 E5 A5 BD</code> représente <code>你好</code>. Choisissez <strong>ASCII standard</strong> si tous les octets doivent rester dans <code>00-7F</code>.", boundaryNoteTitle: "Hex décrit les valeurs d'octets, pas l'encodage du texte.", boundaryNoteText: "Un même octet supérieur à 7F peut représenter des caractères différents. Utilisez l'encodage de la source.",
      invalidTitle: "Hex invalide et octets incomplets", invalidP1: "Chaque octet exige exactement deux chiffres. <code>486</code> est incomplet et tout caractère hors de <code>0-9</code> et <code>A-F</code> est invalide. L'outil le signale sans modifier les octets.", invalidP2: "En ASCII standard, les octets supérieurs à <code>7F</code> apparaissent comme <code>?</code>. En UTF-8, les séquences incorrectes utilisent <code>�</code> et affichent un avertissement.",
      relatedEyebrow: "Convertisseurs associés", relatedTitle: "Continuer à convertir ASCII et Unicode", relatedText: "Choisissez un autre outil pour le sens inverse, la sortie binaire ou les séquences Unicode.", relatedHomeTitle: "Convertisseur ASCII to Unicode", relatedHomeText: "Décodez les séquences sûres pour ASCII et les représentations Unicode.", relatedBinaryTitle: "Convertisseur ASCII to Binary", relatedBinaryText: "Convertissez les caractères ASCII en groupes binaires de 8 bits.", relatedUnicodeTitle: "Convertisseur Unicode to ASCII", relatedUnicodeText: "Échappez, translittérez, remplacez ou supprimez les caractères non ASCII."
    },
    de: {
      topLabel: "OBEN", topAriaLabel: "Nach oben", navHow: "Funktionsweise", navCode: "Code", navBoundary: "ASCII und UTF-8", languageLabel: "Sprache auswählen", languageMenuLabel: "Sprache", breadcrumbLabel: "Brotkrümelnavigation", breadcrumbHome: "ASCII to Unicode", breadcrumbCurrent: "Hex to ASCII Konverter",
      heroEyebrow: "Kostenloser Hexadezimal-Decoder im Browser", heroTitle: "Hex to ASCII Konverter", heroLede: "Hexadezimale Bytes in lesbaren Text umwandeln. Standard-ASCII gilt für 00 bis 7F; UTF-8 für mehrsprachigen Text, Symbole und Emoji.", proofLabel: "Vorteile des Konverters",
      toolTitle: "Hexadezimale Bytes als Text decodieren", formatLabel: "Textcodierung", formatUtf8: "UTF-8-Text", formatAscii: "Standard-ASCII", formatHelp: "Leerzeichen, Zeilenumbrüche, Kommas, Doppelpunkte, Bindestriche sowie 0x- und \\x-Präfixe werden akzeptiert. Jedes Byte benötigt zwei Hex-Ziffern.",
      inputLabel: "Hex-Eingabe", inputPlaceholder: "48 65 6C 6C 6F", inputHelp: "Kompakte oder getrennte Hex-Bytes einfügen.", outputLabel: "Textausgabe", outputPlaceholder: "Hello", examplesLabel: "Beispiele testen",
      warningInvalidHex: "Nur Hexadezimalziffern verwenden. Trennzeichen und 0x- oder \\x-Präfixe werden unterstützt.", warningOddHex: "Ein Byte benötigt zwei Hexadezimalziffern. Ergänzen Sie die fehlende Ziffer.", warningInvalidUtf8: "Die Bytes sind nicht vollständig gültiges UTF-8. Ersatzzeichen markieren ungültige Sequenzen.", warningNonAsciiHex: "Bytes über 7F sind kein Standard-ASCII und werden als ? angezeigt. Für mehrsprachigen Text UTF-8 wählen.",
      howEyebrow: "Konvertierungsleitfaden", howTitle: "So funktioniert die Hex to ASCII Umwandlung", howP1: "Hexadezimal schreibt jedes Byte mit zwei Ziffern von <code>00</code> bis <code>FF</code>. Für ASCII wird jedes Paar als Byte gelesen und ein Wert von <code>00</code> bis <code>7F</code> dem Zeichen zugeordnet. Hex <code>48</code> ist dezimal <code>72</code> und steht für <code>H</code>.", howP2: "Darum wird <code>48 65 6C 6C 6F</code> zu <code>Hello</code>. Trennzeichen zeigen nur Bytegrenzen; <code>48656C6C6F</code> liefert dasselbe Ergebnis.",
      thHex: "Hex-Byte", thDecimal: "Dezimal", thCharacter: "ASCII-Zeichen", spaceCharacter: "Leerzeichen",
      codeTitle: "Hex to ASCII in JavaScript", codeP1: "Für Standard-ASCII Hex in Zweierpaare teilen, mit <code>parseInt(pair, 16)</code> lesen, Werte über <code>0x7F</code> ablehnen und den Rest mit <code>String.fromCharCode</code> umwandeln.", pythonTitle: "Hex to ASCII in Python", pythonP1: "<code>bytes.fromhex</code> akzeptiert kompakte oder getrennte Hex-Werte. Mit <code>\"ascii\"</code> für striktes ASCII oder <code>\"utf-8\"</code> für mehrsprachigen Unicode-Text decodieren.",
      boundaryTitle: "Hex-Bytes: Standard-ASCII und UTF-8", boundaryP1: "Standard-ASCII definiert nur <code>00</code> bis <code>7F</code>. Ein Byte von <code>80</code> bis <code>FF</code> kann zu UTF-8, Latin-1, Windows-1252 oder einer anderen Codierung gehören.", boundaryP2: "<strong>UTF-8-Text</strong> für Bytes aus modernen Webseiten, JSON, APIs oder UTF-8-Dateien wählen. <code>E4 BD A0 E5 A5 BD</code> steht für <code>你好</code>. <strong>Standard-ASCII</strong> wählen, wenn alle Bytes in <code>00-7F</code> liegen müssen.", boundaryNoteTitle: "Hex beschreibt Bytewerte, nicht die Textcodierung.", boundaryNoteText: "Dasselbe Byte über 7F kann je nach Codierung verschiedene Zeichen bedeuten. Verwenden Sie die Codierung der Quelldaten.",
      invalidTitle: "Ungültiges Hex und unvollständige Bytes", invalidP1: "Jedes Byte benötigt genau zwei Ziffern. <code>486</code> ist unvollständig; Zeichen außerhalb von <code>0-9</code> und <code>A-F</code> sind ungültig. Das Tool meldet dies, ohne Bytes zu verändern.", invalidP2: "In Standard-ASCII erscheinen Bytes über <code>7F</code> als <code>?</code>. In UTF-8 verwenden fehlerhafte Sequenzen <code>�</code> und zeigen eine Warnung.",
      relatedEyebrow: "Verwandte Konverter", relatedTitle: "ASCII und Unicode weiter umwandeln", relatedText: "Wählen Sie ein anderes Tool für die Gegenrichtung, Binärausgabe oder Unicode-Escapes.", relatedHomeTitle: "ASCII to Unicode Konverter", relatedHomeText: "ASCII-sichere Escapes und Unicode-Darstellungen decodieren.", relatedBinaryTitle: "ASCII to Binary Konverter", relatedBinaryText: "ASCII-Zeichen in feste 8-Bit-Binärgruppen umwandeln.", relatedUnicodeTitle: "Unicode to ASCII Konverter", relatedUnicodeText: "Nicht-ASCII-Zeichen maskieren, transliterieren, ersetzen oder entfernen."
    },
    ja: {
      topLabel: "上へ", topAriaLabel: "ページ上部へ戻る", navHow: "変換方法", navCode: "コード", navBoundary: "ASCII と UTF-8", languageLabel: "言語を選択", languageMenuLabel: "言語", breadcrumbLabel: "パンくずリスト", breadcrumbHome: "ASCII to Unicode", breadcrumbCurrent: "Hex to ASCII コンバーター",
      heroEyebrow: "ブラウザで使える無料 Hex デコーダー", heroTitle: "Hex to ASCII コンバーター", heroLede: "16進バイトを読みやすいテキストに変換します。00 から 7F は標準 ASCII、多言語テキスト、記号、絵文字は UTF-8 を選びます。", proofLabel: "コンバーターの特徴",
      toolTitle: "16進バイトをテキストにデコード", formatLabel: "テキストエンコーディング", formatUtf8: "UTF-8 テキスト", formatAscii: "標準 ASCII", formatHelp: "空白、改行、カンマ、コロン、ハイフン、0x と \\x の接頭辞に対応します。各バイトには2桁の16進数が必要です。",
      inputLabel: "Hex 入力", inputPlaceholder: "48 65 6C 6C 6F", inputHelp: "連続または区切られた16進バイトを貼り付けます。", outputLabel: "テキスト出力", outputPlaceholder: "Hello", examplesLabel: "例を試す",
      warningInvalidHex: "16進数だけを使用してください。区切り文字と 0x / \\x 接頭辞に対応します。", warningOddHex: "1バイトには2桁の16進数が必要です。不足する桁を追加してください。", warningInvalidUtf8: "バイト列の一部が有効な UTF-8 ではありません。置換文字が無効な部分を示します。", warningNonAsciiHex: "7F を超えるバイトは標準 ASCII ではないため ? で表示します。多言語テキストには UTF-8 を選びます。",
      howEyebrow: "変換ガイド", howTitle: "Hex to ASCII 変換の仕組み", howP1: "16進数は1バイトを <code>00</code> から <code>FF</code> の2桁で表します。ASCII では各ペアをバイトとして読み、<code>00</code> から <code>7F</code> を対応する文字にします。16進 <code>48</code> は10進 <code>72</code> で <code>H</code> を表します。", howP2: "そのため <code>48 65 6C 6C 6F</code> は <code>Hello</code> になります。区切りは境界を読みやすくするだけで、<code>48656C6C6F</code> も同じ結果です。",
      thHex: "Hex バイト", thDecimal: "10進数", thCharacter: "ASCII 文字", spaceCharacter: "空白",
      codeTitle: "JavaScript で Hex to ASCII", codeP1: "標準 ASCII では Hex を2桁ずつ分け、<code>parseInt(pair, 16)</code> で読み、<code>0x7F</code> を超える値を拒否して <code>String.fromCharCode</code> で文字にします。", pythonTitle: "Python で Hex to ASCII", pythonP1: "<code>bytes.fromhex</code> は連続・空白区切りの16進数に対応します。厳密な ASCII は <code>\"ascii\"</code>、多言語 Unicode テキストは <code>\"utf-8\"</code> でデコードします。",
      boundaryTitle: "Hex バイト：標準 ASCII と UTF-8", boundaryP1: "標準 ASCII が定義するのは <code>00</code> から <code>7F</code> です。<code>80</code> から <code>FF</code> は UTF-8、Latin-1、Windows-1252 など別のエンコーディングの可能性があります。", boundaryP2: "現代の Web、JSON、API、UTF-8 ファイル由来なら <strong>UTF-8 テキスト</strong> を選びます。<code>E4 BD A0 E5 A5 BD</code> は <code>你好</code> です。全バイトを <code>00-7F</code> に限定する場合は <strong>標準 ASCII</strong> を選びます。", boundaryNoteTitle: "Hex はバイト値を示し、テキストエンコーディングは示しません。", boundaryNoteText: "7F を超える同じバイトでもエンコーディングによって文字が変わります。元データに合う設定を選びます。",
      invalidTitle: "無効な Hex と不完全なバイト", invalidP1: "各バイトには必ず2桁が必要です。<code>486</code> は不完全で、<code>0-9</code> と <code>A-F</code> 以外は無効です。ツールはバイト列を勝手に変えず問題を示します。", invalidP2: "標準 ASCII では <code>7F</code> を超えるバイトを <code>?</code> で表示します。UTF-8 では不正な列を <code>�</code> で示し警告します。",
      relatedEyebrow: "関連コンバーター", relatedTitle: "ASCII と Unicode の変換を続ける", relatedText: "逆方向、バイナリ出力、Unicode エスケープに合うツールを選びます。", relatedHomeTitle: "ASCII to Unicode コンバーター", relatedHomeText: "ASCII セーフなエスケープと Unicode 表現をデコードします。", relatedBinaryTitle: "ASCII to Binary コンバーター", relatedBinaryText: "ASCII 文字を固定 8 ビットのバイナリに変換します。", relatedUnicodeTitle: "Unicode to ASCII コンバーター", relatedUnicodeText: "非 ASCII 文字をエスケープ、音写、置換、削除します。"
    },
    ko: {
      topLabel: "위로", topAriaLabel: "맨 위로", navHow: "변환 방식", navCode: "코드", navBoundary: "ASCII와 UTF-8", languageLabel: "언어 선택", languageMenuLabel: "언어", breadcrumbLabel: "이동 경로", breadcrumbHome: "ASCII to Unicode", breadcrumbCurrent: "Hex to ASCII 변환기",
      heroEyebrow: "브라우저에서 실행되는 무료 Hex 디코더", heroTitle: "Hex to ASCII 변환기", heroLede: "16진수 바이트를 읽을 수 있는 텍스트로 변환합니다. 00~7F는 표준 ASCII, 다국어 텍스트와 기호, 이모지는 UTF-8을 사용하세요.", proofLabel: "변환기 특징",
      toolTitle: "16진수 바이트를 텍스트로 디코딩", formatLabel: "텍스트 인코딩", formatUtf8: "UTF-8 텍스트", formatAscii: "표준 ASCII", formatHelp: "공백, 줄바꿈, 쉼표, 콜론, 하이픈, 0x 및 \\x 접두사를 지원합니다. 각 바이트에는 16진수 두 자리가 필요합니다.",
      inputLabel: "Hex 입력", inputPlaceholder: "48 65 6C 6C 6F", inputHelp: "연속 또는 구분된 16진수 바이트를 붙여 넣으세요.", outputLabel: "텍스트 출력", outputPlaceholder: "Hello", examplesLabel: "예시 실행",
      warningInvalidHex: "16진수만 사용하세요. 구분자와 0x 또는 \\x 접두사를 지원합니다.", warningOddHex: "한 바이트에는 16진수 두 자리가 필요합니다. 빠진 자리를 추가하세요.", warningInvalidUtf8: "바이트 전체가 유효한 UTF-8이 아닙니다. 대체 문자가 잘못된 시퀀스를 표시합니다.", warningNonAsciiHex: "7F보다 큰 바이트는 표준 ASCII가 아니므로 ?로 표시합니다. 다국어 텍스트에는 UTF-8을 선택하세요.",
      howEyebrow: "변환 안내", howTitle: "Hex to ASCII 변환 방식", howP1: "16진수는 각 바이트를 <code>00</code>부터 <code>FF</code>까지 두 자리로 표시합니다. ASCII 변환은 각 쌍을 바이트로 읽고 <code>00</code>부터 <code>7F</code>까지 해당 문자에 연결합니다. Hex <code>48</code>은 10진수 <code>72</code>이며 <code>H</code>입니다.", howP2: "따라서 <code>48 65 6C 6C 6F</code>는 <code>Hello</code>가 됩니다. 구분자는 경계를 보여 줄 뿐이며 <code>48656C6C6F</code>도 결과가 같습니다.",
      thHex: "Hex 바이트", thDecimal: "10진수", thCharacter: "ASCII 문자", spaceCharacter: "공백",
      codeTitle: "JavaScript에서 Hex to ASCII", codeP1: "표준 ASCII에서는 Hex를 두 자리씩 나누고 <code>parseInt(pair, 16)</code>으로 읽은 뒤 <code>0x7F</code>보다 큰 값을 거부하고 <code>String.fromCharCode</code>로 변환합니다.", pythonTitle: "Python에서 Hex to ASCII", pythonP1: "<code>bytes.fromhex</code>는 연속 또는 공백 구분 16진수를 지원합니다. 엄격한 ASCII는 <code>\"ascii\"</code>, 다국어 Unicode 텍스트는 <code>\"utf-8\"</code>로 디코딩합니다.",
      boundaryTitle: "Hex 바이트: 표준 ASCII와 UTF-8", boundaryP1: "표준 ASCII는 <code>00</code>부터 <code>7F</code>까지만 정의합니다. <code>80</code>부터 <code>FF</code>는 UTF-8, Latin-1, Windows-1252 또는 다른 인코딩일 수 있습니다.", boundaryP2: "현대 웹, JSON, API, UTF-8 파일에서 온 바이트는 <strong>UTF-8 텍스트</strong>를 선택하세요. <code>E4 BD A0 E5 A5 BD</code>는 <code>你好</code>입니다. 모든 바이트가 <code>00-7F</code>여야 하면 <strong>표준 ASCII</strong>를 선택합니다.", boundaryNoteTitle: "Hex는 바이트 값을 나타내며 텍스트 인코딩을 나타내지 않습니다.", boundaryNoteText: "7F보다 큰 같은 바이트도 인코딩에 따라 다른 문자가 됩니다. 원본 데이터의 인코딩을 선택하세요.",
      invalidTitle: "잘못된 Hex와 불완전한 바이트", invalidP1: "각 바이트에는 정확히 두 자리가 필요합니다. <code>486</code>은 불완전하며 <code>0-9</code>와 <code>A-F</code> 이외 문자는 잘못되었습니다. 도구는 바이트를 바꾸지 않고 문제를 알려 줍니다.", invalidP2: "표준 ASCII에서는 <code>7F</code>보다 큰 바이트를 <code>?</code>로 표시합니다. UTF-8에서는 잘못된 시퀀스를 <code>�</code>로 표시하고 경고합니다.",
      relatedEyebrow: "관련 변환기", relatedTitle: "ASCII와 Unicode 변환 계속하기", relatedText: "역방향, 2진수 출력, Unicode 이스케이프에 맞는 도구를 선택하세요.", relatedHomeTitle: "ASCII to Unicode 변환기", relatedHomeText: "ASCII 안전 이스케이프와 Unicode 표현을 디코딩합니다.", relatedBinaryTitle: "ASCII to Binary 변환기", relatedBinaryText: "ASCII 문자를 고정 8비트 2진수로 변환합니다.", relatedUnicodeTitle: "Unicode to ASCII 변환기", relatedUnicodeText: "비 ASCII 문자를 이스케이프, 독음 변환, 교체 또는 제거합니다."
    }
  };

  config.pages.hexToAscii = page;

  config.meta.hexToAscii = {
    zh: { title: "Hex to ASCII 转换器 - 免费在线工具", description: "在线将十六进制字节转换为 ASCII 或 UTF-8 文本，支持连续 Hex、常用分隔符、0x 与 \\x 前缀和无效字节提示。" },
    es: { title: "Convertidor Hex to ASCII - Herramienta gratuita", description: "Convierte bytes hexadecimales a texto ASCII o UTF-8 con hex compacto, separadores, prefijos 0x y \\x y avisos de bytes inválidos." },
    pt: { title: "Conversor Hex to ASCII - Ferramenta gratuita", description: "Converta bytes hexadecimais em texto ASCII ou UTF-8 com hex compacto, separadores, prefixos 0x e \\x e avisos de bytes inválidos." },
    fr: { title: "Convertisseur Hex to ASCII - Outil gratuit", description: "Convertissez des octets hexadécimaux en texte ASCII ou UTF-8 avec saisie compacte, séparateurs, préfixes 0x et \\x et alertes." },
    de: { title: "Hex to ASCII Konverter - Kostenloses Tool", description: "Hexadezimale Bytes in ASCII- oder UTF-8-Text umwandeln, mit kompaktem Hex, Trennzeichen, 0x- und \\x-Präfixen und Warnungen." },
    ja: { title: "Hex to ASCII コンバーター - 無料ツール", description: "16進バイトを ASCII または UTF-8 テキストに変換。連続 Hex、区切り、0x・\\x 接頭辞、無効バイト警告に対応。" },
    ko: { title: "Hex to ASCII 변환기 - 무료 도구", description: "16진수 바이트를 ASCII 또는 UTF-8 텍스트로 변환하세요. 연속 Hex, 구분자, 0x 및 \\x 접두사와 오류 경고를 지원합니다." }
  };
})();
