(function () {
  "use strict";

  const languages = {
    en: { label: "English", htmlLang: "en" },
    zh: { label: "简体中文", htmlLang: "zh-CN" },
    es: { label: "Español", htmlLang: "es" },
    pt: { label: "Português", htmlLang: "pt-BR" },
    fr: { label: "Français", htmlLang: "fr" },
    de: { label: "Deutsch", htmlLang: "de" },
    ja: { label: "日本語", htmlLang: "ja" },
    ko: { label: "한국어", htmlLang: "ko" }
  };

  const homeKeys = [
    "skip", "navConverter", "navExamples", "navFormats", "navFaq", "navOpen", "eyebrow", "heroTitle", "heroLede", "proofNoSignup", "proofFree", "toolKicker", "toolTitle", "statusReady", "statusDone", "statusCopied", "statusCleared", "statusImported", "statusDownloaded", "modeDecode", "modeEncode", "modeEntities", "modeMojibake", "formatLabel", "autoConvert", "formatHelp", "inputLabel", "inputHelp", "outputLabel", "charsLabel", "btnConvert", "btnCopy", "btnClear", "btnSwap", "btnImport", "btnDownload", "warningMalformed", "warningNoChange", "warningEmpty", "previewEyebrow", "previewTitle", "previewText", "previewCaption", "landingEyebrow", "whatTitle", "whatP1", "whatP2", "howTitle", "howIntro", "step1Title", "step1Text", "step2Title", "step2Text", "step3Title", "step3Text", "examplesEyebrow", "examplesTitle", "examplesText", "tryExample", "exLogTitle", "exLogText", "exJsonTitle", "exJsonText", "exEntityTitle", "exEntityText", "exEmojiTitle", "exEmojiText", "exMojibakeTitle", "exMojibakeText", "exEncodeTitle", "exEncodeText", "formatsTitle", "formatsIntro", "formatUnicodeTitle", "formatHtmlTitle", "formatHexTitle", "formatBrokenTitle", "useTitle", "useIntro", "useLogsTitle", "useLogsText", "useApiTitle", "useApiText", "useHtmlTitle", "useHtmlText", "useTestsTitle", "useTestsText", "compareTitle", "compareIntro", "compareNote", "faqEyebrow", "faqTitle", "faq1Q", "faq1A", "faq2Q", "faq2A", "faq3Q", "faq3A", "faq4Q", "faq4A", "faq5Q", "faq5A", "faq6Q", "faq6A", "privacyTitle", "privacyText", "privacyText2", "privacyLink", "aboutTitle", "aboutText", "aboutText2", "termsTitle", "termsText", "termsText2", "termsLink", "contactTitle", "contactText", "contactText2", "contactLink", "footerPrivacy", "footerTerms", "footerContact"
  ];

  function zip(keys, values) {
    return keys.reduce((result, key, index) => {
      result[key] = values[index];
      return result;
    }, {});
  }

  const homeValues = {};

  homeValues.es = [
    "Ir al convertidor", "Convertidor", "Ejemplos", "Formatos", "Preguntas frecuentes", "Abrir convertidor",
    "Herramienta gratuita en el navegador para registros, código, JSON y texto dañado", "Convertidor ASCII to Unicode", "Decodifica escapes ASCII como \\u0048, entidades HTML, U+1F680, bytes hexadecimales y texto mojibake en Unicode legible. También codifica texto de nuevo en formatos Unicode sin salir de esta página.", "Sin registro", "Conversión gratuita en línea",
    "Herramienta interactiva", "Convierte texto ASCII seguro a Unicode en una sola página", "Listo", "Convertido", "Copiado", "Borrado", "Importado", "Descargado",
    "Decodificar a Unicode", "Codificar como escapes", "Entidades HTML", "Reparar mojibake", "Formato de salida", "Conversión automática", "El selector de formato se usa al codificar texto legible como escapes o entidades.",
    "Entrada ASCII", "Pega escapes, entidades, texto de bytes, cadenas JSON o mojibake.", "Salida Unicode", "caracteres", "Convertir", "Copiar", "Borrar", "Intercambiar", "Importar TXT", "Descargar salida",
    "Se detectó una secuencia de escape posiblemente incompleta. El texto original se conservó cuando fue necesario.", "No se detectó contenido convertible, por lo que se conserva el texto original.", "Introduce el texto que quieres convertir.",
    "Antes y después", "Unicode legible a partir de texto ASCII seguro", "Un buen convertidor debe mostrar el resultado al instante, mantener al usuario en la misma URL y ser útil antes de cualquier explicación extensa.", "La vista previa muestra cómo una entrada ASCII segura se convierte en una salida Unicode legible en la misma página.",
    "Contenido de la página renderizado directamente en HTML", "¿Qué es un convertidor ASCII to Unicode?", "Un convertidor ASCII to Unicode transforma representaciones de texto seguras para ASCII en los caracteres Unicode reales que las personas esperan leer. Estas formas escapadas aparecen a menudo en JSON, registros, archivos de configuración, bases de datos, navegadores y respuestas de API.", "Esta página reúne el convertidor, la explicación, los ejemplos, los formatos compatibles y las preguntas frecuentes en la misma URL canónica para resolver el problema sin saltar entre páginas.",
    "Cómo convertir ASCII a Unicode", "Pega el texto, elige el modo que corresponda al problema y conviértelo aquí mismo. El resultado aparece sin abrir una página separada.", "Pega texto escapado o dañado", "Usa escapes Unicode, entidades HTML, notación U+, bytes hexadecimales o mojibake copiado de un registro, API, archivo JSON o exportación antigua de base de datos.", "Elige el modo de conversión correcto", "Decodifica a Unicode legible, codifica texto como escapes, convierte entidades HTML o repara mojibake común.", "Copia o descarga el resultado", "Mantén el resultado en la página, cópialo al portapapeles o descarga un archivo de texto para usarlo después.",
    "Muestra de resultados seleccionados", "Ejemplos del convertidor ASCII to Unicode", "Estos ejemplos seleccionados funcionan como una zona de resultados. Muestran lo que produce la herramienta sin crear páginas de usuario de baja calidad para indexar.", "Probar este ejemplo", "Decodificar un escape de registro", "Lee texto escapado de registros del servidor o salidas de diagnóstico.", "Decodificar escapes Unicode de JSON", "Convierte cadenas seguras para JSON en texto multilingüe legible.", "Decodificar una entidad HTML", "Convierte texto de entidad copiado de HTML en el símbolo visible.", "Decodificar un punto de código de emoji", "Usa la notación U+ para emoji y símbolos fuera del ASCII básico.", "Reparar mojibake", "Corrige texto UTF-8 que se interpretó por error como Latin-1.", "Codificar texto legible", "Crea formatos de escape Unicode para código, documentación o pruebas.",
    "Formatos ASCII y Unicode compatibles", "El convertidor se centra en los formatos que realmente aparecen al depurar, analizar y mover texto entre sistemas.", "Escapes Unicode", "Entidades HTML", "Escapes de bytes hexadecimales", "Texto mojibake",
    "Casos de uso habituales", "Una sola página debe satisfacer tanto una conversión rápida como una búsqueda más profunda. Estas son las situaciones principales para las que se creó.", "Registros y diagnósticos", "Decodifica cargas escapadas para que errores, nombres, emoji y símbolos sean legibles durante la depuración.", "API y JSON", "Comprende texto que los servicios escapan para transportarlo o mantener la compatibilidad.", "Limpieza de HTML", "Convierte entidades numéricas en caracteres reales antes de editar o publicar contenido.", "Datos de prueba y código", "Genera cadenas de escape estables para fixtures, instantáneas, documentación y ejemplos entre lenguajes.",
    "ASCII frente a Unicode frente a UTF-8", "ASCII es un conjunto pequeño para letras inglesas básicas, dígitos y caracteres de control. Unicode es el estándar que cubre sistemas de escritura modernos, emoji y símbolos. UTF-8 es una forma común de almacenar Unicode como bytes.", "Muchas cadenas confusas aparecen al mezclar bytes, caracteres y formatos de escape. Esta herramienta ayuda a inspeccionar la representación y recuperar el texto que querías leer.",
    "Preguntas habituales", "Preguntas frecuentes sobre ASCII to Unicode", "¿Qué es un convertidor ASCII to Unicode?", "Decodifica representaciones ASCII seguras como escapes Unicode, entidades HTML y códigos U+ en Unicode legible. También puede codificar texto legible en esos formatos.", "¿Admite \\uXXXX y emoji?", "Sí. Admite \\uXXXX, \\u{1F600}, pares sustitutos como \\uD83D\\uDE00 y notación U+ para emoji y símbolos.", "¿Puedo decodificar entidades HTML?", "Sí. Las entidades numéricas decimales y hexadecimales, como &#9731; y &#x2603;, pueden convertirse en caracteres Unicode visibles.", "¿Por qué ocurre el mojibake?", "Suele aparecer cuando los bytes UTF-8 se interpretan con otra codificación. El modo de reparación intenta reconstruir el texto UTF-8 original cuando reconoce ese patrón.", "¿La conversión es privada?", "Sí. El convertidor funciona localmente en tu navegador. La página permite registrar acciones sin guardar el texto que pegas.", "¿Se añadirán más convertidores relacionados?", "Solo se añadirán cuando resuelvan un problema específico de conversión de texto. Esta primera versión se centra en ASCII to Unicode.",
    "Nota de privacidad", "El texto que pegas permanece en tu navegador. El convertidor no requiere una cuenta, no sube archivos TXT ni guarda el historial de conversiones en nuestro servidor.", "La preferencia de idioma se guarda localmente. Si se añade analítica, registrará acciones como convertir, copiar y descargar sin enviar el texto de entrada o salida.", "Leer la Política de privacidad", "Acerca de", "ASCII to Unicode es una página de conversión enfocada en desarrolladores, redactores, editores de localización, probadores de QA y operadores que necesitan Unicode legible a partir de texto escapado o dañado.", "La página se mantiene deliberadamente enfocada: un convertidor, ejemplos seleccionados, formatos compatibles y explicaciones prácticas de problemas comunes de codificación.", "Términos", "Usa esta herramienta para inspección de texto, depuración, limpieza de contenido y preparación de datos de prueba. Verifica resultados importantes antes de usarlos en contextos de producción, legales, médicos o financieros.", "Eres responsable del texto que procesas y de cumplir las reglas de cualquier sistema donde uses el resultado convertido.", "Leer los Términos de uso", "Contacto", "Para correcciones, solicitudes de funciones, problemas de accesibilidad o preguntas de privacidad, escribe a:", "Al informar de un problema, incluye el modo de conversión y el resultado esperado. No incluyas secretos ni texto privado.", "Abrir la página de contacto", "Privacidad", "Términos", "Contacto"
  ];

  homeValues.pt = [
    "Ir para o conversor", "Conversor", "Exemplos", "Formatos", "Perguntas frequentes", "Abrir conversor",
    "Ferramenta gratuita no navegador para logs, código, JSON e texto corrompido", "Conversor ASCII to Unicode", "Decodifique escapes seguros para ASCII, como \\u0048, entidades HTML, U+1F680, bytes hexadecimais e mojibake em Unicode legível. Codifique o texto novamente em formatos Unicode sem sair desta página.", "Sem cadastro", "Conversão online gratuita",
    "Ferramenta interativa", "Converta texto seguro para ASCII em Unicode em uma única página", "Pronto", "Convertido", "Copiado", "Limpo", "Importado", "Baixado",
    "Decodificar para Unicode", "Codificar como escapes", "Entidades HTML", "Corrigir mojibake", "Formato de saída", "Conversão automática", "O seletor de formato é usado ao codificar texto legível como escapes ou entidades.",
    "Entrada ASCII", "Cole escapes, entidades, texto em bytes, strings JSON ou mojibake.", "Saída Unicode", "caracteres", "Converter", "Copiar", "Limpar", "Trocar", "Importar TXT", "Baixar saída",
    "Foi detectada uma sequência de escape possivelmente incompleta. O texto original foi preservado quando necessário.", "Nenhum conteúdo conversível foi detectado, então o texto original foi preservado.", "Digite o texto que deseja converter.",
    "Antes e depois", "Unicode legível a partir de texto seguro para ASCII", "Um bom conversor deve mostrar o resultado imediatamente, manter o usuário na mesma URL e ser útil antes de qualquer explicação longa.", "A prévia mostra a entrada segura para ASCII se tornando uma saída Unicode legível na mesma página.",
    "Conteúdo da página renderizado diretamente em HTML", "O que é um conversor ASCII to Unicode?", "Um conversor ASCII to Unicode transforma representações de texto seguras para ASCII nos caracteres Unicode reais que as pessoas esperam ler. Desenvolvedores encontram essas formas com frequência em JSON, logs, arquivos de configuração, bancos de dados, saídas do navegador e respostas de API.", "Esta página mantém o conversor, a explicação, os exemplos, os formatos compatíveis e as perguntas frequentes na mesma URL canônica, para resolver o problema sem trocar de página.",
    "Como converter ASCII em Unicode", "Cole o texto, escolha o modo adequado ao problema e converta no mesmo lugar. O resultado aparece sem abrir uma página separada.", "Cole texto escapado ou corrompido", "Use escapes Unicode, entidades HTML, notação U+, bytes hexadecimais ou mojibake copiado de um log, API, arquivo JSON ou exportação antiga de banco de dados.", "Escolha o modo de conversão correto", "Decodifique para Unicode legível, codifique texto como escapes, converta entidades HTML ou corrija mojibake comum.", "Copie ou baixe o resultado", "Mantenha o resultado na página, copie para a área de transferência ou baixe um arquivo de texto para usar depois.",
    "Vitrine de resultados selecionados", "Exemplos do conversor ASCII to Unicode", "Estes exemplos selecionados funcionam como uma área de resultados. Eles mostram o que a ferramenta produz sem criar páginas de usuário indexáveis e de baixa qualidade.", "Testar este exemplo", "Decodificar um escape de log", "Leia texto escapado de logs do servidor ou saídas de diagnóstico.", "Decodificar escapes Unicode de JSON", "Transforme strings seguras para JSON em texto multilíngue legível.", "Decodificar uma entidade HTML", "Converta texto de entidade copiado do HTML no símbolo visível.", "Decodificar um ponto de código de emoji", "Use a notação U+ para emoji e símbolos fora do ASCII básico.", "Corrigir mojibake", "Corrija texto UTF-8 interpretado por engano como Latin-1.", "Codificar texto legível", "Crie formatos de escape Unicode para código, documentação ou testes.",
    "Formatos ASCII e Unicode compatíveis", "O conversor foca nos formatos encontrados de verdade ao depurar, analisar e mover texto entre sistemas.", "Escapes Unicode", "Entidades HTML", "Escapes de bytes hexadecimais", "Texto mojibake",
    "Casos de uso comuns", "Uma única página deve atender tanto à conversão rápida quanto à intenção de pesquisa mais profunda. Estas são as principais situações para as quais ela foi criada.", "Logs e diagnósticos", "Decodifique cargas escapadas para tornar erros, nomes, emoji e símbolos legíveis durante a depuração.", "APIs e JSON", "Entenda textos que serviços escapam para transporte ou compatibilidade.", "Limpeza de HTML", "Converta entidades numéricas em caracteres reais antes de editar ou publicar conteúdo.", "Dados de teste e código", "Gere strings de escape estáveis para fixtures, snapshots, documentação e exemplos entre linguagens.",
    "ASCII vs Unicode vs UTF-8", "ASCII é um conjunto pequeno de caracteres para letras inglesas básicas, dígitos e controles. Unicode é o padrão que cobre sistemas de escrita modernos, emoji e símbolos. UTF-8 é uma forma comum de armazenar Unicode como bytes.", "Muitas strings confusas surgem quando bytes, caracteres e formatos de escape são misturados. Esta ferramenta ajuda a inspecionar a representação e recuperar o texto que você queria ler.",
    "Perguntas frequentes", "Perguntas frequentes sobre ASCII to Unicode", "O que é um conversor ASCII to Unicode?", "Ele decodifica representações seguras para ASCII, como escapes Unicode, entidades HTML e códigos U+, em Unicode legível. Também pode codificar texto legível nesses formatos.", "Há suporte para \\uXXXX e emoji?", "Sim. Há suporte para \\uXXXX, \\u{1F600}, pares substitutos como \\uD83D\\uDE00 e notação U+ para emoji e símbolos.", "Posso decodificar entidades HTML?", "Sim. Entidades numéricas decimais e hexadecimais, como &#9731; e &#x2603;, podem ser convertidas em caracteres Unicode visíveis.", "Por que o mojibake acontece?", "Ele costuma aparecer quando bytes UTF-8 são interpretados com outra codificação. O modo de correção tenta reconstruir o texto UTF-8 original quando reconhece esse padrão.", "A conversão é privada?", "Sim. O conversor funciona localmente no seu navegador. A página foi projetada para registrar ações sem registrar o texto colado.", "Mais conversores relacionados serão adicionados?", "Eles só serão adicionados quando resolverem um problema específico de conversão de texto. Esta primeira versão mantém o foco em ASCII to Unicode.",
    "Nota de privacidade", "O texto colado permanece no navegador. O conversor não exige conta, não envia arquivos TXT e não armazena o histórico de conversão em nosso servidor.", "A preferência de idioma fica salva localmente. Se a análise for adicionada, ela registrará ações como converter, copiar e baixar sem enviar o texto de entrada ou saída.", "Ler a Política de Privacidade", "Sobre", "ASCII to Unicode é uma página de conversão focada em desenvolvedores, redatores, editores de localização, testadores de QA e operadores que precisam de Unicode legível a partir de texto escapado ou corrompido.", "A página é intencionalmente focada: um conversor, exemplos selecionados, formatos compatíveis e explicações práticas para problemas comuns de codificação.", "Termos", "Use esta ferramenta para inspeção de texto, depuração, limpeza de conteúdo e preparação de dados de teste. Verifique resultados importantes antes de usá-los em contextos de produção, jurídicos, médicos ou financeiros.", "Você é responsável pelo texto processado e por seguir as regras de qualquer sistema em que o resultado convertido seja usado.", "Ler os Termos de Uso", "Contato", "Para correções, solicitações de recursos, problemas de acessibilidade ou dúvidas de privacidade, entre em contato:", "Ao relatar um problema, informe o modo de conversão e a saída esperada. Não inclua segredos nem texto privado.", "Abrir a página de contato", "Privacidade", "Termos", "Contato"
  ];

  homeValues.fr = [
    "Aller au convertisseur", "Convertisseur", "Exemples", "Formats", "FAQ", "Ouvrir le convertisseur",
    "Outil gratuit dans le navigateur pour les journaux, le code, JSON et le texte corrompu", "Convertisseur ASCII to Unicode", "Décodez les séquences ASCII comme \\u0048, les entités HTML, U+1F680, les octets hexadécimaux et le mojibake en Unicode lisible. Encodez aussi le texte dans des formats Unicode sans quitter cette page.", "Sans inscription", "Conversion gratuite en ligne",
    "Outil interactif", "Convertissez du texte compatible ASCII en Unicode sur une seule page", "Prêt", "Converti", "Copié", "Effacé", "Importé", "Téléchargé",
    "Décoder en Unicode", "Encoder en séquences", "Entités HTML", "Réparer le mojibake", "Format de sortie", "Conversion automatique", "Le sélecteur de format est utilisé pour encoder du texte lisible en séquences ou en entités.",
    "Entrée ASCII", "Collez des séquences, entités, octets, chaînes JSON ou du mojibake.", "Sortie Unicode", "caractères", "Convertir", "Copier", "Effacer", "Permuter", "Importer un TXT", "Télécharger la sortie",
    "Une séquence d'échappement peut être incomplète. Le texte d'origine a été conservé lorsque nécessaire.", "Aucun contenu convertible n'a été détecté, le texte d'origine est donc conservé.", "Saisissez le texte à convertir.",
    "Avant et après", "Unicode lisible à partir de texte compatible ASCII", "Un bon convertisseur affiche immédiatement le résultat, garde l'utilisateur sur la même URL et reste utile avant toute longue explication.", "L'aperçu montre une entrée compatible ASCII transformée en sortie Unicode lisible sur la même page.",
    "Contenu de la page rendu directement en HTML", "Qu'est-ce qu'un convertisseur ASCII to Unicode ?", "Un convertisseur ASCII to Unicode transforme des représentations de texte compatibles ASCII en véritables caractères Unicode lisibles. Ces formes échappées apparaissent souvent dans JSON, les journaux, les fichiers de configuration, les bases de données, les sorties de navigateur et les réponses d'API.", "Cette page réunit le convertisseur, les explications, les exemples, les formats pris en charge et la FAQ sur la même URL canonique pour résoudre le problème sans changer de page.",
    "Comment convertir ASCII en Unicode", "Collez votre texte, choisissez le mode adapté et lancez la conversion sur place. Le résultat apparaît sans ouvrir une page séparée.", "Collez du texte échappé ou corrompu", "Utilisez des séquences Unicode, des entités HTML, la notation U+, des octets hexadécimaux ou du mojibake provenant d'un journal, d'une API, d'un fichier JSON ou d'un ancien export de base de données.", "Choisissez le bon mode de conversion", "Décodez en Unicode lisible, encodez le texte en séquences, convertissez les entités HTML ou réparez le mojibake courant.", "Copiez ou téléchargez le résultat", "Conservez le résultat sur la page, copiez-le dans le presse-papiers ou téléchargez un fichier texte.",
    "Sélection de résultats", "Exemples du convertisseur ASCII to Unicode", "Ces exemples sélectionnés servent de zone de résultats. Ils montrent ce que produit l'outil sans créer de pages utilisateur indexables de faible qualité.", "Essayer cet exemple", "Décoder une séquence de journal", "Lisez le texte échappé provenant de journaux serveur ou de diagnostics.", "Décoder des séquences Unicode JSON", "Transformez des chaînes compatibles JSON en texte multilingue lisible.", "Décoder une entité HTML", "Convertissez une entité copiée depuis du HTML en symbole visible.", "Décoder un point de code emoji", "Utilisez la notation U+ pour les emoji et symboles hors de l'ASCII de base.", "Réparer le mojibake", "Corrigez du texte UTF-8 interprété par erreur comme du Latin-1.", "Encoder du texte lisible", "Créez des formats d'échappement Unicode pour le code, la documentation ou les tests.",
    "Formats ASCII et Unicode pris en charge", "Le convertisseur se concentre sur les formats réellement rencontrés lors du débogage, de l'analyse et du transfert de texte entre systèmes.", "Séquences Unicode", "Entités HTML", "Séquences d'octets hexadécimaux", "Texte mojibake",
    "Cas d'utilisation courants", "Une seule page doit répondre à la fois au besoin de conversion rapide et à une recherche plus approfondie. Voici les principales situations couvertes.", "Journaux et diagnostics", "Décodez les données échappées afin de rendre lisibles les erreurs, noms, emoji et symboles pendant le débogage.", "API et JSON", "Comprenez le texte échappé par des services pour le transport ou la compatibilité.", "Nettoyage HTML", "Convertissez les entités numériques en vrais caractères avant de modifier ou publier du contenu.", "Données de test et code", "Générez des chaînes d'échappement stables pour les fixtures, instantanés, documents et exemples multilingues.",
    "ASCII, Unicode et UTF-8", "ASCII est un petit jeu de caractères pour les lettres anglaises de base, les chiffres et les caractères de contrôle. Unicode couvre les systèmes d'écriture modernes, les emoji et les symboles. UTF-8 est une manière courante de stocker Unicode sous forme d'octets.", "De nombreuses chaînes confuses résultent d'un mélange entre octets, caractères et formats d'échappement. Cet outil aide à inspecter la représentation et à récupérer le texte attendu.",
    "Questions fréquentes", "FAQ ASCII to Unicode", "Qu'est-ce qu'un convertisseur ASCII to Unicode ?", "Il décode les représentations compatibles ASCII, comme les séquences Unicode, les entités HTML et les codes U+, en Unicode lisible. Il peut aussi encoder du texte lisible dans ces formats.", "Prend-il en charge \\uXXXX et les emoji ?", "Oui. Il prend en charge \\uXXXX, \\u{1F600}, les paires de substitution comme \\uD83D\\uDE00 et la notation U+ pour les emoji et symboles.", "Puis-je décoder des entités HTML ?", "Oui. Les entités numériques décimales et hexadécimales comme &#9731; et &#x2603; peuvent être converties en caractères Unicode visibles.", "Pourquoi le mojibake apparaît-il ?", "Il apparaît souvent lorsque des octets UTF-8 sont interprétés avec un autre encodage. Le mode de réparation tente de reconstruire le texte UTF-8 d'origine lorsqu'il reconnaît ce motif.", "La conversion est-elle privée ?", "Oui. Le convertisseur s'exécute localement dans votre navigateur. La page permet d'enregistrer des actions sans enregistrer le texte collé.", "D'autres convertisseurs seront-ils ajoutés ?", "Ils ne seront ajoutés que s'ils résolvent un problème précis de conversion de texte. Cette première version reste centrée sur ASCII to Unicode.",
    "Note de confidentialité", "Le texte collé reste dans votre navigateur. Le convertisseur ne nécessite aucun compte, ne téléverse pas les fichiers TXT et ne conserve pas l'historique sur notre serveur.", "La préférence de langue est enregistrée localement. Si des statistiques sont ajoutées, elles enregistreront des actions comme convertir, copier et télécharger sans envoyer le texte d'entrée ou de sortie.", "Lire la Politique de confidentialité", "À propos", "ASCII to Unicode est une page de conversion destinée aux développeurs, rédacteurs, responsables de localisation, testeurs QA et opérateurs qui ont besoin d'un Unicode lisible à partir de texte échappé ou corrompu.", "La page reste volontairement ciblée : un convertisseur, des exemples sélectionnés, les formats pris en charge et des explications pratiques sur les problèmes d'encodage courants.", "Conditions", "Utilisez cet outil pour inspecter du texte, déboguer, nettoyer du contenu et préparer des données de test. Vérifiez les résultats importants avant tout usage en production ou dans un contexte juridique, médical ou financier.", "Vous êtes responsable du texte traité et du respect des règles de tout système dans lequel le résultat est utilisé.", "Lire les Conditions d'utilisation", "Contact", "Pour signaler une correction, demander une fonction ou poser une question d'accessibilité ou de confidentialité, contactez :", "Lors du signalement d'un problème, indiquez le mode de conversion et le résultat attendu. N'incluez aucun secret ni texte privé.", "Ouvrir la page de contact", "Confidentialité", "Conditions", "Contact"
  ];

  homeValues.de = [
    "Zum Konverter springen", "Konverter", "Beispiele", "Formate", "FAQ", "Konverter öffnen",
    "Kostenloses Browser-Tool für Logs, Code, JSON und fehlerhaften Text", "ASCII to Unicode Konverter", "Dekodieren Sie ASCII-sichere Escape-Sequenzen wie \\u0048, HTML-Entitäten, U+1F680, Hex-Bytes und Mojibake in lesbares Unicode. Kodieren Sie Text auf derselben Seite wieder in Unicode-Formate.", "Keine Anmeldung", "Kostenlose Online-Konvertierung",
    "Interaktives Tool", "ASCII-sicheren Text auf einer Seite in Unicode umwandeln", "Bereit", "Konvertiert", "Kopiert", "Geleert", "Importiert", "Heruntergeladen",
    "In Unicode dekodieren", "Als Escape-Sequenzen kodieren", "HTML-Entitäten", "Mojibake reparieren", "Ausgabeformat", "Automatisch konvertieren", "Die Formatauswahl wird verwendet, wenn lesbarer Text als Escape-Sequenzen oder Entitäten kodiert wird.",
    "ASCII-Eingabe", "Escape-Sequenzen, Entitäten, Byte-Text, JSON-Strings oder Mojibake einfügen.", "Unicode-Ausgabe", "Zeichen", "Konvertieren", "Kopieren", "Leeren", "Tauschen", "TXT importieren", "Ausgabe herunterladen",
    "Eine möglicherweise unvollständige Escape-Sequenz wurde erkannt. Der Originaltext wurde bei Bedarf beibehalten.", "Es wurde kein konvertierbarer Inhalt erkannt, daher bleibt der Originaltext erhalten.", "Geben Sie den zu konvertierenden Text ein.",
    "Vorher und nachher", "Lesbares Unicode aus ASCII-sicherem Text", "Ein guter Konverter zeigt das Ergebnis sofort, hält Nutzer auf derselben URL und ist schon vor jeder längeren Erklärung nützlich.", "Die Vorschau zeigt, wie ASCII-sichere Eingabe auf derselben Seite zu lesbarer Unicode-Ausgabe wird.",
    "Direkt im HTML gerenderter Seiteninhalt", "Was ist ein ASCII to Unicode Konverter?", "Ein ASCII to Unicode Konverter wandelt ASCII-sichere Textdarstellungen in die echten Unicode-Zeichen um, die Menschen lesen möchten. Entwickler finden solche Escape-Formen häufig in JSON, Logs, Konfigurationsdateien, Datenbanken, Browserausgaben und API-Antworten.", "Diese Seite bündelt Konverter, Erklärung, Beispiele, unterstützte Formate und FAQ unter derselben kanonischen URL, damit das Problem ohne Seitenwechsel gelöst werden kann.",
    "ASCII in Unicode umwandeln", "Fügen Sie den Text ein, wählen Sie den passenden Modus und konvertieren Sie direkt auf der Seite. Das Ergebnis erscheint ohne separate Ergebnisseite.", "Escape- oder fehlerhaften Text einfügen", "Verwenden Sie Unicode-Escapes, HTML-Entitäten, U+-Notation, Hex-Bytes oder Mojibake aus Logs, APIs, JSON-Dateien oder alten Datenbankexporten.", "Den richtigen Modus wählen", "In lesbares Unicode dekodieren, lesbaren Text als Escapes kodieren, HTML-Entitäten umwandeln oder übliches Mojibake reparieren.", "Ergebnis kopieren oder herunterladen", "Behalten Sie das Ergebnis auf der Seite, kopieren Sie es oder laden Sie eine Textdatei zur späteren Verwendung herunter.",
    "Ausgewählte Ergebnisse", "Beispiele für den ASCII to Unicode Konverter", "Diese ausgewählten Beispiele dienen als Ergebnisbereich. Sie zeigen die Ausgabe des Tools, ohne minderwertige indexierbare Nutzerseiten zu erzeugen.", "Dieses Beispiel testen", "Log-Escape dekodieren", "Lesen Sie Escape-Text aus Server-Logs oder Diagnoseausgaben.", "JSON-Unicode-Escapes dekodieren", "Wandeln Sie JSON-sichere Strings in lesbaren mehrsprachigen Text um.", "HTML-Entität dekodieren", "Wandeln Sie aus HTML kopierten Entitätstext in das sichtbare Symbol um.", "Emoji-Codepoint dekodieren", "Verwenden Sie U+-Notation für Emoji und Symbole außerhalb von Basis-ASCII.", "Mojibake reparieren", "Korrigieren Sie UTF-8-Text, der versehentlich als Latin-1 gelesen wurde.", "Lesbaren Text kodieren", "Erzeugen Sie Unicode-Escape-Formate für Code, Dokumentation oder Tests.",
    "Unterstützte ASCII- und Unicode-Formate", "Der Konverter konzentriert sich auf Formate, die beim Debuggen, Parsen und Übertragen von Text zwischen Systemen tatsächlich auftreten.", "Unicode-Escapes", "HTML-Entitäten", "Hex-Byte-Escapes", "Mojibake-Text",
    "Häufige Anwendungsfälle", "Eine einzelne Seite sollte sowohl schnelle Tool-Nutzung als auch tiefergehende Suchabsicht erfüllen. Dafür wurde sie hauptsächlich entwickelt.", "Logs und Diagnose", "Dekodieren Sie Escape-Nutzlasten, damit Fehler, Namen, Emoji und Symbole beim Debuggen lesbar werden.", "APIs und JSON", "Verstehen Sie Text, den Dienste für Transport oder Kompatibilität mit Escape-Sequenzen versehen.", "HTML-Bereinigung", "Wandeln Sie numerische Entitäten vor dem Bearbeiten oder Veröffentlichen in echte Zeichen um.", "Testdaten und Code", "Erzeugen Sie stabile Escape-Strings für Fixtures, Snapshots, Dokumentation und sprachübergreifende Beispiele.",
    "ASCII vs. Unicode vs. UTF-8", "ASCII ist ein kleiner Zeichensatz für grundlegende englische Buchstaben, Ziffern und Steuerzeichen. Unicode deckt moderne Schriftsysteme, Emoji und Symbole ab. UTF-8 ist eine verbreitete Methode, Unicode als Bytes zu speichern.", "Viele verwirrende Strings entstehen, wenn Bytes, Zeichen und Escape-Formate vermischt werden. Dieses Tool hilft, die Darstellung zu prüfen und den beabsichtigten Text wiederherzustellen.",
    "Häufige Fragen", "ASCII to Unicode FAQ", "Was ist ein ASCII to Unicode Konverter?", "Er dekodiert ASCII-sichere Darstellungen wie Unicode-Escapes, HTML-Entitäten und U+-Codes in lesbares Unicode. Lesbarer Text kann auch zurück in diese Formate kodiert werden.", "Werden \\uXXXX und Emoji unterstützt?", "Ja. Unterstützt werden \\uXXXX, \\u{1F600}, Ersatzzeichenpaare wie \\uD83D\\uDE00 und U+-Notation für Emoji und Symbole.", "Kann ich HTML-Entitäten dekodieren?", "Ja. Dezimale und hexadezimale numerische Entitäten wie &#9731; und &#x2603; können in sichtbare Unicode-Zeichen umgewandelt werden.", "Warum entsteht Mojibake?", "Mojibake entsteht oft, wenn UTF-8-Bytes als andere Kodierung interpretiert werden. Der Reparaturmodus versucht, bei diesem Muster den ursprünglichen UTF-8-Text wiederherzustellen.", "Ist die Konvertierung privat?", "Ja. Der Konverter läuft lokal in Ihrem Browser. Aktionen können erfasst werden, ohne den eingefügten Text zu speichern.", "Werden weitere Konverter hinzugefügt?", "Nur wenn sie ein konkretes Textkonvertierungsproblem lösen. Diese erste Version konzentriert sich auf ASCII to Unicode.",
    "Datenschutzhinweis", "Eingefügter Text bleibt in Ihrem Browser. Der Konverter erfordert kein Konto, lädt keine TXT-Dateien hoch und speichert keinen Konvertierungsverlauf auf unserem Server.", "Die Sprachauswahl wird lokal gespeichert. Falls Analysen hinzukommen, erfassen sie Aktionen wie Konvertieren, Kopieren und Herunterladen, ohne Ein- oder Ausgabetext zu senden.", "Datenschutzerklärung lesen", "Über", "ASCII to Unicode ist eine fokussierte Textkonvertierungsseite für Entwickler, Autoren, Lokalisierungsredakteure, QA-Tester und Betreiber, die lesbares Unicode aus Escape- oder fehlerhaftem Text benötigen.", "Die Seite bleibt bewusst fokussiert: ein Konverter, ausgewählte Beispiele, unterstützte Formate und praktische Erklärungen zu häufigen Kodierungsproblemen.", "Bedingungen", "Nutzen Sie dieses Tool zur Textprüfung, Fehlersuche, Inhaltsbereinigung und Vorbereitung von Testdaten. Prüfen Sie wichtige Ausgaben vor der Verwendung in Produktion sowie in rechtlichen, medizinischen oder finanziellen Kontexten.", "Sie sind für den verarbeiteten Text und die Einhaltung der Regeln jedes Systems verantwortlich, in dem die Ausgabe verwendet wird.", "Nutzungsbedingungen lesen", "Kontakt", "Für Korrekturen, Funktionswünsche, Barrierefreiheitsprobleme oder Datenschutzfragen kontaktieren Sie:", "Geben Sie bei einem Problem den Konvertierungsmodus und die erwartete Ausgabe an. Senden Sie keine Geheimnisse oder privaten Texte.", "Kontaktseite öffnen", "Datenschutz", "Bedingungen", "Kontakt"
  ];

  homeValues.ja = [
    "コンバーターへ移動", "コンバーター", "例", "形式", "よくある質問", "コンバーターを開く",
    "ログ、コード、JSON、文字化けに使える無料ブラウザツール", "ASCII to Unicode コンバーター", "\\u0048、HTML エンティティ、U+1F680、16進バイト、文字化けなどの ASCII セーフな表現を読みやすい Unicode にデコードします。このページを離れずに、テキストを Unicode 形式へ戻すこともできます。", "登録不要", "無料オンライン変換",
    "インタラクティブツール", "ASCII セーフなテキストを1ページで Unicode に変換", "準備完了", "変換完了", "コピーしました", "消去しました", "読み込みました", "ダウンロードしました",
    "Unicode にデコード", "エスケープにエンコード", "HTML エンティティ", "文字化けを修復", "出力形式", "自動変換", "形式セレクターは、読みやすいテキストをエスケープやエンティティに変換するときに使用します。",
    "ASCII 入力", "エスケープ、エンティティ、バイト文字列、JSON 文字列、文字化けを貼り付けます。", "Unicode 出力", "文字", "変換", "コピー", "消去", "入れ替え", "TXT を読み込む", "出力をダウンロード",
    "不完全な可能性があるエスケープシーケンスを検出しました。必要な箇所では元のテキストを保持しています。", "変換できる内容が見つからなかったため、元のテキストを保持しています。", "変換するテキストを入力してください。",
    "変換前と変換後", "ASCII セーフなテキストから読みやすい Unicode へ", "優れたコンバーターは結果をすぐに表示し、同じ URL 上で作業を完了でき、長い説明を読む前から役立つ必要があります。", "このプレビューは、ASCII セーフな入力が同じページで読みやすい Unicode 出力に変わる様子を示しています。",
    "HTML に直接レンダリングされたページ内容", "ASCII to Unicode コンバーターとは？", "ASCII to Unicode コンバーターは、ASCII セーフなテキスト表現を実際に読める Unicode 文字へ変換します。開発者は JSON、ログ、設定ファイル、データベース、ブラウザ出力、API レスポンスでこうしたエスケープ形式をよく目にします。", "このページでは、コンバーター、説明、例、対応形式、FAQ を同じ canonical URL にまとめ、ページを移動せず問題を解決できます。",
    "ASCII を Unicode に変換する方法", "テキストを貼り付け、問題に合うモードを選び、その場で変換します。別の結果ページを開かずに結果が表示されます。", "エスケープまたは文字化けしたテキストを貼り付ける", "ログ、API、JSON ファイル、古いデータベース出力からコピーした Unicode エスケープ、HTML エンティティ、U+ 表記、16進バイト、文字化けを使用できます。", "適切な変換モードを選ぶ", "読みやすい Unicode へのデコード、テキストのエスケープ化、HTML エンティティの変換、一般的な文字化けの修復から選びます。", "結果をコピーまたはダウンロード", "結果をページに残したままコピーするか、後で使えるテキストファイルとしてダウンロードします。",
    "厳選された変換結果", "ASCII to Unicode コンバーターの例", "厳選した例を結果表示として掲載しています。低品質なユーザーページを大量に作ることなく、ツールの出力を確認できます。", "この例を試す", "ログのエスケープをデコード", "サーバーログや診断出力のエスケープされたテキストを読み取ります。", "JSON の Unicode エスケープをデコード", "JSON セーフな文字列を読みやすい多言語テキストへ戻します。", "HTML エンティティをデコード", "HTML からコピーしたエンティティを表示可能な記号へ変換します。", "絵文字のコードポイントをデコード", "基本 ASCII 外の絵文字や記号には U+ 表記を使用します。", "文字化けを修復", "UTF-8 が誤って Latin-1 として解釈された文字列を修正します。", "読みやすいテキストをエンコード", "コード、文書、テスト向けの Unicode エスケープ形式を生成します。",
    "対応する ASCII と Unicode の形式", "デバッグ、解析、システム間のテキスト移動で実際に遭遇する形式を中心に対応しています。", "Unicode エスケープ", "HTML エンティティ", "16進バイトエスケープ", "文字化けテキスト",
    "主な利用例", "1つのページで、すばやい変換と詳しい情報を探す目的の両方に対応します。主な利用場面は次のとおりです。", "ログと診断", "エスケープされたデータをデコードし、デバッグ中にエラー、名前、絵文字、記号を読みやすくします。", "API と JSON", "転送や互換性のためにサービスがエスケープしたテキストを理解できます。", "HTML の整理", "編集や公開の前に数値エンティティを実際の文字へ変換します。", "テストデータとコード", "fixture、スナップショット、文書、多言語の例に使える安定したエスケープ文字列を生成します。",
    "ASCII・Unicode・UTF-8 の違い", "ASCII は基本的な英字、数字、制御文字を扱う小さな文字セットです。Unicode は現代の文字体系、絵文字、記号などを扱う文字規格です。UTF-8 は Unicode をバイトとして保存する一般的な方法です。", "分かりにくい文字列の多くは、バイト、文字、エスケープ形式の混在で発生します。このツールは表現を確認し、本来読みたかったテキストを復元するのに役立ちます。",
    "よくある質問", "ASCII to Unicode FAQ", "ASCII to Unicode コンバーターとは？", "Unicode エスケープ、HTML エンティティ、U+ コードなどの ASCII セーフな表現を読みやすい Unicode にデコードします。読みやすいテキストをこれらの形式へエンコードすることもできます。", "\\uXXXX と絵文字に対応していますか？", "はい。\\uXXXX、\\u{1F600}、\\uD83D\\uDE00 のようなサロゲートペア、絵文字や記号の U+ 表記に対応しています。", "HTML エンティティをデコードできますか？", "はい。&#9731; や &#x2603; のような10進・16進の数値エンティティを表示可能な Unicode 文字へ変換できます。", "文字化けはなぜ起こりますか？", "UTF-8 のバイトが別の文字コードとして解釈されるとよく発生します。修復モードはこのパターンを検出したときに元の UTF-8 テキストの復元を試みます。", "変換内容は非公開ですか？", "はい。変換はブラウザ内でローカルに実行されます。貼り付けたテキストを記録せず、操作イベントだけを記録できる設計です。", "関連コンバーターは今後追加されますか？", "明確な文字変換の問題を解決できる場合にのみ追加します。最初のバージョンは ASCII to Unicode に集中します。",
    "プライバシーについて", "貼り付けたテキストはブラウザ内に留まります。アカウントは不要で、TXT ファイルをアップロードせず、変換履歴をサーバーに保存しません。", "言語設定はブラウザに保存されます。将来解析機能を追加しても、入力・出力テキストを送信せず、変換、コピー、ダウンロードなどの操作だけを記録します。", "プライバシーポリシーを読む", "このサイトについて", "ASCII to Unicode は、エスケープまたは文字化けしたテキストから読みやすい Unicode を必要とする開発者、ライター、ローカライズ担当者、QA テスター、運用担当者向けの変換ページです。", "コンバーター、厳選例、対応形式、一般的な文字コード問題の実用的な説明に機能を絞っています。", "利用規約", "テキスト確認、デバッグ、コンテンツ整理、テストデータ作成に使用できます。本番、法律、医療、金融に関わる用途では重要な出力を必ず確認してください。", "処理するテキストと、変換結果を使用するシステムの規則を守る責任は利用者にあります。", "利用規約を読む", "お問い合わせ", "修正、機能要望、アクセシビリティ、プライバシーに関するお問い合わせ先：", "問題を報告するときは、変換モードと期待する出力を記載してください。秘密情報や個人情報は含めないでください。", "お問い合わせページを開く", "プライバシー", "利用規約", "お問い合わせ"
  ];

  homeValues.ko = [
    "변환기로 이동", "변환기", "예시", "형식", "자주 묻는 질문", "변환기 열기",
    "로그, 코드, JSON 및 깨진 텍스트를 위한 무료 브라우저 도구", "ASCII to Unicode 변환기", "\\u0048, HTML 엔터티, U+1F680, 16진수 바이트 및 모지바케 같은 ASCII 안전 표현을 읽을 수 있는 Unicode로 디코딩합니다. 이 페이지를 벗어나지 않고 텍스트를 Unicode 형식으로 다시 인코딩할 수도 있습니다.", "가입 불필요", "무료 온라인 변환",
    "대화형 도구", "ASCII 안전 텍스트를 한 페이지에서 Unicode로 변환", "준비됨", "변환됨", "복사됨", "지워짐", "가져옴", "다운로드됨",
    "Unicode로 디코딩", "이스케이프로 인코딩", "HTML 엔터티", "모지바케 복구", "출력 형식", "자동 변환", "형식 선택기는 읽을 수 있는 텍스트를 이스케이프나 엔터티로 인코딩할 때 사용됩니다.",
    "ASCII 입력", "이스케이프, 엔터티, 바이트 텍스트, JSON 문자열 또는 모지바케를 붙여 넣으세요.", "Unicode 출력", "문자", "변환", "복사", "지우기", "바꾸기", "TXT 가져오기", "출력 다운로드",
    "불완전할 수 있는 이스케이프 시퀀스가 감지되었습니다. 필요한 곳에는 원문을 유지했습니다.", "변환 가능한 내용을 찾지 못해 원문을 유지했습니다.", "변환할 텍스트를 입력하세요.",
    "변환 전과 후", "ASCII 안전 텍스트에서 읽기 쉬운 Unicode로", "좋은 변환기는 결과를 즉시 보여 주고, 사용자를 같은 URL에 머물게 하며, 긴 설명 전부터 유용해야 합니다.", "미리보기는 ASCII 안전 입력이 같은 페이지에서 읽기 쉬운 Unicode 출력으로 바뀌는 모습을 보여 줍니다.",
    "HTML에 직접 렌더링된 페이지 콘텐츠", "ASCII to Unicode 변환기란 무엇인가요?", "ASCII to Unicode 변환기는 ASCII 안전 텍스트 표현을 사람이 읽을 수 있는 실제 Unicode 문자로 바꿉니다. 개발자는 JSON, 로그, 설정 파일, 데이터베이스, 브라우저 출력 및 API 응답에서 이런 이스케이프 형식을 자주 접합니다.", "이 페이지는 변환기, 설명, 예시, 지원 형식 및 FAQ를 동일한 canonical URL에 모아 페이지를 이동하지 않고 문제를 해결할 수 있게 합니다.",
    "ASCII를 Unicode로 변환하는 방법", "텍스트를 붙여 넣고 문제에 맞는 모드를 선택한 뒤 그 자리에서 변환하세요. 별도의 결과 페이지 없이 결과가 나타납니다.", "이스케이프되거나 깨진 텍스트 붙여 넣기", "로그, API, JSON 파일 또는 오래된 데이터베이스 내보내기에서 가져온 Unicode 이스케이프, HTML 엔터티, U+ 표기, 16진수 바이트 또는 모지바케를 사용할 수 있습니다.", "알맞은 변환 모드 선택", "읽을 수 있는 Unicode로 디코딩하거나, 텍스트를 이스케이프로 인코딩하거나, HTML 엔터티를 변환하거나, 일반적인 모지바케를 복구합니다.", "결과 복사 또는 다운로드", "결과를 페이지에 유지한 채 클립보드로 복사하거나 나중에 사용할 텍스트 파일로 다운로드하세요.",
    "엄선된 결과 보기", "ASCII to Unicode 변환기 예시", "엄선한 예시는 결과 표시 영역처럼 작동합니다. 품질이 낮은 사용자 페이지를 만들지 않고도 도구의 결과를 보여 줍니다.", "이 예시 사용", "로그 이스케이프 디코딩", "서버 로그나 진단 출력의 이스케이프 텍스트를 읽습니다.", "JSON Unicode 이스케이프 디코딩", "JSON 안전 문자열을 읽기 쉬운 다국어 텍스트로 되돌립니다.", "HTML 엔터티 디코딩", "HTML에서 복사한 엔터티 텍스트를 보이는 기호로 변환합니다.", "이모지 코드 포인트 디코딩", "기본 ASCII 밖의 이모지와 기호에 U+ 표기를 사용합니다.", "모지바케 복구", "UTF-8 텍스트가 Latin-1로 잘못 읽힌 일반적인 문제를 수정합니다.", "읽을 수 있는 텍스트 인코딩", "코드, 문서 또는 테스트용 Unicode 이스케이프 형식을 만듭니다.",
    "지원하는 ASCII 및 Unicode 형식", "이 변환기는 디버깅, 구문 분석 및 시스템 간 텍스트 이동 중 실제로 만나는 형식에 집중합니다.", "Unicode 이스케이프", "HTML 엔터티", "16진수 바이트 이스케이프", "모지바케 텍스트",
    "일반적인 사용 사례", "한 페이지에서 빠른 도구 사용과 더 깊은 검색 의도를 모두 충족합니다. 다음은 이 페이지가 만들어진 주요 상황입니다.", "로그 및 진단", "이스케이프된 데이터를 디코딩해 디버깅 중 오류, 이름, 이모지 및 기호를 읽을 수 있게 합니다.", "API 및 JSON", "서비스가 전송이나 호환성을 위해 이스케이프한 텍스트를 이해할 수 있습니다.", "HTML 정리", "콘텐츠를 편집하거나 게시하기 전에 숫자 엔터티를 실제 문자로 변환합니다.", "테스트 데이터 및 코드", "fixture, 스냅샷, 문서 및 언어 간 예시에 쓸 안정적인 이스케이프 문자열을 생성합니다.",
    "ASCII, Unicode, UTF-8 비교", "ASCII는 기본 영문자, 숫자 및 제어 문자를 위한 작은 문자 집합입니다. Unicode는 현대 문자 체계, 이모지 및 기호를 아우르는 문자 표준입니다. UTF-8은 Unicode를 바이트로 저장하는 일반적인 방식입니다.", "바이트, 문자, 이스케이프 형식이 섞이면 혼란스러운 문자열이 생깁니다. 이 도구는 표현 방식을 확인하고 원래 읽으려던 텍스트를 복원하는 데 도움을 줍니다.",
    "자주 묻는 질문", "ASCII to Unicode FAQ", "ASCII to Unicode 변환기란 무엇인가요?", "Unicode 이스케이프, HTML 엔터티, U+ 코드 같은 ASCII 안전 표현을 읽을 수 있는 Unicode로 디코딩합니다. 읽을 수 있는 텍스트를 해당 형식으로 다시 인코딩할 수도 있습니다.", "\\uXXXX와 이모지를 지원하나요?", "예. \\uXXXX, \\u{1F600}, \\uD83D\\uDE00 같은 서로게이트 쌍, 이모지와 기호용 U+ 표기를 지원합니다.", "HTML 엔터티를 디코딩할 수 있나요?", "예. &#9731; 및 &#x2603; 같은 10진수와 16진수 숫자 엔터티를 보이는 Unicode 문자로 변환할 수 있습니다.", "모지바케는 왜 발생하나요?", "UTF-8 바이트가 다른 인코딩으로 해석될 때 자주 발생합니다. 복구 모드는 이 패턴이 있을 때 원래 UTF-8 텍스트를 재구성합니다.", "변환은 비공개인가요?", "예. 변환기는 브라우저에서 로컬로 실행됩니다. 붙여 넣은 텍스트를 기록하지 않고 동작 이벤트만 기록하도록 설계되었습니다.", "관련 변환기가 더 추가되나요?", "명확한 텍스트 변환 문제를 해결하는 경우에만 추가됩니다. 첫 버전은 ASCII to Unicode에 집중합니다.",
    "개인정보 안내", "붙여 넣은 텍스트는 브라우저에 남습니다. 계정이 필요 없고 TXT 파일을 업로드하지 않으며 변환 기록을 서버에 저장하지 않습니다.", "언어 설정은 브라우저에 로컬로 저장됩니다. 분석 기능이 추가되어도 입력이나 출력 텍스트를 보내지 않고 변환, 복사, 다운로드 같은 동작만 기록합니다.", "개인정보 처리방침 읽기", "소개", "ASCII to Unicode는 이스케이프되거나 깨진 텍스트에서 읽을 수 있는 Unicode가 필요한 개발자, 작성자, 현지화 편집자, QA 테스터 및 운영자를 위한 변환 페이지입니다.", "한 가지 변환기, 엄선된 예시, 지원 형식 및 일반적인 문자 인코딩 문제에 대한 실용적인 설명에 의도적으로 집중합니다.", "이용약관", "텍스트 검사, 디버깅, 콘텐츠 정리 및 테스트 데이터 준비에 이 도구를 사용하세요. 프로덕션, 법률, 의료 또는 금융 환경에서 중요한 결과를 사용하기 전에 확인해야 합니다.", "처리하는 텍스트와 변환 결과를 사용하는 시스템의 규칙을 준수할 책임은 사용자에게 있습니다.", "이용약관 읽기", "문의", "수정, 기능 요청, 접근성 문제 또는 개인정보 질문은 다음으로 문의하세요:", "문제를 보고할 때 변환 모드와 예상 결과를 포함하세요. 비밀이나 개인 텍스트는 포함하지 마세요.", "문의 페이지 열기", "개인정보", "이용약관", "문의"
  ];

  const home = Object.fromEntries(Object.entries(homeValues).map(([lang, values]) => [lang, zip(homeKeys, values)]));
  const homeExtras = {
    es: { topLabel: "ARRIBA", formatDecimal: "HTML decimal", formatHex: "HTML hexadecimal", formatUnicodeText: "\\u0048, \\u{1F600}, \\uD83D\\uDE00, %u4F60 y U+1F680.", formatHtmlText: "&#9731; y &#x2603; se decodifican como símbolos legibles y también pueden generarse a partir del texto.", formatHexText: "Las secuencias de bytes como \\xE2\\x98\\x80 se decodifican como UTF-8 cuando forman grupos válidos.", formatBrokenText: "Las cadenas dañadas habituales, como cafÃ©, pueden reconstruirse si los bytes originales eran UTF-8.", previewAlt: "Vista previa de secuencias ASCII convertidas en texto Unicode legible" },
    pt: { topLabel: "TOPO", formatDecimal: "HTML decimal", formatHex: "HTML hexadecimal", formatUnicodeText: "\\u0048, \\u{1F600}, \\uD83D\\uDE00, %u4F60 e U+1F680.", formatHtmlText: "&#9731; e &#x2603; são decodificados como símbolos legíveis e também podem ser gerados a partir do texto.", formatHexText: "Sequências de bytes como \\xE2\\x98\\x80 são decodificadas como UTF-8 quando formam grupos válidos.", formatBrokenText: "Strings corrompidas comuns, como cafÃ©, podem ser reconstruídas quando os bytes originais eram UTF-8.", previewAlt: "Prévia de sequências ASCII convertidas em texto Unicode legível" },
    fr: { topLabel: "HAUT", formatDecimal: "HTML décimal", formatHex: "HTML hexadécimal", formatUnicodeText: "\\u0048, \\u{1F600}, \\uD83D\\uDE00, %u4F60 et U+1F680.", formatHtmlText: "&#9731; et &#x2603; sont décodés en symboles lisibles et peuvent aussi être générés depuis le texte.", formatHexText: "Les séquences d'octets comme \\xE2\\x98\\x80 sont décodées en UTF-8 lorsqu'elles forment des groupes valides.", formatBrokenText: "Les chaînes corrompues courantes comme cafÃ© peuvent être reconstruites si les octets d'origine étaient en UTF-8.", previewAlt: "Aperçu de séquences ASCII converties en texte Unicode lisible" },
    de: { topLabel: "OBEN", formatDecimal: "HTML dezimal", formatHex: "HTML hexadezimal", formatUnicodeText: "\\u0048, \\u{1F600}, \\uD83D\\uDE00, %u4F60 und U+1F680.", formatHtmlText: "&#9731; und &#x2603; werden in lesbare Symbole dekodiert und können auch aus Text erzeugt werden.", formatHexText: "Byte-Sequenzen wie \\xE2\\x98\\x80 werden als UTF-8 dekodiert, wenn sie gültige Bytefolgen bilden.", formatBrokenText: "Häufige fehlerhafte Strings wie cafÃ© können rekonstruiert werden, wenn die ursprünglichen Bytes UTF-8 waren.", previewAlt: "Vorschau auf die Umwandlung von ASCII-Sequenzen in lesbaren Unicode-Text" },
    ja: { topLabel: "上へ", formatDecimal: "HTML 10進数", formatHex: "HTML 16進数", formatUnicodeText: "\\u0048、\\u{1F600}、\\uD83D\\uDE00、%u4F60、U+1F680。", formatHtmlText: "&#9731; と &#x2603; を読みやすい記号へデコードし、入力テキストから生成することもできます。", formatHexText: "\\xE2\\x98\\x80 のようなバイト列は、有効な並びの場合に UTF-8 としてデコードされます。", formatBrokenText: "元のバイトが UTF-8 なら、cafÃ© のような一般的な文字化けを復元できます。", previewAlt: "ASCII エスケープを読みやすい Unicode テキストへ変換するプレビュー" },
    ko: { topLabel: "위로", formatDecimal: "HTML 10진수", formatHex: "HTML 16진수", formatUnicodeText: "\\u0048, \\u{1F600}, \\uD83D\\uDE00, %u4F60 및 U+1F680.", formatHtmlText: "&#9731; 및 &#x2603;을 읽을 수 있는 기호로 디코딩하고 입력 텍스트에서 생성할 수도 있습니다.", formatHexText: "\\xE2\\x98\\x80 같은 바이트 시퀀스는 유효한 바이트 묶음일 때 UTF-8로 디코딩됩니다.", formatBrokenText: "원래 바이트가 UTF-8이면 cafÃ© 같은 일반적인 깨진 문자열을 복원할 수 있습니다.", previewAlt: "ASCII 이스케이프를 읽기 쉬운 Unicode 텍스트로 변환하는 미리보기" }
  };
  Object.entries(homeExtras).forEach(([lang, values]) => Object.assign(home[lang], values));
  const analyticsHomeCopy = {
    es: {
      faq5A: "Sí. La conversión se ejecuta localmente en tu navegador. Google Analytics registra eventos de página y de acciones, pero no recibe el texto de entrada ni el resultado convertido.",
      privacyText2: "La preferencia de idioma se guarda localmente. Google Analytics mide el uso de la página y acciones como convertir, copiar y descargar sin enviar la entrada, la salida ni el contenido TXT importado."
    },
    pt: {
      faq5A: "Sim. A conversão é executada localmente no navegador. O Google Analytics registra eventos de página e ações, mas não recebe o texto de entrada nem a saída convertida.",
      privacyText2: "A preferência de idioma é salva localmente. O Google Analytics mede o uso da página e ações como converter, copiar e baixar sem enviar entrada, saída ou conteúdo TXT importado."
    },
    fr: {
      faq5A: "Oui. La conversion s'exécute localement dans votre navigateur. Google Analytics enregistre des événements de page et d'action, mais ne reçoit ni le texte saisi ni le résultat converti.",
      privacyText2: "La langue choisie est enregistrée localement. Google Analytics mesure l'utilisation des pages et des actions comme convertir, copier et télécharger, sans envoyer le texte saisi, le résultat ou le contenu TXT importé."
    },
    de: {
      faq5A: "Ja. Die Konvertierung läuft lokal in Ihrem Browser. Google Analytics erfasst Seiten- und Aktionsereignisse, erhält aber weder den Eingabetext noch die konvertierte Ausgabe.",
      privacyText2: "Die Sprachauswahl wird lokal gespeichert. Google Analytics misst Seitennutzung und Aktionen wie Konvertieren, Kopieren und Herunterladen, ohne Eingabe, Ausgabe oder importierte TXT-Inhalte zu senden."
    },
    ja: {
      faq5A: "はい。変換はブラウザ内でローカルに実行されます。Google Analytics はページと操作のイベントを記録しますが、入力テキストや変換結果は受信しません。",
      privacyText2: "言語設定はブラウザに保存されます。Google Analytics はページ利用と変換、コピー、ダウンロードなどの操作を測定しますが、入力、出力、読み込んだ TXT の内容は送信しません。"
    },
    ko: {
      faq5A: "예. 변환은 브라우저에서 로컬로 실행됩니다. Google Analytics는 페이지 및 동작 이벤트를 기록하지만 입력 텍스트나 변환된 출력은 수신하지 않습니다.",
      privacyText2: "언어 설정은 브라우저에 로컬로 저장됩니다. Google Analytics는 페이지 사용과 변환, 복사, 다운로드 같은 동작을 측정하지만 입력, 출력 또는 가져온 TXT 내용은 전송하지 않습니다."
    }
  };
  Object.entries(analyticsHomeCopy).forEach(([lang, values]) => Object.assign(home[lang], values));
  const commonKeys = ["navConverter", "navExamples", "navFormats", "navFaq", "navOpen", "footerPrivacy", "footerTerms", "footerContact"];
  const common = Object.fromEntries(Object.keys(home).map((lang) => [lang, Object.fromEntries(commonKeys.map((key) => [key, home[lang][key]]))]));
  common.zh = {
    navConverter: "转换器", navExamples: "示例", navFormats: "格式", navFaq: "常见问题", navOpen: "打开转换器",
    footerPrivacy: "隐私", footerTerms: "条款", footerContact: "联系"
  };

  const pageKeys = {
    privacy: ["skipPrivacy", "privacyEyebrow", "privacyH1", "lastUpdated", "privacyIntro", "localTitle", "localText", "storageTitle", "storageText", "analyticsTitle", "analyticsText", "sensitiveTitle", "sensitiveText", "contactTitle", "privacyContactText"],
    terms: ["skipTerms", "termsEyebrow", "termsH1", "lastUpdated", "termsIntro", "permittedTitle", "permittedText", "responsibilityTitle", "responsibilityText", "verificationTitle", "verificationText", "warrantyTitle", "warrantyText", "contactTitle", "termsContactText"],
    contact: ["skipContact", "contactEyebrow", "contactH1", "contactIntro", "feedbackTitle", "feedbackText", "accessibilityTitle", "accessibilityText", "questionsTitle", "questionsText", "suggestedTitle", "suggestedText"],
    notFound: ["skipContent", "notFoundH1", "notFoundText", "notFoundOpen", "notFoundBack"]
  };

  const pageValues = {
    privacy: {
      zh: ["跳到隐私政策", "隐私", "隐私政策", "最后更新：2026年7月11日。", "ASCII to Unicode 是一款注重隐私、基于浏览器的文本转换器。核心转换在浏览器本地运行，无需账号。", "本地转换", "粘贴到转换器的文本会在浏览器中处理。网站无需把输入、输出或导入的 TXT 文件上传到服务器即可完成转换。", "本地存储", "语言切换会把所选语言保存在 localStorage 中，让每个页面都能记住你的偏好。你可以在浏览器设置中清除它。", "分析事件", "如果未来启用分析，只会记录转换、模式切换、尝试示例、复制、下载和语言切换等操作事件。输入和输出文本不会作为分析数据发送。", "敏感文本", "除非你愿意在当前浏览器会话中处理，否则不要向任何在线工具粘贴密码、私钥、受监管数据或其他秘密。", "联系", "如有隐私问题，请发送邮件至"],
      es: ["Ir a la política de privacidad", "Privacidad", "Política de privacidad", "Última actualización: 11 de julio de 2026.", "ASCII to Unicode está diseñado como un convertidor de texto privado basado en el navegador. La conversión principal se ejecuta localmente y no requiere una cuenta.", "Conversión local", "El texto pegado se procesa en el navegador. El sitio no necesita subir la entrada, la salida ni el archivo TXT importado a un servidor.", "Almacenamiento local", "El selector guarda el idioma elegido en localStorage para recordarlo en todas las páginas. Puedes borrarlo desde la configuración del navegador.", "Eventos de análisis", "Si se activa la analítica, se limitará a acciones como convertir, cambiar de modo, probar ejemplos, copiar, descargar y cambiar de idioma. El texto de entrada y salida no se enviará.", "Texto sensible", "No pegues contraseñas, claves privadas, datos regulados ni otros secretos en una herramienta en línea salvo que aceptes procesarlos en tu sesión del navegador.", "Contacto", "Para preguntas de privacidad, escribe a"],
      pt: ["Ir para a política de privacidade", "Privacidade", "Política de Privacidade", "Última atualização: 11 de julho de 2026.", "ASCII to Unicode foi criado como um conversor de texto privado no navegador. A conversão principal é executada localmente e não exige conta.", "Conversão local", "O texto colado é processado no navegador. O site não precisa enviar entrada, saída ou arquivo TXT importado para um servidor.", "Armazenamento local", "O seletor salva o idioma escolhido no localStorage para lembrá-lo em todas as páginas. Você pode apagá-lo nas configurações do navegador.", "Eventos de análise", "Se a análise for ativada, ficará limitada a ações como converter, mudar o modo, testar exemplos, copiar, baixar e trocar o idioma. O texto de entrada e saída não será enviado.", "Texto sensível", "Não cole senhas, chaves privadas, dados regulamentados ou outros segredos em uma ferramenta online, a menos que aceite processá-los na sessão do navegador.", "Contato", "Para dúvidas de privacidade, envie um e-mail para"],
      fr: ["Aller à la politique de confidentialité", "Confidentialité", "Politique de confidentialité", "Dernière mise à jour : 11 juillet 2026.", "ASCII to Unicode est un convertisseur de texte privé fonctionnant dans le navigateur. La conversion principale s'exécute localement et ne nécessite aucun compte.", "Conversion locale", "Le texte collé est traité dans le navigateur. Le site n'a pas besoin d'envoyer l'entrée, la sortie ou le fichier TXT importé à un serveur.", "Stockage local", "Le sélecteur enregistre la langue choisie dans localStorage afin de la mémoriser sur toutes les pages. Vous pouvez l'effacer dans les réglages du navigateur.", "Événements statistiques", "Si des statistiques sont activées, elles se limiteront aux actions comme convertir, changer de mode, essayer un exemple, copier, télécharger et changer de langue. Aucun texte d'entrée ou de sortie ne sera envoyé.", "Texte sensible", "Ne collez pas de mots de passe, clés privées, données réglementées ou autres secrets dans un outil en ligne, sauf si vous acceptez leur traitement dans votre session de navigateur.", "Contact", "Pour toute question de confidentialité, écrivez à"],
      de: ["Zur Datenschutzerklärung springen", "Datenschutz", "Datenschutzerklärung", "Zuletzt aktualisiert: 11. Juli 2026.", "ASCII to Unicode ist als privater, browserbasierter Textkonverter konzipiert. Die Kernkonvertierung läuft lokal im Browser und erfordert kein Konto.", "Lokale Konvertierung", "Eingefügter Text wird im Browser verarbeitet. Eingabe, Ausgabe und importierte TXT-Dateien müssen nicht an einen Server übertragen werden.", "Lokaler Speicher", "Die Sprachauswahl speichert die gewählte Sprache in localStorage, damit sie auf allen Seiten erhalten bleibt. Sie kann in den Browsereinstellungen gelöscht werden.", "Analyseereignisse", "Falls Analysen aktiviert werden, beschränken sie sich auf Aktionen wie Konvertieren, Moduswechsel, Beispielaufruf, Kopieren, Herunterladen und Sprachwechsel. Ein- und Ausgabetext wird nicht gesendet.", "Sensible Texte", "Fügen Sie keine Passwörter, privaten Schlüssel, regulierten Daten oder andere Geheimnisse in Online-Tools ein, sofern Sie deren Verarbeitung in Ihrer Browsersitzung nicht akzeptieren.", "Kontakt", "Bei Datenschutzfragen schreiben Sie an"],
      ja: ["プライバシーポリシーへ移動", "プライバシー", "プライバシーポリシー", "最終更新日：2026年7月11日。", "ASCII to Unicode はプライバシーを重視したブラウザベースのテキスト変換ツールです。主要な変換はブラウザ内で実行され、アカウントは不要です。", "ローカル変換", "貼り付けたテキストはブラウザ内で処理されます。入力、出力、読み込んだ TXT ファイルをサーバーへ送信する必要はありません。", "ローカルストレージ", "選択した言語は localStorage に保存され、すべてのページで設定が維持されます。ブラウザ設定から削除できます。", "解析イベント", "将来解析を有効にしても、変換、モード変更、例の利用、コピー、ダウンロード、言語変更などの操作だけを記録します。入力・出力テキストは送信しません。", "機密テキスト", "ブラウザセッション内で処理することに同意できない場合、パスワード、秘密鍵、規制対象データなどをオンラインツールへ貼り付けないでください。", "お問い合わせ", "プライバシーに関するお問い合わせ先："],
      ko: ["개인정보 처리방침으로 이동", "개인정보", "개인정보 처리방침", "최종 업데이트: 2026년 7월 11일.", "ASCII to Unicode는 개인정보를 중시하는 브라우저 기반 텍스트 변환기입니다. 핵심 변환은 브라우저에서 로컬로 실행되며 계정이 필요하지 않습니다.", "로컬 변환", "붙여 넣은 텍스트는 브라우저에서 처리됩니다. 입력, 출력 또는 가져온 TXT 파일을 서버에 업로드할 필요가 없습니다.", "로컬 저장소", "선택한 언어는 localStorage에 저장되어 모든 페이지에서 유지됩니다. 브라우저 설정에서 삭제할 수 있습니다.", "분석 이벤트", "분석 기능이 활성화되어도 변환, 모드 변경, 예시 사용, 복사, 다운로드, 언어 전환 같은 동작만 기록합니다. 입력 및 출력 텍스트는 전송하지 않습니다.", "민감한 텍스트", "브라우저 세션에서 처리하는 데 동의하지 않는다면 비밀번호, 개인 키, 규제 데이터 또는 기타 비밀을 온라인 도구에 붙여 넣지 마세요.", "문의", "개인정보 관련 문의 이메일:" ]
    },
    terms: {
      zh: ["跳到使用条款", "条款", "使用条款", "最后更新：2026年7月11日。", "使用 ASCII to Unicode 即表示你同意负责任地使用转换器，并在依赖重要输出前自行核对。", "允许的用途", "你可以把工具用于文本检查、调试、内容清理、本地化审核、测试数据准备及相关 ASCII 或 Unicode 转换。", "你的责任", "你需要对处理的文本、复制或下载的输出，以及遵守项目、工作场所或所在司法管辖区的规则负责。", "输出核验", "转换器适合检查和格式化，但重要输出用于生产系统、法律文件、医疗流程、财务记录或安全敏感场景前必须核对。", "无担保", "网站按现状提供，并可能随时间变化。我们不保证服务始终可用，也不保证每一种格式错误的输入都能完美转换。", "联系", "如对条款有疑问，请发送邮件至"],
      es: ["Ir a los términos", "Términos", "Términos de uso", "Última actualización: 11 de julio de 2026.", "Al usar ASCII to Unicode, aceptas utilizar el convertidor de forma responsable y verificar cualquier resultado importante antes de confiar en él.", "Uso permitido", "Puedes usar la herramienta para inspección de texto, depuración, limpieza de contenido, revisión de localización, preparación de datos de prueba y conversiones relacionadas con ASCII o Unicode.", "Tu responsabilidad", "Eres responsable del texto procesado, la salida copiada o descargada y el cumplimiento de las reglas aplicables a tu proyecto, trabajo o jurisdicción.", "Verificación de resultados", "El convertidor sirve para inspeccionar y dar formato, pero los resultados importantes deben verificarse antes de usarlos en producción o en ámbitos legales, médicos, financieros o sensibles para la seguridad.", "Sin garantía", "El sitio se ofrece tal cual y puede cambiar. No garantizamos disponibilidad ininterrumpida ni una conversión perfecta para todas las entradas dañadas.", "Contacto", "Para preguntas sobre estos términos, escribe a"],
      pt: ["Ir para os termos", "Termos", "Termos de Uso", "Última atualização: 11 de julho de 2026.", "Ao usar ASCII to Unicode, você concorda em utilizar o conversor com responsabilidade e verificar resultados importantes antes de confiar neles.", "Uso permitido", "Você pode usar a ferramenta para inspeção de texto, depuração, limpeza de conteúdo, revisão de localização, preparação de dados de teste e conversões relacionadas a ASCII ou Unicode.", "Sua responsabilidade", "Você é responsável pelo texto processado, pela saída copiada ou baixada e pelo cumprimento das regras do seu projeto, trabalho ou jurisdição.", "Verificação da saída", "O conversor é útil para inspeção e formatação, mas resultados importantes devem ser conferidos antes do uso em produção ou em contextos jurídicos, médicos, financeiros ou sensíveis à segurança.", "Sem garantia", "O site é fornecido no estado em que se encontra e pode mudar. Não garantimos disponibilidade contínua nem conversão perfeita para toda entrada corrompida.", "Contato", "Para dúvidas sobre estes termos, envie um e-mail para"],
      fr: ["Aller aux conditions", "Conditions", "Conditions d'utilisation", "Dernière mise à jour : 11 juillet 2026.", "En utilisant ASCII to Unicode, vous acceptez d'utiliser le convertisseur de manière responsable et de vérifier tout résultat important avant de vous y fier.", "Utilisation autorisée", "Vous pouvez utiliser l'outil pour inspecter du texte, déboguer, nettoyer du contenu, vérifier une localisation, préparer des données de test et effectuer des conversions ASCII ou Unicode associées.", "Votre responsabilité", "Vous êtes responsable du texte traité, de la sortie copiée ou téléchargée et du respect des règles applicables à votre projet, travail ou juridiction.", "Vérification des résultats", "Le convertisseur facilite l'inspection et le formatage, mais tout résultat important doit être vérifié avant usage en production ou dans un contexte juridique, médical, financier ou sensible à la sécurité.", "Absence de garantie", "Le site est fourni en l'état et peut évoluer. Nous ne garantissons ni une disponibilité continue ni une conversion parfaite de toutes les entrées corrompues.", "Contact", "Pour toute question sur ces conditions, écrivez à"],
      de: ["Zu den Nutzungsbedingungen springen", "Bedingungen", "Nutzungsbedingungen", "Zuletzt aktualisiert: 11. Juli 2026.", "Mit der Nutzung von ASCII to Unicode erklären Sie sich mit einer verantwortungsvollen Verwendung und der Prüfung wichtiger Ausgaben einverstanden.", "Zulässige Nutzung", "Sie dürfen das Tool zur Textprüfung, Fehlersuche, Inhaltsbereinigung, Lokalisierungsprüfung, Testdatenvorbereitung und für verwandte ASCII- oder Unicode-Konvertierungen nutzen.", "Ihre Verantwortung", "Sie sind für den verarbeiteten Text, kopierte oder heruntergeladene Ausgaben und die Einhaltung der für Projekt, Arbeitsplatz oder Rechtsgebiet geltenden Regeln verantwortlich.", "Ausgabeprüfung", "Der Konverter hilft bei Prüfung und Formatierung. Wichtige Ausgaben müssen vor dem Einsatz in Produktion sowie in rechtlichen, medizinischen, finanziellen oder sicherheitsrelevanten Bereichen geprüft werden.", "Keine Gewährleistung", "Die Website wird im vorhandenen Zustand bereitgestellt und kann sich ändern. Eine ununterbrochene Verfügbarkeit oder perfekte Konvertierung jeder fehlerhaften Eingabe wird nicht garantiert.", "Kontakt", "Bei Fragen zu diesen Bedingungen schreiben Sie an"],
      ja: ["利用規約へ移動", "利用規約", "利用規約", "最終更新日：2026年7月11日。", "ASCII to Unicode を利用することで、コンバーターを責任を持って使用し、重要な出力を信頼する前に確認することに同意したものとします。", "許可される用途", "テキスト確認、デバッグ、コンテンツ整理、ローカライズ確認、テストデータ作成、および関連する ASCII・Unicode 変換に使用できます。", "利用者の責任", "処理するテキスト、コピーまたはダウンロードする出力、およびプロジェクト、職場、地域に適用される規則の遵守は利用者の責任です。", "出力の確認", "コンバーターは確認と形式変換に役立ちますが、本番システム、法律文書、医療、金融、安全性に関わる用途では重要な出力を事前に確認してください。", "保証について", "サイトは現状のまま提供され、変更される場合があります。継続的な提供や、すべての不正な入力に対する完全な変換は保証しません。", "お問い合わせ", "利用規約に関するお問い合わせ先："],
      ko: ["이용약관으로 이동", "이용약관", "이용약관", "최종 업데이트: 2026년 7월 11일.", "ASCII to Unicode를 사용하면 변환기를 책임감 있게 사용하고 중요한 결과를 신뢰하기 전에 확인하는 데 동의하는 것입니다.", "허용되는 사용", "텍스트 검사, 디버깅, 콘텐츠 정리, 현지화 검토, 테스트 데이터 준비 및 관련 ASCII 또는 Unicode 변환에 도구를 사용할 수 있습니다.", "사용자의 책임", "처리하는 텍스트, 복사 또는 다운로드한 출력, 프로젝트나 직장 또는 관할 지역에 적용되는 규칙 준수는 사용자의 책임입니다.", "출력 확인", "변환기는 검사와 형식 지정에 유용하지만 프로덕션, 법률 문서, 의료, 금융 또는 보안에 민감한 환경에서는 중요한 결과를 사용 전에 확인해야 합니다.", "보증 없음", "사이트는 현재 상태로 제공되며 변경될 수 있습니다. 중단 없는 제공이나 모든 잘못된 입력에 대한 완벽한 변환을 보장하지 않습니다.", "문의", "이 약관에 관한 문의 이메일:" ]
    },
    contact: {
      zh: ["跳到联系页面", "联系", "联系 ASCII to Unicode", "如需反馈修正、功能建议、无障碍问题、隐私问题或转换器意见，请发送邮件至", "转换器反馈", "请说明转换模式、所选格式和期望输出。不要发送密码、私钥、客户数据或其他敏感文本。", "无障碍", "如果某个控件难以通过键盘、屏幕阅读器、移动设备或高对比度设置使用，请说明浏览器和设备，以便复现问题。", "隐私问题", "关于本地转换、localStorage、导入 TXT 文件或分析事件处理的问题，都可以发送到同一邮箱。", "格式建议", "如果你需要其他 ASCII-safe 或 Unicode 相关格式，请附上简短示例和希望得到的可读输出。"],
      es: ["Ir a contacto", "Contacto", "Contactar con ASCII to Unicode", "Para correcciones, solicitudes de funciones, problemas de accesibilidad, preguntas de privacidad o comentarios sobre el convertidor, escribe a", "Comentarios del convertidor", "Incluye el modo, el formato elegido y el resultado esperado. No envíes contraseñas, claves privadas, datos de clientes ni otro texto sensible.", "Accesibilidad", "Si un control es difícil de usar con teclado, lector de pantalla, móvil o alto contraste, indica el navegador y el dispositivo para poder reproducirlo.", "Preguntas de privacidad", "Las preguntas sobre conversión local, localStorage, archivos TXT importados o eventos de análisis pueden enviarse al mismo correo.", "Formatos sugeridos", "Si necesitas otro formato seguro para ASCII o relacionado con Unicode, incluye un ejemplo breve y la salida legible que esperas."],
      pt: ["Ir para contato", "Contato", "Contato ASCII to Unicode", "Para correções, solicitações de recursos, problemas de acessibilidade, dúvidas de privacidade ou comentários sobre o conversor, envie um e-mail para", "Feedback do conversor", "Informe o modo, o formato selecionado e a saída esperada. Não envie senhas, chaves privadas, dados de clientes ou outros textos sensíveis.", "Acessibilidade", "Se um controle for difícil de usar com teclado, leitor de tela, celular ou alto contraste, informe o navegador e o dispositivo para reproduzirmos o problema.", "Dúvidas de privacidade", "Perguntas sobre conversão local, localStorage, arquivos TXT importados ou eventos de análise podem ser enviadas para o mesmo e-mail.", "Formatos sugeridos", "Se precisar de outro formato seguro para ASCII ou relacionado a Unicode, inclua um exemplo curto e a saída legível desejada."],
      fr: ["Aller au contact", "Contact", "Contacter ASCII to Unicode", "Pour signaler une correction, demander une fonction, poser une question d'accessibilité ou de confidentialité ou commenter le convertisseur, écrivez à", "Retour sur le convertisseur", "Indiquez le mode, le format choisi et le résultat attendu. N'envoyez aucun mot de passe, clé privée, donnée client ou autre texte sensible.", "Accessibilité", "Si un contrôle est difficile à utiliser au clavier, avec un lecteur d'écran, sur mobile ou en contraste élevé, indiquez le navigateur et l'appareil pour reproduire le problème.", "Questions de confidentialité", "Les questions sur la conversion locale, localStorage, les fichiers TXT importés ou les événements statistiques peuvent être envoyées à la même adresse.", "Formats suggérés", "Si vous avez besoin d'un autre format compatible ASCII ou lié à Unicode, joignez un court exemple et la sortie lisible souhaitée."],
      de: ["Zum Kontakt springen", "Kontakt", "ASCII to Unicode kontaktieren", "Für Korrekturen, Funktionswünsche, Barrierefreiheitsprobleme, Datenschutzfragen oder Rückmeldungen zum Konverter schreiben Sie an", "Rückmeldung zum Konverter", "Nennen Sie Modus, gewähltes Format und erwartete Ausgabe. Senden Sie keine Passwörter, privaten Schlüssel, Kundendaten oder andere sensible Texte.", "Barrierefreiheit", "Wenn ein Steuerelement mit Tastatur, Screenreader, Mobilgerät oder hohem Kontrast schwer nutzbar ist, nennen Sie Browser und Gerät, damit das Problem reproduziert werden kann.", "Datenschutzfragen", "Fragen zu lokaler Konvertierung, localStorage, importierten TXT-Dateien oder Analyseereignissen können an dieselbe Adresse gesendet werden.", "Formatvorschläge", "Wenn Sie ein weiteres ASCII-sicheres oder Unicode-bezogenes Format benötigen, senden Sie ein kurzes Beispiel und die gewünschte lesbare Ausgabe."],
      ja: ["お問い合わせへ移動", "お問い合わせ", "ASCII to Unicode へのお問い合わせ", "修正、機能要望、アクセシビリティ、プライバシー、コンバーターへのご意見は次のメールアドレスへお送りください：", "コンバーターへのご意見", "変換モード、選択した形式、期待する出力を記載してください。パスワード、秘密鍵、顧客データなどの機密情報は送信しないでください。", "アクセシビリティ", "キーボード、スクリーンリーダー、モバイル端末、高コントラスト設定で操作しにくい場合は、再現できるようブラウザと端末をお知らせください。", "プライバシーに関する質問", "ローカル変換、localStorage、読み込んだ TXT ファイル、解析イベントに関する質問も同じメールアドレスへ送信できます。", "形式の提案", "別の ASCII セーフまたは Unicode 関連形式が必要な場合は、短い例と希望する読みやすい出力をお送りください。"],
      ko: ["문의로 이동", "문의", "ASCII to Unicode 문의", "수정, 기능 요청, 접근성 문제, 개인정보 질문 또는 변환기 피드백은 다음 이메일로 보내 주세요:", "변환기 피드백", "변환 모드, 선택한 형식 및 예상 출력을 포함하세요. 비밀번호, 개인 키, 고객 데이터 또는 기타 민감한 텍스트는 보내지 마세요.", "접근성", "키보드, 화면 읽기 프로그램, 모바일 기기 또는 고대비 설정에서 컨트롤을 사용하기 어렵다면 문제를 재현할 수 있도록 브라우저와 기기를 알려 주세요.", "개인정보 질문", "로컬 변환, localStorage, 가져온 TXT 파일 또는 분석 이벤트 처리에 관한 질문도 같은 이메일로 보낼 수 있습니다.", "형식 제안", "다른 ASCII 안전 또는 Unicode 관련 형식이 필요하면 짧은 예시와 원하는 읽기 쉬운 출력을 포함하세요." ]
    },
    notFound: {
      zh: ["跳到正文", "找不到页面", "你打开的页面不可用。首页的转换器仍可正常使用，你可以返回继续解码或编码 Unicode 文本。", "打开 ASCII to Unicode 转换器", "返回首页"],
      es: ["Ir al contenido", "Página no encontrada", "La página que abriste no está disponible. El convertidor sigue listo en la página de inicio para que continúes decodificando o codificando texto Unicode.", "Abrir el convertidor ASCII to Unicode", "Volver al inicio"],
      pt: ["Ir para o conteúdo", "Página não encontrada", "A página aberta não está disponível. O conversor continua pronto na página inicial para você decodificar ou codificar texto Unicode.", "Abrir o conversor ASCII to Unicode", "Voltar ao início"],
      fr: ["Aller au contenu", "Page introuvable", "La page ouverte n'est pas disponible. Le convertisseur reste accessible sur l'accueil pour continuer à décoder ou encoder du texte Unicode.", "Ouvrir le convertisseur ASCII to Unicode", "Retour à l'accueil"],
      de: ["Zum Inhalt springen", "Seite nicht gefunden", "Die geöffnete Seite ist nicht verfügbar. Der Konverter auf der Startseite ist weiterhin bereit, um Unicode-Text zu dekodieren oder zu kodieren.", "ASCII to Unicode Konverter öffnen", "Zur Startseite"],
      ja: ["本文へ移動", "ページが見つかりません", "開いたページは利用できません。ホームページのコンバーターは引き続き利用でき、Unicode テキストのデコードやエンコードを続けられます。", "ASCII to Unicode コンバーターを開く", "ホームへ戻る"],
      ko: ["본문으로 이동", "페이지를 찾을 수 없음", "연 페이지를 사용할 수 없습니다. 홈페이지의 변환기는 계속 사용할 수 있으므로 Unicode 텍스트 디코딩이나 인코딩을 이어갈 수 있습니다.", "ASCII to Unicode 변환기 열기", "홈페이지로 돌아가기"]
    }
  };

  const pages = Object.fromEntries(Object.entries(pageValues).map(([page, locales]) => [
    page,
    Object.fromEntries(Object.entries(locales).map(([lang, values]) => [lang, zip(pageKeys[page], values)]))
  ]));
  const analyticsPrivacyCopy = {
    zh: ["最后更新：2026年7月12日。", "我们使用 Google Analytics 4 衡量页面浏览、互动时间、滚动、出站点击，以及转换、模式切换、尝试示例、复制、下载、导入和语言切换等操作。转换器不会把你的输入、输出或导入的 TXT 内容发送给 Google Analytics。"],
    es: ["Última actualización: 12 de julio de 2026.", "Usamos Google Analytics 4 para medir páginas vistas, tiempo de interacción, desplazamientos, clics salientes y acciones como convertir, cambiar de modo, probar ejemplos, copiar, descargar, importar y cambiar de idioma. El convertidor no envía a Google Analytics la entrada, la salida ni el contenido TXT importado."],
    pt: ["Última atualização: 12 de julho de 2026.", "Usamos o Google Analytics 4 para medir visualizações de página, tempo de engajamento, rolagens, cliques de saída e ações como converter, mudar o modo, testar exemplos, copiar, baixar, importar e trocar o idioma. O conversor não envia entrada, saída ou conteúdo TXT importado ao Google Analytics."],
    fr: ["Dernière mise à jour : 12 juillet 2026.", "Nous utilisons Google Analytics 4 pour mesurer les pages vues, le temps d'engagement, le défilement, les clics sortants et des actions comme convertir, changer de mode, essayer un exemple, copier, télécharger, importer et changer de langue. Le convertisseur n'envoie ni l'entrée, ni la sortie, ni le contenu TXT importé à Google Analytics."],
    de: ["Zuletzt aktualisiert: 12. Juli 2026.", "Wir verwenden Google Analytics 4, um Seitenaufrufe, Interaktionszeit, Scrollvorgänge, ausgehende Klicks und Aktionen wie Konvertieren, Moduswechsel, Beispielaufruf, Kopieren, Herunterladen, Importieren und Sprachwechsel zu messen. Der Konverter sendet keine Eingabe, Ausgabe oder importierten TXT-Inhalte an Google Analytics."],
    ja: ["最終更新日：2026年7月12日。", "Google Analytics 4 を使用して、ページビュー、エンゲージメント時間、スクロール、外部リンクのクリック、変換、モード変更、例の利用、コピー、ダウンロード、読み込み、言語変更などの操作を測定します。入力、出力、読み込んだ TXT の内容は Google Analytics に送信しません。"],
    ko: ["최종 업데이트: 2026년 7월 12일.", "Google Analytics 4를 사용하여 페이지 조회, 참여 시간, 스크롤, 외부 링크 클릭과 변환, 모드 변경, 예시 사용, 복사, 다운로드, 가져오기, 언어 전환 같은 동작을 측정합니다. 변환기는 입력, 출력 또는 가져온 TXT 내용을 Google Analytics로 보내지 않습니다."]
  };
  Object.entries(analyticsPrivacyCopy).forEach(([lang, values]) => {
    pages.privacy[lang].lastUpdated = values[0];
    pages.privacy[lang].analyticsText = values[1];
  });

  const meta = {
    home: {
      zh: { title: "ASCII to Unicode 转换器 - 在线解码与编码", description: "在线转换 ASCII to Unicode。解码 Unicode 转义、HTML 实体、U+ 代码、十六进制字节和乱码，或将文本编码为 Unicode 格式。" },
      es: { title: "Convertidor ASCII to Unicode - Decodificar y codificar", description: "Convierte ASCII to Unicode en línea. Decodifica escapes Unicode, entidades HTML, códigos U+, bytes hexadecimales y mojibake, o codifica texto." },
      pt: { title: "Conversor ASCII to Unicode - Decodificar e codificar", description: "Converta ASCII to Unicode online. Decodifique escapes Unicode, entidades HTML, códigos U+, bytes hexadecimais e mojibake, ou codifique texto." },
      fr: { title: "Convertisseur ASCII to Unicode - Décoder et encoder", description: "Convertissez ASCII to Unicode en ligne. Décodez les séquences Unicode, entités HTML, codes U+, octets hexadécimaux et le mojibake, ou encodez du texte." },
      de: { title: "ASCII to Unicode Konverter - Online dekodieren", description: "ASCII to Unicode online umwandeln. Unicode-Escapes, HTML-Entitäten, U+-Codes, Hex-Bytes und Mojibake dekodieren oder Text kodieren." },
      ja: { title: "ASCII to Unicode コンバーター - オンライン変換", description: "ASCII to Unicode をオンライン変換。Unicode エスケープ、HTML エンティティ、U+ コード、16進バイト、文字化けのデコードとテキストのエンコードに対応。" },
      ko: { title: "ASCII to Unicode 변환기 - 온라인 디코딩 및 인코딩", description: "ASCII to Unicode를 온라인으로 변환하세요. Unicode 이스케이프, HTML 엔터티, U+ 코드, 16진수 바이트, 모지바케 디코딩과 텍스트 인코딩을 지원합니다." }
    },
    privacy: {
      zh: { title: "隐私政策 - ASCII to Unicode", description: "了解 ASCII to Unicode 如何在浏览器本地处理转换、TXT 导入、语言偏好和分析事件。" },
      es: { title: "Política de privacidad - ASCII to Unicode", description: "Conoce cómo ASCII to Unicode gestiona la conversión local, archivos TXT, preferencias de idioma y eventos de análisis." },
      pt: { title: "Política de Privacidade - ASCII to Unicode", description: "Saiba como ASCII to Unicode trata conversão local, arquivos TXT, idioma e eventos de análise." },
      fr: { title: "Politique de confidentialité - ASCII to Unicode", description: "Découvrez comment ASCII to Unicode gère la conversion locale, les fichiers TXT, la langue et les événements statistiques." },
      de: { title: "Datenschutzerklärung - ASCII to Unicode", description: "Erfahren Sie, wie ASCII to Unicode lokale Konvertierung, TXT-Dateien, Spracheinstellungen und Analyseereignisse behandelt." },
      ja: { title: "プライバシーポリシー - ASCII to Unicode", description: "ASCII to Unicode のローカル変換、TXT ファイル、言語設定、解析イベントの取り扱いについて説明します。" },
      ko: { title: "개인정보 처리방침 - ASCII to Unicode", description: "ASCII to Unicode의 로컬 변환, TXT 파일, 언어 설정 및 분석 이벤트 처리 방식을 확인하세요." }
    },
    terms: {
      zh: { title: "使用条款 - ASCII to Unicode", description: "ASCII to Unicode 使用条款，包括允许用途、用户责任、输出核验和服务担保说明。" },
      es: { title: "Términos de uso - ASCII to Unicode", description: "Términos de ASCII to Unicode sobre uso permitido, responsabilidad del usuario, verificación de resultados y garantías." },
      pt: { title: "Termos de Uso - ASCII to Unicode", description: "Termos de ASCII to Unicode sobre uso permitido, responsabilidade, verificação da saída e garantias." },
      fr: { title: "Conditions d'utilisation - ASCII to Unicode", description: "Conditions de ASCII to Unicode concernant l'usage autorisé, la responsabilité, la vérification et les garanties." },
      de: { title: "Nutzungsbedingungen - ASCII to Unicode", description: "Bedingungen für ASCII to Unicode zu zulässiger Nutzung, Verantwortung, Ausgabeprüfung und Gewährleistung." },
      ja: { title: "利用規約 - ASCII to Unicode", description: "ASCII to Unicode の許可される用途、利用者の責任、出力確認、保証に関する利用規約です。" },
      ko: { title: "이용약관 - ASCII to Unicode", description: "ASCII to Unicode의 허용 사용, 사용자 책임, 출력 확인 및 보증에 관한 이용약관입니다." }
    },
    contact: {
      zh: { title: "联系 - ASCII to Unicode", description: "联系 ASCII to Unicode，反馈修正、功能建议、无障碍问题、隐私问题或转换器意见。" },
      es: { title: "Contacto - ASCII to Unicode", description: "Contacta con ASCII to Unicode para correcciones, funciones, accesibilidad, privacidad o comentarios del convertidor." },
      pt: { title: "Contato - ASCII to Unicode", description: "Entre em contato com ASCII to Unicode para correções, recursos, acessibilidade, privacidade ou feedback." },
      fr: { title: "Contact - ASCII to Unicode", description: "Contactez ASCII to Unicode pour une correction, une fonction, l'accessibilité, la confidentialité ou un retour." },
      de: { title: "Kontakt - ASCII to Unicode", description: "Kontaktieren Sie ASCII to Unicode für Korrekturen, Funktionen, Barrierefreiheit, Datenschutz oder Rückmeldungen." },
      ja: { title: "お問い合わせ - ASCII to Unicode", description: "修正、機能要望、アクセシビリティ、プライバシー、変換に関するご意見は ASCII to Unicode へお問い合わせください。" },
      ko: { title: "문의 - ASCII to Unicode", description: "수정, 기능 요청, 접근성, 개인정보 또는 변환기 피드백은 ASCII to Unicode에 문의하세요." }
    },
    notFound: {
      zh: { title: "找不到页面 - ASCII to Unicode", description: "找不到你打开的页面。返回 ASCII to Unicode 转换器继续在线转换文本。" },
      es: { title: "Página no encontrada - ASCII to Unicode", description: "La página no está disponible. Vuelve al convertidor ASCII to Unicode para continuar en línea." },
      pt: { title: "Página não encontrada - ASCII to Unicode", description: "A página não está disponível. Volte ao conversor ASCII to Unicode para continuar online." },
      fr: { title: "Page introuvable - ASCII to Unicode", description: "Cette page n'est pas disponible. Revenez au convertisseur ASCII to Unicode pour continuer en ligne." },
      de: { title: "Seite nicht gefunden - ASCII to Unicode", description: "Diese Seite ist nicht verfügbar. Kehren Sie zum ASCII to Unicode Konverter zurück." },
      ja: { title: "ページが見つかりません - ASCII to Unicode", description: "ページが見つかりません。ASCII to Unicode コンバーターへ戻ってオンライン変換を続けられます。" },
      ko: { title: "페이지를 찾을 수 없음 - ASCII to Unicode", description: "페이지를 찾을 수 없습니다. ASCII to Unicode 변환기로 돌아가 온라인 변환을 계속하세요." }
    }
  };

  window.asciiUnicodeI18n = { languages, home, common, pages, meta };
})();
