(function () {
  "use strict";

  const config = window.asciiUnicodeI18n;
  if (!config) return;

  const fallback = {
    topLabel: "TOP", topAriaLabel: "Back to top", skip: "Skip to converter", navHow: "How it works", navCode: "Code", navBoundary: "7-bit vs 8-bit", languageLabel: "Choose language", languageMenuLabel: "Language", breadcrumbLabel: "Breadcrumb", breadcrumbHome: "ASCII to Unicode", breadcrumbCurrent: "Binary to ASCII Converter",
    heroEyebrow: "Free browser-based binary decoder", heroTitle: "Binary to ASCII Converter", heroLede: "Turn 7-bit or 8-bit binary groups into readable ASCII text. Use UTF-8 mode when the binary represents multilingual text, symbols, or emoji.", proofLabel: "Converter highlights", proofNoSignup: "No signup", proofFree: "Free online conversion",
    toolKicker: "Interactive tool", toolTitle: "Decode binary code into text", statusReady: "Ready", formatLabel: "Text encoding", formatAscii: "Standard ASCII", formatUtf8: "UTF-8 text", formatHelp: "ASCII accepts separated 7-bit or 8-bit groups and compact streams. UTF-8 requires complete 8-bit bytes. Spaces, commas, line breaks, colons, hyphens, and 0b prefixes are accepted.", inputLabel: "Binary input", inputPlaceholder: "01001000 01100101 01101100 01101100 01101111", inputHelp: "Paste compact or separated binary groups containing only 0 and 1.", outputLabel: "Text output", outputPlaceholder: "Hello", examplesLabel: "Try examples",
    warningInvalidBinary: "Use binary digits only. Spaces, commas, line breaks, colons, hyphens, and 0b prefixes are supported.", warningIncompleteBinary: "Use complete 7-bit or 8-bit groups for ASCII, or complete 8-bit bytes for UTF-8.", warningInvalidUtf8Binary: "The binary bytes are not valid UTF-8 throughout. Replacement characters mark invalid sequences.", warningNonAsciiBinary: "Values above 127 are not standard ASCII and are shown as ?. Choose UTF-8 when the bytes encode multilingual text.",
    howEyebrow: "Conversion guide", howTitle: "How Binary to ASCII Conversion Works", howP1: "Each ASCII character has a number from <code>0</code> to <code>127</code>. Read each binary group as a base-2 number, then map that number to the ASCII table. Binary <code>01001000</code> is decimal <code>72</code>, which represents <code>H</code>.", howP2: "The input <code>01001000 01101001</code> therefore becomes <code>Hi</code>. Standard ASCII is a 7-bit code, but it is commonly stored as an 8-bit byte with a leading zero. This tool accepts both forms in ASCII mode.", thBinary: "Binary", thDecimal: "Decimal", thCharacter: "ASCII character", spaceCharacter: "Space",
    codeTitle: "Binary to ASCII in JavaScript", codeP1: "For separated ASCII groups, validate seven or eight binary digits, convert each group with <code>parseInt(bits, 2)</code>, reject values above <code>127</code>, and build the text with <code>String.fromCharCode</code>.", pythonTitle: "Binary to ASCII in Python", pythonP1: "Python can convert each group with <code>int(bits, 2)</code>. For UTF-8, collect complete 8-bit values in a <code>bytes</code> object and call <code>decode(\"utf-8\")</code> so multibyte sequences are handled together.",
    boundaryTitle: "7-bit ASCII, 8-bit Bytes, and UTF-8", boundaryP1: "Standard ASCII defines <code>128</code> values, so seven bits are enough. In byte-oriented systems, ASCII normally uses eight bits with the high bit set to zero: <code>1000001</code> and <code>01000001</code> both represent <code>A</code>.", boundaryP2: "An 8-bit value from <code>10000000</code> through <code>11111111</code> is not standard ASCII by itself. It may be part of UTF-8 or a legacy encoding. Choose <strong>UTF-8 text</strong> only when every input group is a full 8-bit byte from a UTF-8 byte stream.", boundaryNoteTitle: "Binary digits do not identify the text encoding.", boundaryNoteText: "The byte boundaries and source encoding must be known before values above 127 can be decoded correctly.",
    invalidTitle: "Invalid Binary and Incomplete Groups", invalidP1: "Binary input may contain only <code>0</code> and <code>1</code> after optional <code>0b</code> prefixes. ASCII groups must contain seven or eight bits; UTF-8 groups must contain exactly eight. A compact stream must divide evenly into the selected group width.", invalidP2: "The converter rejects incomplete groups instead of padding or dropping bits. In ASCII mode, values above <code>127</code> appear as <code>?</code> with a warning. In UTF-8 mode, malformed byte sequences use <code>�</code> and trigger a separate warning.",
    relatedEyebrow: "Related converters", relatedTitle: "Continue Converting ASCII and Unicode", relatedText: "Use the reverse binary converter, decode hexadecimal bytes, or work with Unicode representations.", relatedHomeTitle: "ASCII to Unicode Converter", relatedHomeText: "Decode ASCII-safe escapes and Unicode representations.", relatedReverseTitle: "ASCII to Binary Converter", relatedReverseText: "Convert ASCII or UTF-8 text into binary bytes.", relatedHexTitle: "Hex to ASCII Converter", relatedHexText: "Decode hexadecimal bytes as ASCII or UTF-8 text.", relatedUnicodeTitle: "Unicode to ASCII Converter", relatedUnicodeText: "Escape, transliterate, replace, or remove non-ASCII characters.", footerText: "A focused browser utility for inspecting and converting text representations."
  };

  const makePage = (translations) => Object.assign({}, fallback, translations);
  const page = {
    zh: makePage({
      topLabel: "顶部", topAriaLabel: "返回顶部", skip: "跳到转换器", navHow: "转换原理", navCode: "代码", navBoundary: "7 位与 8 位", languageLabel: "选择语言", languageMenuLabel: "语言", breadcrumbLabel: "面包屑导航", breadcrumbHome: "ASCII to Unicode", breadcrumbCurrent: "Binary to ASCII 转换器",
      heroEyebrow: "免费的浏览器二进制解码工具", heroTitle: "Binary to ASCII 转换器", heroLede: "将 7 位或 8 位二进制组转换为可读 ASCII 文本。二进制表示多语言文本、符号或 emoji 时请选择 UTF-8。", proofLabel: "转换器特点", proofNoSignup: "无需注册", proofFree: "在线免费转换",
      toolKicker: "交互工具", toolTitle: "将二进制代码解码为文本", statusReady: "就绪", formatLabel: "文本编码", formatAscii: "标准 ASCII", formatUtf8: "UTF-8 文本", formatHelp: "ASCII 支持带分隔符的 7/8 位组和连续位流；UTF-8 必须使用完整 8 位字节。支持空格、逗号、换行、冒号、连字符和 0b 前缀。", inputLabel: "二进制输入", inputHelp: "粘贴只包含 0 和 1 的连续或带分隔符二进制组。", outputLabel: "文本输出", examplesLabel: "尝试示例",
      warningInvalidBinary: "只能使用二进制数字。支持空格、逗号、换行、冒号、连字符和 0b 前缀。", warningIncompleteBinary: "ASCII 请使用完整 7 位或 8 位组；UTF-8 请使用完整 8 位字节。", warningInvalidUtf8Binary: "这些二进制字节不是完整有效的 UTF-8，替换字符标出了无效序列。", warningNonAsciiBinary: "高于 127 的值不属于标准 ASCII，已显示为 ?。字节表示多语言文本时请选择 UTF-8。",
      howEyebrow: "转换指南", howTitle: "Binary to ASCII 转换原理", howP1: "每个 ASCII 字符都有一个 <code>0</code> 到 <code>127</code> 的数值。把每个二进制组按二进制解析，再到 ASCII 表中查找字符。<code>01001000</code> 是十进制 <code>72</code>，代表 <code>H</code>。", howP2: "因此 <code>01001000 01101001</code> 会得到 <code>Hi</code>。标准 ASCII 是 7 位编码，但通常用最高位为 0 的 8 位字节保存；ASCII 模式支持这两种形式。", thBinary: "二进制", thDecimal: "十进制", thCharacter: "ASCII 字符", spaceCharacter: "空格",
      codeTitle: "JavaScript 中的 Binary to ASCII", codeP1: "对分组 ASCII 输入，先验证每组是否为 7 或 8 位，再用 <code>parseInt(bits, 2)</code> 转换，拒绝高于 <code>127</code> 的值，并用 <code>String.fromCharCode</code> 组成文本。", pythonTitle: "Python 中的 Binary to ASCII", pythonP1: "Python 可用 <code>int(bits, 2)</code> 转换每组。处理 UTF-8 时，把完整 8 位值放入 <code>bytes</code>，再调用 <code>decode(\"utf-8\")</code>，让多字节序列整体解码。",
      boundaryTitle: "7 位 ASCII、8 位字节与 UTF-8", boundaryP1: "标准 ASCII 定义 <code>128</code> 个值，因此 7 位足够。在按字节存储的系统中，ASCII 通常补成最高位为 0 的 8 位：<code>1000001</code> 和 <code>01000001</code> 都代表 <code>A</code>。", boundaryP2: "从 <code>10000000</code> 到 <code>11111111</code> 的 8 位值本身不是标准 ASCII，可能属于 UTF-8 或旧式编码。只有当每组都是 UTF-8 字节流中的完整 8 位字节时，才选择 <strong>UTF-8 文本</strong>。", boundaryNoteTitle: "二进制数字本身不能说明文本编码。", boundaryNoteText: "要正确解码高于 127 的值，必须知道字节边界和来源编码。",
      invalidTitle: "无效二进制与不完整分组", invalidP1: "去掉可选的 <code>0b</code> 前缀后，输入只能包含 <code>0</code> 和 <code>1</code>。ASCII 每组必须为 7 或 8 位，UTF-8 每组必须恰好 8 位；连续位流必须能按所选宽度整除。", invalidP2: "转换器会拒绝不完整分组，不会自动补位或丢位。ASCII 模式把高于 <code>127</code> 的值显示为 <code>?</code> 并提示；UTF-8 模式用 <code>�</code> 标出无效字节序列。",
      relatedEyebrow: "相关转换器", relatedTitle: "继续转换 ASCII 和 Unicode", relatedText: "使用反向二进制转换器、解码十六进制字节，或处理 Unicode 表示。", relatedHomeTitle: "ASCII to Unicode 转换器", relatedHomeText: "解码 ASCII-safe 转义和 Unicode 表示。", relatedReverseTitle: "ASCII to Binary 转换器", relatedReverseText: "将 ASCII 或 UTF-8 文本编码为二进制字节。", relatedHexTitle: "Hex to ASCII 转换器", relatedHexText: "将十六进制字节解码为 ASCII 或 UTF-8 文本。", relatedUnicodeTitle: "Unicode to ASCII 转换器", relatedUnicodeText: "转义、转写、替换或删除非 ASCII 字符。", footerText: "用于检查和转换文本表示的专注型浏览器工具。"
    }),
    es: makePage({
      topLabel: "ARRIBA", topAriaLabel: "Volver arriba", skip: "Ir al convertidor", navHow: "Cómo funciona", navCode: "Código", navBoundary: "7 bits y 8 bits", languageLabel: "Elegir idioma", languageMenuLabel: "Idioma", breadcrumbLabel: "Ruta de navegación", breadcrumbCurrent: "Convertidor Binary to ASCII", heroEyebrow: "Decodificador binario gratuito en el navegador", heroTitle: "Convertidor Binary to ASCII", heroLede: "Convierte grupos binarios de 7 u 8 bits en texto ASCII legible. Usa UTF-8 para texto multilingüe, símbolos o emoji.", proofLabel: "Ventajas del convertidor", toolTitle: "Decodificar código binario como texto", formatLabel: "Codificación de texto", formatAscii: "ASCII estándar", formatUtf8: "Texto UTF-8", formatHelp: "ASCII admite grupos de 7 u 8 bits y secuencias compactas; UTF-8 exige bytes completos de 8 bits. Se aceptan separadores y prefijos 0b.", inputLabel: "Entrada binaria", inputHelp: "Pega grupos binarios compactos o separados que solo contengan 0 y 1.", outputLabel: "Salida de texto", examplesLabel: "Probar ejemplos", warningInvalidBinary: "Usa solo dígitos binarios. Se admiten separadores y prefijos 0b.", warningIncompleteBinary: "Usa grupos completos de 7 u 8 bits para ASCII y bytes de 8 bits para UTF-8.", warningInvalidUtf8Binary: "Los bytes no forman UTF-8 válido por completo.", warningNonAsciiBinary: "Los valores mayores que 127 no son ASCII estándar y aparecen como ?. Elige UTF-8 para texto multilingüe.", howTitle: "Cómo funciona la conversión Binary to ASCII", thBinary: "Binario", thDecimal: "Decimal", thCharacter: "Carácter ASCII", spaceCharacter: "Espacio", codeTitle: "Binary to ASCII en JavaScript", pythonTitle: "Binary to ASCII en Python", boundaryTitle: "ASCII de 7 bits, bytes de 8 bits y UTF-8", boundaryNoteTitle: "Los bits no identifican la codificación del texto.", invalidTitle: "Binario inválido y grupos incompletos", relatedEyebrow: "Convertidores relacionados", relatedTitle: "Seguir convirtiendo ASCII y Unicode", relatedReverseTitle: "Convertidor ASCII to Binary", relatedHexTitle: "Convertidor Hex to ASCII", relatedUnicodeTitle: "Convertidor Unicode to ASCII"
    }),
    pt: makePage({
      topLabel: "TOPO", topAriaLabel: "Voltar ao topo", skip: "Ir ao conversor", navHow: "Como funciona", navCode: "Código", navBoundary: "7 bits e 8 bits", languageLabel: "Escolher idioma", languageMenuLabel: "Idioma", breadcrumbLabel: "Navegação estrutural", breadcrumbCurrent: "Conversor Binary to ASCII", heroEyebrow: "Decodificador binário gratuito no navegador", heroTitle: "Conversor Binary to ASCII", heroLede: "Converta grupos binários de 7 ou 8 bits em texto ASCII legível. Use UTF-8 para texto multilíngue, símbolos ou emoji.", proofLabel: "Destaques do conversor", toolTitle: "Decodificar código binário em texto", formatLabel: "Codificação de texto", formatAscii: "ASCII padrão", formatUtf8: "Texto UTF-8", formatHelp: "ASCII aceita grupos de 7 ou 8 bits e fluxos compactos; UTF-8 exige bytes completos de 8 bits. Separadores e prefixos 0b são aceitos.", inputLabel: "Entrada binária", inputHelp: "Cole grupos binários compactos ou separados contendo apenas 0 e 1.", outputLabel: "Saída de texto", examplesLabel: "Testar exemplos", warningInvalidBinary: "Use apenas dígitos binários. Separadores e prefixos 0b são aceitos.", warningIncompleteBinary: "Use grupos completos de 7 ou 8 bits para ASCII e bytes de 8 bits para UTF-8.", warningInvalidUtf8Binary: "Os bytes não formam UTF-8 totalmente válido.", warningNonAsciiBinary: "Valores acima de 127 não são ASCII padrão e aparecem como ?. Escolha UTF-8 para texto multilíngue.", howTitle: "Como funciona a conversão Binary to ASCII", thBinary: "Binário", thDecimal: "Decimal", thCharacter: "Caractere ASCII", spaceCharacter: "Espaço", codeTitle: "Binary to ASCII em JavaScript", pythonTitle: "Binary to ASCII em Python", boundaryTitle: "ASCII de 7 bits, bytes de 8 bits e UTF-8", boundaryNoteTitle: "Os bits não identificam a codificação do texto.", invalidTitle: "Binário inválido e grupos incompletos", relatedEyebrow: "Conversores relacionados", relatedTitle: "Continuar convertendo ASCII e Unicode", relatedReverseTitle: "Conversor ASCII to Binary", relatedHexTitle: "Conversor Hex to ASCII", relatedUnicodeTitle: "Conversor Unicode to ASCII"
    }),
    fr: makePage({
      topLabel: "HAUT", topAriaLabel: "Retour en haut", skip: "Aller au convertisseur", navHow: "Fonctionnement", navCode: "Code", navBoundary: "7 bits et 8 bits", languageLabel: "Choisir la langue", languageMenuLabel: "Langue", breadcrumbLabel: "Fil d'Ariane", breadcrumbCurrent: "Convertisseur Binary to ASCII", heroEyebrow: "Décodeur binaire gratuit dans le navigateur", heroTitle: "Convertisseur Binary to ASCII", heroLede: "Transformez des groupes binaires de 7 ou 8 bits en texte ASCII lisible. Utilisez UTF-8 pour le texte multilingue, les symboles ou les emoji.", proofLabel: "Avantages du convertisseur", toolTitle: "Décoder du binaire en texte", formatLabel: "Encodage du texte", formatAscii: "ASCII standard", formatUtf8: "Texte UTF-8", formatHelp: "ASCII accepte les groupes de 7 ou 8 bits et les flux compacts ; UTF-8 exige des octets complets. Les séparateurs et préfixes 0b sont acceptés.", inputLabel: "Entrée binaire", inputHelp: "Collez des groupes binaires compacts ou séparés contenant uniquement 0 et 1.", outputLabel: "Sortie texte", examplesLabel: "Essayer des exemples", warningInvalidBinary: "Utilisez uniquement des chiffres binaires. Les séparateurs et préfixes 0b sont acceptés.", warningIncompleteBinary: "Utilisez des groupes complets de 7 ou 8 bits pour ASCII et de 8 bits pour UTF-8.", warningInvalidUtf8Binary: "Les octets ne forment pas un UTF-8 entièrement valide.", warningNonAsciiBinary: "Les valeurs supérieures à 127 ne sont pas ASCII standard et sont affichées par ?. Choisissez UTF-8 pour le texte multilingue.", howTitle: "Fonctionnement de la conversion Binary to ASCII", thBinary: "Binaire", thDecimal: "Décimal", thCharacter: "Caractère ASCII", spaceCharacter: "Espace", codeTitle: "Binary to ASCII en JavaScript", pythonTitle: "Binary to ASCII en Python", boundaryTitle: "ASCII 7 bits, octets 8 bits et UTF-8", boundaryNoteTitle: "Les bits n'identifient pas l'encodage du texte.", invalidTitle: "Binaire invalide et groupes incomplets", relatedEyebrow: "Convertisseurs associés", relatedTitle: "Continuer à convertir ASCII et Unicode", relatedReverseTitle: "Convertisseur ASCII to Binary", relatedHexTitle: "Convertisseur Hex to ASCII", relatedUnicodeTitle: "Convertisseur Unicode to ASCII"
    }),
    de: makePage({
      topLabel: "OBEN", topAriaLabel: "Nach oben", skip: "Zum Konverter", navHow: "Funktionsweise", navCode: "Code", navBoundary: "7 Bit und 8 Bit", languageLabel: "Sprache auswählen", languageMenuLabel: "Sprache", breadcrumbLabel: "Brotkrümelnavigation", breadcrumbCurrent: "Binary to ASCII Konverter", heroEyebrow: "Kostenloser Binärdecoder im Browser", heroTitle: "Binary to ASCII Konverter", heroLede: "7- oder 8-Bit-Binärgruppen in lesbaren ASCII-Text umwandeln. Für mehrsprachigen Text, Symbole oder Emoji UTF-8 verwenden.", proofLabel: "Vorteile des Konverters", toolTitle: "Binärcode als Text decodieren", formatLabel: "Textcodierung", formatAscii: "Standard-ASCII", formatUtf8: "UTF-8-Text", formatHelp: "ASCII akzeptiert 7- oder 8-Bit-Gruppen und kompakte Folgen; UTF-8 erfordert vollständige 8-Bit-Bytes. Trennzeichen und 0b-Präfixe sind erlaubt.", inputLabel: "Binäreingabe", inputHelp: "Kompakte oder getrennte Binärgruppen nur aus 0 und 1 einfügen.", outputLabel: "Textausgabe", examplesLabel: "Beispiele", warningInvalidBinary: "Nur Binärziffern verwenden. Trennzeichen und 0b-Präfixe sind erlaubt.", warningIncompleteBinary: "Vollständige 7- oder 8-Bit-Gruppen für ASCII und 8-Bit-Bytes für UTF-8 verwenden.", warningInvalidUtf8Binary: "Die Bytes sind nicht vollständig gültiges UTF-8.", warningNonAsciiBinary: "Werte über 127 sind kein Standard-ASCII und erscheinen als ?. Für mehrsprachigen Text UTF-8 wählen.", howTitle: "So funktioniert die Binary to ASCII Umwandlung", thBinary: "Binär", thDecimal: "Dezimal", thCharacter: "ASCII-Zeichen", spaceCharacter: "Leerzeichen", codeTitle: "Binary to ASCII in JavaScript", pythonTitle: "Binary to ASCII in Python", boundaryTitle: "7-Bit-ASCII, 8-Bit-Bytes und UTF-8", boundaryNoteTitle: "Binärziffern bestimmen nicht die Textcodierung.", invalidTitle: "Ungültiges Binärformat und unvollständige Gruppen", relatedEyebrow: "Verwandte Konverter", relatedTitle: "ASCII und Unicode weiter umwandeln", relatedReverseTitle: "ASCII to Binary Konverter", relatedHexTitle: "Hex to ASCII Konverter", relatedUnicodeTitle: "Unicode to ASCII Konverter"
    }),
    ja: makePage({
      topLabel: "上へ", topAriaLabel: "ページ上部へ戻る", skip: "コンバーターへ移動", navHow: "変換方法", navCode: "コード", navBoundary: "7 ビットと 8 ビット", languageLabel: "言語を選択", languageMenuLabel: "言語", breadcrumbLabel: "パンくずリスト", breadcrumbCurrent: "Binary to ASCII コンバーター", heroEyebrow: "ブラウザで使える無料バイナリデコーダー", heroTitle: "Binary to ASCII コンバーター", heroLede: "7 ビットまたは 8 ビットのバイナリグループを読みやすい ASCII テキストに変換します。多言語テキスト、記号、絵文字には UTF-8 を使います。", proofLabel: "コンバーターの特徴", toolTitle: "バイナリコードをテキストにデコード", formatLabel: "テキストエンコーディング", formatAscii: "標準 ASCII", formatUtf8: "UTF-8 テキスト", formatHelp: "ASCII は 7/8 ビットグループと連続入力に対応し、UTF-8 は完全な 8 ビットバイトが必要です。区切りと 0b 接頭辞に対応します。", inputLabel: "バイナリ入力", inputHelp: "0 と 1 だけの連続または区切られたグループを貼り付けます。", outputLabel: "テキスト出力", examplesLabel: "例を試す", warningInvalidBinary: "バイナリ数字だけを使用してください。区切りと 0b 接頭辞に対応します。", warningIncompleteBinary: "ASCII は完全な 7/8 ビット、UTF-8 は完全な 8 ビットバイトを使用してください。", warningInvalidUtf8Binary: "バイト列の一部が有効な UTF-8 ではありません。", warningNonAsciiBinary: "127 を超える値は標準 ASCII ではないため ? で表示します。多言語テキストには UTF-8 を選びます。", howTitle: "Binary to ASCII 変換の仕組み", thBinary: "バイナリ", thDecimal: "10 進数", thCharacter: "ASCII 文字", spaceCharacter: "空白", codeTitle: "JavaScript で Binary to ASCII", pythonTitle: "Python で Binary to ASCII", boundaryTitle: "7 ビット ASCII、8 ビットバイト、UTF-8", boundaryNoteTitle: "バイナリ数字だけでは文字エンコーディングは決まりません。", invalidTitle: "無効なバイナリと不完全なグループ", relatedEyebrow: "関連コンバーター", relatedTitle: "ASCII と Unicode の変換を続ける", relatedReverseTitle: "ASCII to Binary コンバーター", relatedHexTitle: "Hex to ASCII コンバーター", relatedUnicodeTitle: "Unicode to ASCII コンバーター"
    }),
    ko: makePage({
      topLabel: "위로", topAriaLabel: "맨 위로", skip: "변환기로 이동", navHow: "변환 방식", navCode: "코드", navBoundary: "7비트와 8비트", languageLabel: "언어 선택", languageMenuLabel: "언어", breadcrumbLabel: "이동 경로", breadcrumbCurrent: "Binary to ASCII 변환기", heroEyebrow: "브라우저에서 실행되는 무료 이진 디코더", heroTitle: "Binary to ASCII 변환기", heroLede: "7비트 또는 8비트 이진 그룹을 읽을 수 있는 ASCII 텍스트로 변환합니다. 다국어 텍스트, 기호, 이모지는 UTF-8을 사용하세요.", proofLabel: "변환기 특징", toolTitle: "이진 코드를 텍스트로 디코딩", formatLabel: "텍스트 인코딩", formatAscii: "표준 ASCII", formatUtf8: "UTF-8 텍스트", formatHelp: "ASCII는 7/8비트 그룹과 연속 입력을 지원하며 UTF-8은 완전한 8비트 바이트가 필요합니다. 구분자와 0b 접두사를 지원합니다.", inputLabel: "이진 입력", inputHelp: "0과 1만 포함한 연속 또는 구분된 이진 그룹을 붙여 넣으세요.", outputLabel: "텍스트 출력", examplesLabel: "예시 실행", warningInvalidBinary: "이진 숫자만 사용하세요. 구분자와 0b 접두사를 지원합니다.", warningIncompleteBinary: "ASCII는 완전한 7/8비트 그룹, UTF-8은 완전한 8비트 바이트를 사용하세요.", warningInvalidUtf8Binary: "바이트 전체가 유효한 UTF-8이 아닙니다.", warningNonAsciiBinary: "127보다 큰 값은 표준 ASCII가 아니므로 ?로 표시합니다. 다국어 텍스트에는 UTF-8을 선택하세요.", howTitle: "Binary to ASCII 변환 방식", thBinary: "이진수", thDecimal: "10진수", thCharacter: "ASCII 문자", spaceCharacter: "공백", codeTitle: "JavaScript에서 Binary to ASCII", pythonTitle: "Python에서 Binary to ASCII", boundaryTitle: "7비트 ASCII, 8비트 바이트, UTF-8", boundaryNoteTitle: "이진 숫자만으로 텍스트 인코딩을 알 수 없습니다.", invalidTitle: "잘못된 이진수와 불완전한 그룹", relatedEyebrow: "관련 변환기", relatedTitle: "ASCII와 Unicode 변환 계속하기", relatedReverseTitle: "ASCII to Binary 변환기", relatedHexTitle: "Hex to ASCII 변환기", relatedUnicodeTitle: "Unicode to ASCII 변환기"
    })
  };

  config.pages.binaryToAscii = page;
  config.meta.binaryToAscii = {
    zh: { title: "Binary to ASCII 转换器 - 免费在线工具", description: "在线将 7 位或 8 位二进制代码转换为 ASCII 或 UTF-8 文本，支持连续输入、常用分隔符、0b 前缀和错误提示。" },
    es: { title: "Convertidor Binary to ASCII - Herramienta gratis", description: "Convierte código binario de 7 u 8 bits en texto ASCII o UTF-8 con entrada compacta, separadores, prefijos 0b y avisos claros." },
    pt: { title: "Conversor Binary to ASCII - Ferramenta gratuita", description: "Converta código binário de 7 ou 8 bits em texto ASCII ou UTF-8 com entrada compacta, separadores, prefixos 0b e avisos." },
    fr: { title: "Convertisseur Binary to ASCII - Outil gratuit", description: "Convertissez du binaire 7 ou 8 bits en texte ASCII ou UTF-8 avec saisie compacte, séparateurs, préfixes 0b et alertes." },
    de: { title: "Binary to ASCII Konverter - Kostenloses Tool", description: "7- oder 8-Bit-Binärcode in ASCII- oder UTF-8-Text umwandeln, mit kompakter Eingabe, Trennzeichen, 0b-Präfixen und Warnungen." },
    ja: { title: "Binary to ASCII コンバーター - 無料ツール", description: "7/8 ビットのバイナリコードを ASCII または UTF-8 テキストに変換。連続入力、区切り、0b 接頭辞、エラー警告に対応。" },
    ko: { title: "Binary to ASCII 변환기 - 무료 도구", description: "7비트 또는 8비트 이진 코드를 ASCII나 UTF-8 텍스트로 변환하세요. 연속 입력, 구분자, 0b 접두사와 오류 경고를 지원합니다." }
  };
})();
