(function () {
  "use strict";

  const config = window.asciiUnicodeI18n;
  if (!config) return;

  const page = {
    zh: {
      topLabel: "顶部", topAriaLabel: "返回顶部", skip: "跳到转换工具", navHow: "转换方法", navCode: "代码", navBoundary: "ASCII 与 UTF-8", languageLabel: "选择语言", languageMenuLabel: "语言", breadcrumbLabel: "面包屑导航", breadcrumbHome: "ASCII to Unicode", breadcrumbCurrent: "ASCII to Hex 转换器",
      heroEyebrow: "免费的浏览器十六进制转换工具", heroTitle: "ASCII to Hex 转换器", heroLede: "立即将 ASCII 文本转换为十六进制字节值。文本包含重音字母、非拉丁文字、符号或 emoji 时，请使用 UTF-8 字节模式。", proofLabel: "转换器特点", proofNoSignup: "无需注册", proofFree: "在线免费转换",
      toolKicker: "可交互工具", toolTitle: "将 ASCII 字符转换为十六进制", statusReady: "就绪", statusDone: "已转换", statusCopied: "已复制", statusCleared: "已清空", statusImported: "已导入", statusDownloaded: "已下载", modeAscii: "标准 ASCII", modeUtf8: "UTF-8 字节", formatLabel: "输出格式", formatSpace: "空格分隔", formatCompact: "连续 Hex", formatPrefix: "0x 前缀", formatEscape: "\\x 转义", autoConvert: "自动转换", formatHelp: "ASCII 模式为每个字符输出一个两位 Hex 字节，并标记不支持的字符，不会猜测编码。",
      inputLabel: "ASCII 输入", inputPlaceholder: "Hello", inputHelp: "输入 ASCII 文本；多语言文本请切换到 UTF-8 字节。", outputLabel: "Hex 输出", outputPlaceholder: "48 65 6C 6C 6F", charsLabel: "个字符", actionsLabel: "转换器操作", btnConvert: "转换", btnCopy: "复制", btnClear: "清空", btnSwap: "交换", btnImport: "导入 TXT", btnDownload: "下载结果", examplesLabel: "尝试示例", warningNonAsciiHexEncode: "非 ASCII 字符已标记为 ??。请使用 UTF-8 字节模式进行无歧义编码。",
      howEyebrow: "转换指南", howTitle: "如何将 ASCII 转为 Hex", howP1: "每个 ASCII 字符都有一个 <code>0</code> 到 <code>127</code> 的数值。把十进制值转换为十六进制并补齐两位即可。大写 <code>A</code> 是十进制 <code>65</code>，对应 Hex 字节 <code>41</code>。", howP2: "转换器会对每个字符重复这个过程，包括空格和控制字符。例如 <code>Hi</code> 变为 <code>48 69</code>。空格分隔便于检查字节边界，连续格式则写成 <code>4869</code>。", thCharacter: "字符", thDecimal: "ASCII 十进制", thHex: "Hex 字节", spaceCharacter: "空格",
      codeTitle: "JavaScript 中的 ASCII to Hex", codeP1: "JavaScript 可用 <code>charCodeAt</code> 读取字符值，拒绝高于 <code>127</code> 的值，再用 <code>toString(16)</code> 和 <code>padStart(2, \"0\")</code> 生成完整 Hex 字节。", pythonTitle: "Python 中的 ASCII to Hex", pythonP1: "Python 的 <code>ord</code> 返回字符数值，<code>format(value, \"02X\")</code> 输出大写两位 Hex。检查所有值小于 <code>128</code> 可确保结果严格属于 ASCII。",
      boundaryTitle: "ASCII Hex 与 UTF-8 Hex", boundaryP1: "标准 ASCII 覆盖 <code>00</code> 到 <code>7F</code>，每个字符对应一个 Hex 字节。ASCII 也是 UTF-8 的子集，所以英文字母、数字、标点和控制字符在两种模式中结果相同。", boundaryP2: "高于 <code>U+007F</code> 的字符不属于 ASCII。在 UTF-8 中它们可能占多个字节：<code>é</code> 是 <code>C3 A9</code>，<code>你</code> 是 <code>E4 BD A0</code>。多语言文本、符号和 emoji 应使用 UTF-8 字节。", boundaryNoteTitle: "一个 ASCII 字符对应一个两位 Hex 字节。", boundaryNoteText: "这条规则只对标准 ASCII 可靠。一个 Unicode 字符在 UTF-8 中可能占两到四个 Hex 字节。",
      utf8Title: "ASCII to Hex 输出格式", utf8P1: "<code>Hi</code> 可以写成空格 Hex <code>48 69</code>、连续 Hex <code>4869</code>、前缀格式 <code>0x48 0x69</code> 或字节转义 <code>\\x48\\x69</code>，底层字节值完全相同。", utf8P2: "检查时使用空格格式，存储或协议使用连续格式，编程上下文使用 0x 前缀，源码字符串和调试 fixture 使用字节转义。",
      relatedEyebrow: "相关转换器", relatedTitle: "继续转换 ASCII 和 Unicode", relatedText: "使用专用工具把结果解码回文本、比较二进制输出或生成 Unicode-safe 转义。", relatedHomeTitle: "ASCII to Unicode 转换器", relatedHomeText: "将 ASCII-safe 转义解码为可读 Unicode 文本。", relatedUnicodeTitle: "Unicode to ASCII 转换器", relatedUnicodeText: "转义、转写、替换或移除非 ASCII 字符。", relatedReverseTitle: "Hex to ASCII 转换器", relatedReverseText: "将十六进制字节解码回 ASCII 或 UTF-8 文本。", relatedBinaryTitle: "ASCII to Binary 转换器", relatedBinaryText: "将同一组 ASCII 字符转换为固定 8 位二进制。"
    },
    es: {
      topLabel: "ARRIBA", topAriaLabel: "Volver arriba", skip: "Ir al convertidor", navHow: "Cómo funciona", navCode: "Código", navBoundary: "ASCII y UTF-8", languageLabel: "Elegir idioma", languageMenuLabel: "Idioma", breadcrumbLabel: "Ruta de navegación", breadcrumbHome: "ASCII to Unicode", breadcrumbCurrent: "Convertidor ASCII to Hex",
      heroEyebrow: "Convertidor hexadecimal gratuito en el navegador", heroTitle: "Convertidor ASCII to Hex", heroLede: "Convierte texto ASCII en valores de bytes hexadecimales. Usa Bytes UTF-8 para acentos, escrituras no latinas, símbolos o emoji.", proofLabel: "Ventajas del convertidor", proofNoSignup: "Sin registro", proofFree: "Conversión gratuita en línea",
      toolKicker: "Herramienta interactiva", toolTitle: "Convertir caracteres ASCII a hexadecimal", statusReady: "Listo", statusDone: "Convertido", statusCopied: "Copiado", statusCleared: "Borrado", statusImported: "Importado", statusDownloaded: "Descargado", modeAscii: "ASCII estándar", modeUtf8: "Bytes UTF-8", formatLabel: "Formato de salida", formatSpace: "Separado por espacios", formatCompact: "Hex compacto", formatPrefix: "Prefijo 0x", formatEscape: "Escape \\x", autoConvert: "Conversión automática", formatHelp: "El modo ASCII genera un byte hex de dos dígitos por carácter y marca los no compatibles sin adivinar la codificación.",
      inputLabel: "Entrada ASCII", inputPlaceholder: "Hello", inputHelp: "Introduce texto ASCII o cambia a Bytes UTF-8 para texto multilingüe.", outputLabel: "Salida Hex", outputPlaceholder: "48 65 6C 6C 6F", charsLabel: "caracteres", actionsLabel: "Acciones del convertidor", btnConvert: "Convertir", btnCopy: "Copiar", btnClear: "Borrar", btnSwap: "Intercambiar", btnImport: "Importar TXT", btnDownload: "Descargar resultado", examplesLabel: "Probar ejemplos", warningNonAsciiHexEncode: "Los caracteres no ASCII se marcan como ??. Usa Bytes UTF-8 para codificarlos sin ambigüedad.",
      howEyebrow: "Guía de conversión", howTitle: "Cómo convertir ASCII a Hex", howP1: "Cada carácter ASCII tiene un valor de <code>0</code> a <code>127</code>. Convierte el valor decimal a base 16 y complétalo con dos dígitos. La <code>A</code> vale <code>65</code> y su byte Hex es <code>41</code>.", howP2: "El proceso se repite para cada carácter. <code>Hi</code> se convierte en <code>48 69</code>; sin espacios representa los mismos bytes como <code>4869</code>.", thCharacter: "Carácter", thDecimal: "ASCII decimal", thHex: "Byte Hex", spaceCharacter: "Espacio",
      codeTitle: "ASCII to Hex en JavaScript", codeP1: "Lee el valor con <code>charCodeAt</code>, rechaza valores superiores a <code>127</code> y usa <code>toString(16)</code> con <code>padStart(2, \"0\")</code>.", pythonTitle: "ASCII to Hex en Python", pythonP1: "<code>ord</code> devuelve el valor y <code>format(value, \"02X\")</code> escribe un byte Hex de dos dígitos. Valores menores de <code>128</code> mantienen ASCII estricto.",
      boundaryTitle: "Hex ASCII y Hex UTF-8", boundaryP1: "ASCII estándar cubre <code>00</code> a <code>7F</code>, un byte por carácter. Como ASCII es un subconjunto de UTF-8, letras inglesas, números y puntuación coinciden en ambos modos.", boundaryP2: "Los caracteres sobre <code>U+007F</code> no son ASCII. En UTF-8, <code>é</code> es <code>C3 A9</code> y <code>你</code> es <code>E4 BD A0</code>. Usa UTF-8 para texto multilingüe, símbolos y emoji.", boundaryNoteTitle: "Un carácter ASCII equivale a un byte Hex de dos dígitos.", boundaryNoteText: "En UTF-8, un carácter Unicode puede necesitar entre dos y cuatro bytes Hex.",
      utf8Title: "Formatos de salida ASCII to Hex", utf8P1: "<code>Hi</code> puede escribirse como <code>48 69</code>, <code>4869</code>, <code>0x48 0x69</code> o <code>\\x48\\x69</code>; los bytes no cambian.", utf8P2: "Usa espacios para inspección, formato compacto para protocolos, 0x en código y escapes para cadenas o datos de prueba.",
      relatedEyebrow: "Convertidores relacionados", relatedTitle: "Continuar convirtiendo ASCII y Unicode", relatedText: "Decodifica el resultado, compara binario o crea escapes Unicode con una herramienta específica.", relatedHomeTitle: "Convertidor ASCII to Unicode", relatedHomeText: "Decodifica escapes ASCII-safe como Unicode legible.", relatedUnicodeTitle: "Convertidor Unicode to ASCII", relatedUnicodeText: "Escapa, translitera, sustituye o elimina caracteres no ASCII.", relatedReverseTitle: "Convertidor Hex to ASCII", relatedReverseText: "Decodifica bytes hexadecimales a texto ASCII o UTF-8.", relatedBinaryTitle: "Convertidor ASCII to Binary", relatedBinaryText: "Convierte los mismos caracteres ASCII en grupos binarios de 8 bits."
    },
    pt: {
      topLabel: "TOPO", topAriaLabel: "Voltar ao topo", skip: "Ir para o conversor", navHow: "Como funciona", navCode: "Código", navBoundary: "ASCII e UTF-8", languageLabel: "Escolher idioma", languageMenuLabel: "Idioma", breadcrumbLabel: "Navegação estrutural", breadcrumbHome: "ASCII to Unicode", breadcrumbCurrent: "Conversor ASCII to Hex",
      heroEyebrow: "Conversor hexadecimal gratuito no navegador", heroTitle: "Conversor ASCII to Hex", heroLede: "Converta texto ASCII em bytes hexadecimais. Use Bytes UTF-8 para acentos, alfabetos não latinos, símbolos ou emoji.", proofLabel: "Destaques", proofNoSignup: "Sem cadastro", proofFree: "Conversão online gratuita",
      toolKicker: "Ferramenta interativa", toolTitle: "Converter caracteres ASCII em hexadecimal", statusReady: "Pronto", statusDone: "Convertido", statusCopied: "Copiado", statusCleared: "Limpo", statusImported: "Importado", statusDownloaded: "Baixado", modeAscii: "ASCII padrão", modeUtf8: "Bytes UTF-8", formatLabel: "Formato de saída", formatSpace: "Separado por espaços", formatCompact: "Hex compacto", formatPrefix: "Prefixo 0x", formatEscape: "Escape \\x", autoConvert: "Conversão automática", formatHelp: "O modo ASCII gera um byte Hex de dois dígitos por caractere e marca caracteres não suportados sem adivinhar a codificação.",
      inputLabel: "Entrada ASCII", inputPlaceholder: "Hello", inputHelp: "Digite texto ASCII ou use Bytes UTF-8 para texto multilíngue.", outputLabel: "Saída Hex", outputPlaceholder: "48 65 6C 6C 6F", charsLabel: "caracteres", actionsLabel: "Ações", btnConvert: "Converter", btnCopy: "Copiar", btnClear: "Limpar", btnSwap: "Trocar", btnImport: "Importar TXT", btnDownload: "Baixar resultado", examplesLabel: "Testar exemplos", warningNonAsciiHexEncode: "Caracteres não ASCII são marcados como ??. Use Bytes UTF-8 para codificação sem ambiguidade.",
      howEyebrow: "Guia de conversão", howTitle: "Como converter ASCII em Hex", howP1: "Cada caractere ASCII tem valor entre <code>0</code> e <code>127</code>. Converta o decimal para base 16 e complete duas casas. <code>A</code> vale <code>65</code> e vira <code>41</code>.", howP2: "O processo é repetido para cada caractere. <code>Hi</code> vira <code>48 69</code>; sem espaços, os mesmos bytes são <code>4869</code>.", thCharacter: "Caractere", thDecimal: "ASCII decimal", thHex: "Byte Hex", spaceCharacter: "Espaço",
      codeTitle: "ASCII to Hex em JavaScript", codeP1: "Leia com <code>charCodeAt</code>, rejeite valores acima de <code>127</code> e use <code>toString(16)</code> com <code>padStart(2, \"0\")</code>.", pythonTitle: "ASCII to Hex em Python", pythonP1: "<code>ord</code> retorna o valor e <code>format(value, \"02X\")</code> gera um byte Hex de dois dígitos. Valores abaixo de <code>128</code> mantêm ASCII estrito.",
      boundaryTitle: "Hex ASCII e Hex UTF-8", boundaryP1: "ASCII padrão cobre <code>00</code> a <code>7F</code>, um byte por caractere. Como ASCII faz parte de UTF-8, letras inglesas, números e pontuação são iguais nos dois modos.", boundaryP2: "Caracteres acima de <code>U+007F</code> não são ASCII. Em UTF-8, <code>é</code> é <code>C3 A9</code> e <code>你</code> é <code>E4 BD A0</code>. Use UTF-8 para texto multilíngue, símbolos e emoji.", boundaryNoteTitle: "Um caractere ASCII corresponde a um byte Hex de dois dígitos.", boundaryNoteText: "Em UTF-8, um caractere Unicode pode usar de dois a quatro bytes Hex.",
      utf8Title: "Formatos de saída ASCII to Hex", utf8P1: "<code>Hi</code> pode ser <code>48 69</code>, <code>4869</code>, <code>0x48 0x69</code> ou <code>\\x48\\x69</code>; os bytes não mudam.", utf8P2: "Use espaços para inspeção, compacto para protocolos, 0x em código e escapes em strings ou fixtures.",
      relatedEyebrow: "Conversores relacionados", relatedTitle: "Continuar convertendo ASCII e Unicode", relatedText: "Decodifique o resultado, compare binário ou gere escapes Unicode com uma ferramenta específica.", relatedHomeTitle: "Conversor ASCII to Unicode", relatedHomeText: "Decodifique escapes ASCII-safe como Unicode legível.", relatedUnicodeTitle: "Conversor Unicode to ASCII", relatedUnicodeText: "Escape, translitere, substitua ou remova caracteres não ASCII.", relatedReverseTitle: "Conversor Hex to ASCII", relatedReverseText: "Decodifique bytes hexadecimais em texto ASCII ou UTF-8.", relatedBinaryTitle: "Conversor ASCII to Binary", relatedBinaryText: "Converta os mesmos caracteres ASCII em grupos binários de 8 bits."
    },
    fr: {
      topLabel: "HAUT", topAriaLabel: "Retour en haut", skip: "Aller au convertisseur", navHow: "Fonctionnement", navCode: "Code", navBoundary: "ASCII et UTF-8", languageLabel: "Choisir la langue", languageMenuLabel: "Langue", breadcrumbLabel: "Fil d'Ariane", breadcrumbHome: "ASCII to Unicode", breadcrumbCurrent: "Convertisseur ASCII to Hex",
      heroEyebrow: "Convertisseur hexadécimal gratuit dans le navigateur", heroTitle: "Convertisseur ASCII to Hex", heroLede: "Convertissez le texte ASCII en octets hexadécimaux. Utilisez les octets UTF-8 pour les accents, écritures non latines, symboles ou emoji.", proofLabel: "Atouts", proofNoSignup: "Sans inscription", proofFree: "Conversion gratuite en ligne",
      toolKicker: "Outil interactif", toolTitle: "Convertir les caractères ASCII en hexadécimal", statusReady: "Prêt", statusDone: "Converti", statusCopied: "Copié", statusCleared: "Effacé", statusImported: "Importé", statusDownloaded: "Téléchargé", modeAscii: "ASCII standard", modeUtf8: "Octets UTF-8", formatLabel: "Format de sortie", formatSpace: "Séparé par espaces", formatCompact: "Hex compact", formatPrefix: "Préfixe 0x", formatEscape: "Échappement \\x", autoConvert: "Conversion automatique", formatHelp: "Le mode ASCII produit un octet Hex à deux chiffres par caractère et signale les caractères non pris en charge sans deviner l'encodage.",
      inputLabel: "Entrée ASCII", inputPlaceholder: "Hello", inputHelp: "Saisissez du texte ASCII ou utilisez les octets UTF-8 pour le texte multilingue.", outputLabel: "Sortie Hex", outputPlaceholder: "48 65 6C 6C 6F", charsLabel: "caractères", actionsLabel: "Actions", btnConvert: "Convertir", btnCopy: "Copier", btnClear: "Effacer", btnSwap: "Permuter", btnImport: "Importer TXT", btnDownload: "Télécharger", examplesLabel: "Essayer des exemples", warningNonAsciiHexEncode: "Les caractères non ASCII sont marqués ??. Utilisez les octets UTF-8 pour un encodage sans ambiguïté.",
      howEyebrow: "Guide de conversion", howTitle: "Comment convertir ASCII en Hex", howP1: "Chaque caractère ASCII vaut de <code>0</code> à <code>127</code>. Convertissez le décimal en base 16 sur deux chiffres. <code>A</code> vaut <code>65</code> et devient <code>41</code>.", howP2: "Le processus est répété pour chaque caractère. <code>Hi</code> devient <code>48 69</code> ; sans espaces, les mêmes octets s'écrivent <code>4869</code>.", thCharacter: "Caractère", thDecimal: "ASCII décimal", thHex: "Octet Hex", spaceCharacter: "Espace",
      codeTitle: "ASCII to Hex en JavaScript", codeP1: "Lisez avec <code>charCodeAt</code>, refusez les valeurs supérieures à <code>127</code>, puis utilisez <code>toString(16)</code> et <code>padStart(2, \"0\")</code>.", pythonTitle: "ASCII to Hex en Python", pythonP1: "<code>ord</code> renvoie la valeur et <code>format(value, \"02X\")</code> écrit un octet Hex à deux chiffres. Les valeurs sous <code>128</code> garantissent l'ASCII strict.",
      boundaryTitle: "Hex ASCII et Hex UTF-8", boundaryP1: "L'ASCII standard couvre <code>00</code> à <code>7F</code>, soit un octet par caractère. ASCII étant inclus dans UTF-8, lettres anglaises, chiffres et ponctuation sont identiques dans les deux modes.", boundaryP2: "Les caractères au-dessus de <code>U+007F</code> ne sont pas ASCII. En UTF-8, <code>é</code> vaut <code>C3 A9</code> et <code>你</code> vaut <code>E4 BD A0</code>. Utilisez UTF-8 pour le texte multilingue, les symboles et emoji.", boundaryNoteTitle: "Un caractère ASCII correspond à un octet Hex à deux chiffres.", boundaryNoteText: "En UTF-8, un caractère Unicode peut occuper deux à quatre octets Hex.",
      utf8Title: "Formats de sortie ASCII to Hex", utf8P1: "<code>Hi</code> peut s'écrire <code>48 69</code>, <code>4869</code>, <code>0x48 0x69</code> ou <code>\\x48\\x69</code> ; les octets restent identiques.", utf8P2: "Utilisez les espaces pour vérifier, le compact pour les protocoles, 0x dans le code et les échappements dans les chaînes ou fixtures.",
      relatedEyebrow: "Convertisseurs associés", relatedTitle: "Continuer à convertir ASCII et Unicode", relatedText: "Décodez le résultat, comparez le binaire ou créez des échappements Unicode avec un outil dédié.", relatedHomeTitle: "Convertisseur ASCII to Unicode", relatedHomeText: "Décodez les échappements ASCII-safe en Unicode lisible.", relatedUnicodeTitle: "Convertisseur Unicode to ASCII", relatedUnicodeText: "Échappez, translittérez, remplacez ou supprimez les caractères non ASCII.", relatedReverseTitle: "Convertisseur Hex to ASCII", relatedReverseText: "Décodez les octets hexadécimaux en texte ASCII ou UTF-8.", relatedBinaryTitle: "Convertisseur ASCII to Binary", relatedBinaryText: "Convertissez les mêmes caractères ASCII en groupes binaires de 8 bits."
    },
    de: {
      topLabel: "NACH OBEN", topAriaLabel: "Zum Seitenanfang", skip: "Zum Konverter", navHow: "Funktionsweise", navCode: "Code", navBoundary: "ASCII und UTF-8", languageLabel: "Sprache wählen", languageMenuLabel: "Sprache", breadcrumbLabel: "Breadcrumb", breadcrumbHome: "ASCII to Unicode", breadcrumbCurrent: "ASCII to Hex Konverter",
      heroEyebrow: "Kostenloser Hex-Konverter im Browser", heroTitle: "ASCII to Hex Konverter", heroLede: "ASCII-Text in hexadezimale Bytewerte umwandeln. Für Akzente, nicht-lateinische Schriften, Symbole oder Emoji UTF-8-Bytes verwenden.", proofLabel: "Vorteile", proofNoSignup: "Keine Anmeldung", proofFree: "Kostenlos online umwandeln",
      toolKicker: "Interaktives Tool", toolTitle: "ASCII-Zeichen in Hexadezimal umwandeln", statusReady: "Bereit", statusDone: "Umgewandelt", statusCopied: "Kopiert", statusCleared: "Geleert", statusImported: "Importiert", statusDownloaded: "Heruntergeladen", modeAscii: "Standard-ASCII", modeUtf8: "UTF-8-Bytes", formatLabel: "Ausgabeformat", formatSpace: "Mit Leerzeichen", formatCompact: "Kompaktes Hex", formatPrefix: "0x-Präfix", formatEscape: "\\x-Escape", autoConvert: "Automatisch umwandeln", formatHelp: "Der ASCII-Modus gibt pro Zeichen ein zweistelliges Hex-Byte aus und markiert nicht unterstützte Zeichen, ohne die Codierung zu raten.",
      inputLabel: "ASCII-Eingabe", inputPlaceholder: "Hello", inputHelp: "ASCII-Text eingeben oder für mehrsprachigen Text UTF-8-Bytes wählen.", outputLabel: "Hex-Ausgabe", outputPlaceholder: "48 65 6C 6C 6F", charsLabel: "Zeichen", actionsLabel: "Aktionen", btnConvert: "Umwandeln", btnCopy: "Kopieren", btnClear: "Leeren", btnSwap: "Tauschen", btnImport: "TXT importieren", btnDownload: "Ergebnis laden", examplesLabel: "Beispiele", warningNonAsciiHexEncode: "Nicht-ASCII-Zeichen werden als ?? markiert. Für eine eindeutige Codierung UTF-8-Bytes verwenden.",
      howEyebrow: "Konvertierungsleitfaden", howTitle: "ASCII in Hex umwandeln", howP1: "Jedes ASCII-Zeichen hat einen Wert von <code>0</code> bis <code>127</code>. Den Dezimalwert zur Basis 16 umrechnen und zweistellig auffüllen. <code>A</code> ist <code>65</code> und wird zu <code>41</code>.", howP2: "Der Vorgang wird für jedes Zeichen wiederholt. <code>Hi</code> wird zu <code>48 69</code>; kompakt sind dieselben Bytes <code>4869</code>.", thCharacter: "Zeichen", thDecimal: "ASCII dezimal", thHex: "Hex-Byte", spaceCharacter: "Leerzeichen",
      codeTitle: "ASCII to Hex in JavaScript", codeP1: "Mit <code>charCodeAt</code> lesen, Werte über <code>127</code> ablehnen und mit <code>toString(16)</code> sowie <code>padStart(2, \"0\")</code> formatieren.", pythonTitle: "ASCII to Hex in Python", pythonP1: "<code>ord</code> liefert den Wert und <code>format(value, \"02X\")</code> ein zweistelliges Hex-Byte. Werte unter <code>128</code> halten die Ausgabe strikt ASCII.",
      boundaryTitle: "ASCII-Hex und UTF-8-Hex", boundaryP1: "Standard-ASCII umfasst <code>00</code> bis <code>7F</code>, ein Byte pro Zeichen. Da ASCII Teil von UTF-8 ist, sind englische Buchstaben, Ziffern und Satzzeichen in beiden Modi gleich.", boundaryP2: "Zeichen über <code>U+007F</code> sind kein ASCII. In UTF-8 ist <code>é</code> <code>C3 A9</code> und <code>你</code> <code>E4 BD A0</code>. Für mehrsprachigen Text, Symbole und Emoji UTF-8 verwenden.", boundaryNoteTitle: "Ein ASCII-Zeichen entspricht einem zweistelligen Hex-Byte.", boundaryNoteText: "In UTF-8 kann ein Unicode-Zeichen zwei bis vier Hex-Bytes belegen.",
      utf8Title: "ASCII to Hex Ausgabeformate", utf8P1: "<code>Hi</code> kann als <code>48 69</code>, <code>4869</code>, <code>0x48 0x69</code> oder <code>\\x48\\x69</code> geschrieben werden; die Bytes bleiben gleich.", utf8P2: "Leerzeichen zum Prüfen, kompakt für Protokolle, 0x im Code und Escapes in Strings oder Fixtures verwenden.",
      relatedEyebrow: "Verwandte Konverter", relatedTitle: "ASCII und Unicode weiter umwandeln", relatedText: "Das Ergebnis decodieren, Binärwerte vergleichen oder Unicode-Escapes mit einem passenden Tool erzeugen.", relatedHomeTitle: "ASCII to Unicode Konverter", relatedHomeText: "ASCII-sichere Escapes in lesbaren Unicode-Text decodieren.", relatedUnicodeTitle: "Unicode to ASCII Konverter", relatedUnicodeText: "Nicht-ASCII-Zeichen maskieren, transliterieren, ersetzen oder entfernen.", relatedReverseTitle: "Hex to ASCII Konverter", relatedReverseText: "Hexadezimale Bytes in ASCII- oder UTF-8-Text decodieren.", relatedBinaryTitle: "ASCII to Binary Konverter", relatedBinaryText: "Dieselben ASCII-Zeichen in feste 8-Bit-Binärgruppen umwandeln."
    },
    ja: {
      topLabel: "上へ", topAriaLabel: "ページ上部へ戻る", skip: "コンバーターへ移動", navHow: "変換方法", navCode: "コード", navBoundary: "ASCII と UTF-8", languageLabel: "言語を選択", languageMenuLabel: "言語", breadcrumbLabel: "パンくずリスト", breadcrumbHome: "ASCII to Unicode", breadcrumbCurrent: "ASCII to Hex コンバーター",
      heroEyebrow: "ブラウザで使える無料16進変換", heroTitle: "ASCII to Hex コンバーター", heroLede: "ASCII テキストを16進バイト値に変換します。アクセント、非ラテン文字、記号、絵文字には UTF-8 バイトを使用します。", proofLabel: "コンバーターの特徴", proofNoSignup: "登録不要", proofFree: "オンラインで無料",
      toolKicker: "インタラクティブツール", toolTitle: "ASCII 文字を16進数に変換", statusReady: "準備完了", statusDone: "変換済み", statusCopied: "コピー済み", statusCleared: "クリア済み", statusImported: "読み込み済み", statusDownloaded: "ダウンロード済み", modeAscii: "標準 ASCII", modeUtf8: "UTF-8 バイト", formatLabel: "出力形式", formatSpace: "空白区切り", formatCompact: "連続 Hex", formatPrefix: "0x 接頭辞", formatEscape: "\\x エスケープ", autoConvert: "自動変換", formatHelp: "ASCII モードは1文字ごとに2桁の Hex バイトを出力し、未対応文字はエンコードを推測せずに示します。",
      inputLabel: "ASCII 入力", inputPlaceholder: "Hello", inputHelp: "ASCII テキストを入力します。多言語テキストは UTF-8 バイトに切り替えます。", outputLabel: "Hex 出力", outputPlaceholder: "48 65 6C 6C 6F", charsLabel: "文字", actionsLabel: "変換操作", btnConvert: "変換", btnCopy: "コピー", btnClear: "クリア", btnSwap: "入れ替え", btnImport: "TXT を読み込む", btnDownload: "結果をダウンロード", examplesLabel: "例を試す", warningNonAsciiHexEncode: "非 ASCII 文字は ?? で表示します。正確なエンコードには UTF-8 バイトを使います。",
      howEyebrow: "変換ガイド", howTitle: "ASCII を Hex に変換する方法", howP1: "各 ASCII 文字には <code>0</code> から <code>127</code> の値があります。10進値を16進数に変換し2桁に揃えます。<code>A</code> は <code>65</code> なので <code>41</code> です。", howP2: "各文字に同じ処理を行います。<code>Hi</code> は <code>48 69</code>、空白なしなら同じバイトが <code>4869</code> になります。", thCharacter: "文字", thDecimal: "ASCII 10進", thHex: "Hex バイト", spaceCharacter: "空白",
      codeTitle: "JavaScript で ASCII to Hex", codeP1: "<code>charCodeAt</code> で値を読み、<code>127</code> を超える値を拒否し、<code>toString(16)</code> と <code>padStart(2, \"0\")</code> で整形します。", pythonTitle: "Python で ASCII to Hex", pythonP1: "<code>ord</code> で値を得て <code>format(value, \"02X\")</code> で2桁の Hex にします。<code>128</code> 未満を確認すると厳密な ASCII になります。",
      boundaryTitle: "ASCII Hex と UTF-8 Hex", boundaryP1: "標準 ASCII は <code>00</code> から <code>7F</code> で、1文字が1バイトです。ASCII は UTF-8 の一部なので、英字、数字、句読点は両モードで同じです。", boundaryP2: "<code>U+007F</code> より上は ASCII ではありません。UTF-8 では <code>é</code> が <code>C3 A9</code>、<code>你</code> が <code>E4 BD A0</code> です。多言語、記号、絵文字には UTF-8 を使います。", boundaryNoteTitle: "ASCII 1文字は2桁の Hex バイト1つに対応します。", boundaryNoteText: "UTF-8 では Unicode 1文字が2〜4個の Hex バイトになることがあります。",
      utf8Title: "ASCII to Hex の出力形式", utf8P1: "<code>Hi</code> は <code>48 69</code>、<code>4869</code>、<code>0x48 0x69</code>、<code>\\x48\\x69</code> と書けます。バイト値は同じです。", utf8P2: "確認には空白区切り、プロトコルには連続、コードには 0x、文字列や fixture にはエスケープを使います。",
      relatedEyebrow: "関連コンバーター", relatedTitle: "ASCII と Unicode の変換を続ける", relatedText: "結果のデコード、バイナリ比較、Unicode エスケープ生成には専用ツールを使います。", relatedHomeTitle: "ASCII to Unicode コンバーター", relatedHomeText: "ASCII セーフなエスケープを読みやすい Unicode に戻します。", relatedUnicodeTitle: "Unicode to ASCII コンバーター", relatedUnicodeText: "非 ASCII 文字をエスケープ、音写、置換、削除します。", relatedReverseTitle: "Hex to ASCII コンバーター", relatedReverseText: "16進バイトを ASCII または UTF-8 テキストに戻します。", relatedBinaryTitle: "ASCII to Binary コンバーター", relatedBinaryText: "同じ ASCII 文字を固定8ビットのバイナリに変換します。"
    },
    ko: {
      topLabel: "위로", topAriaLabel: "맨 위로", skip: "변환기로 이동", navHow: "변환 방식", navCode: "코드", navBoundary: "ASCII와 UTF-8", languageLabel: "언어 선택", languageMenuLabel: "언어", breadcrumbLabel: "이동 경로", breadcrumbHome: "ASCII to Unicode", breadcrumbCurrent: "ASCII to Hex 변환기",
      heroEyebrow: "브라우저에서 실행되는 무료 16진수 변환기", heroTitle: "ASCII to Hex 변환기", heroLede: "ASCII 텍스트를 16진수 바이트 값으로 변환합니다. 액센트, 비라틴 문자, 기호, 이모지는 UTF-8 바이트를 사용하세요.", proofLabel: "변환기 특징", proofNoSignup: "가입 불필요", proofFree: "무료 온라인 변환",
      toolKicker: "인터랙티브 도구", toolTitle: "ASCII 문자를 16진수로 변환", statusReady: "준비", statusDone: "변환됨", statusCopied: "복사됨", statusCleared: "지워짐", statusImported: "가져옴", statusDownloaded: "다운로드됨", modeAscii: "표준 ASCII", modeUtf8: "UTF-8 바이트", formatLabel: "출력 형식", formatSpace: "공백 구분", formatCompact: "연속 Hex", formatPrefix: "0x 접두사", formatEscape: "\\x 이스케이프", autoConvert: "자동 변환", formatHelp: "ASCII 모드는 문자당 두 자리 Hex 바이트를 출력하고 인코딩을 추측하지 않은 채 지원하지 않는 문자를 표시합니다.",
      inputLabel: "ASCII 입력", inputPlaceholder: "Hello", inputHelp: "ASCII 텍스트를 입력하거나 다국어 텍스트에는 UTF-8 바이트를 선택하세요.", outputLabel: "Hex 출력", outputPlaceholder: "48 65 6C 6C 6F", charsLabel: "문자", actionsLabel: "변환 작업", btnConvert: "변환", btnCopy: "복사", btnClear: "지우기", btnSwap: "바꾸기", btnImport: "TXT 가져오기", btnDownload: "결과 다운로드", examplesLabel: "예시 실행", warningNonAsciiHexEncode: "비 ASCII 문자는 ??로 표시됩니다. 명확한 인코딩에는 UTF-8 바이트를 사용하세요.",
      howEyebrow: "변환 안내", howTitle: "ASCII를 Hex로 변환하는 방법", howP1: "각 ASCII 문자는 <code>0</code>부터 <code>127</code>까지의 값을 가집니다. 10진수를 16진수로 바꾸고 두 자리로 맞춥니다. <code>A</code>는 <code>65</code>이며 <code>41</code>입니다.", howP2: "각 문자에 같은 처리를 합니다. <code>Hi</code>는 <code>48 69</code>, 공백 없이 쓰면 같은 바이트가 <code>4869</code>입니다.", thCharacter: "문자", thDecimal: "ASCII 10진수", thHex: "Hex 바이트", spaceCharacter: "공백",
      codeTitle: "JavaScript에서 ASCII to Hex", codeP1: "<code>charCodeAt</code>로 값을 읽고 <code>127</code>보다 큰 값을 거부한 뒤 <code>toString(16)</code>과 <code>padStart(2, \"0\")</code>로 정리합니다.", pythonTitle: "Python에서 ASCII to Hex", pythonP1: "<code>ord</code>로 값을 얻고 <code>format(value, \"02X\")</code>로 두 자리 Hex를 만듭니다. 모든 값이 <code>128</code> 미만이면 엄격한 ASCII입니다.",
      boundaryTitle: "ASCII Hex와 UTF-8 Hex", boundaryP1: "표준 ASCII는 <code>00</code>부터 <code>7F</code>까지이며 문자 하나가 바이트 하나입니다. ASCII는 UTF-8의 일부이므로 영문, 숫자, 문장 부호는 두 모드에서 같습니다.", boundaryP2: "<code>U+007F</code>보다 큰 문자는 ASCII가 아닙니다. UTF-8에서 <code>é</code>는 <code>C3 A9</code>, <code>你</code>는 <code>E4 BD A0</code>입니다. 다국어, 기호, 이모지에는 UTF-8을 사용하세요.", boundaryNoteTitle: "ASCII 문자 하나는 두 자리 Hex 바이트 하나입니다.", boundaryNoteText: "UTF-8에서는 Unicode 문자 하나가 두 개에서 네 개의 Hex 바이트를 사용할 수 있습니다.",
      utf8Title: "ASCII to Hex 출력 형식", utf8P1: "<code>Hi</code>는 <code>48 69</code>, <code>4869</code>, <code>0x48 0x69</code>, <code>\\x48\\x69</code>로 쓸 수 있으며 바이트 값은 같습니다.", utf8P2: "검사에는 공백, 프로토콜에는 연속, 코드에는 0x, 문자열이나 fixture에는 이스케이프를 사용하세요.",
      relatedEyebrow: "관련 변환기", relatedTitle: "ASCII와 Unicode 변환 계속하기", relatedText: "결과 디코딩, 이진수 비교, Unicode 이스케이프 생성에는 전용 도구를 사용하세요.", relatedHomeTitle: "ASCII to Unicode 변환기", relatedHomeText: "ASCII 안전 이스케이프를 읽기 쉬운 Unicode로 복원합니다.", relatedUnicodeTitle: "Unicode to ASCII 변환기", relatedUnicodeText: "비 ASCII 문자를 이스케이프, 독음 변환, 교체 또는 제거합니다.", relatedReverseTitle: "Hex to ASCII 변환기", relatedReverseText: "16진수 바이트를 ASCII 또는 UTF-8 텍스트로 복원합니다.", relatedBinaryTitle: "ASCII to Binary 변환기", relatedBinaryText: "같은 ASCII 문자를 고정 8비트 2진수 그룹으로 변환합니다."
    }
  };

  config.pages.asciiToHex = page;
  config.meta.asciiToHex = {
    zh: { title: "ASCII to Hex 转换器 - 免费在线工具", description: "在线将 ASCII 文本转换为十六进制字节，支持空格、连续 Hex、0x、\\x 格式及非 ASCII 文本的 UTF-8 模式。" },
    es: { title: "Convertidor ASCII to Hex - Herramienta gratuita", description: "Convierte texto ASCII a bytes hexadecimales con formato espaciado, compacto, 0x o \\x y modo UTF-8 para texto no ASCII." },
    pt: { title: "Conversor ASCII to Hex - Ferramenta gratuita", description: "Converta texto ASCII em bytes hexadecimais nos formatos com espaços, compacto, 0x ou \\x e use UTF-8 para texto não ASCII." },
    fr: { title: "Convertisseur ASCII to Hex - Outil gratuit", description: "Convertissez le texte ASCII en octets hexadécimaux espacés, compacts, préfixés 0x ou échappés \\x, avec un mode UTF-8." },
    de: { title: "ASCII to Hex Konverter - Kostenloses Tool", description: "ASCII-Text in Hex-Bytes umwandeln: mit Leerzeichen, kompakt, 0x oder \\x sowie UTF-8-Modus für Nicht-ASCII-Text." },
    ja: { title: "ASCII to Hex コンバーター - 無料ツール", description: "ASCII テキストを16進バイトへ変換。空白、連続、0x、\\x 形式と非 ASCII テキスト用 UTF-8 モードに対応。" },
    ko: { title: "ASCII to Hex 변환기 - 무료 도구", description: "ASCII 텍스트를 16진수 바이트로 변환하세요. 공백, 연속, 0x, \\x 형식과 비 ASCII용 UTF-8 모드를 지원합니다." }
  };
})();
