(function () {
  "use strict";

  const config = window.asciiUnicodeI18n;
  if (!config) return;

  config.pages.asciiToBinary = {
    zh: {
      topLabel: "顶部", topAriaLabel: "返回顶部", skip: "跳到转换工具", navHow: "转换方法", navCode: "代码", navBoundary: "ASCII 与 UTF-8", languageLabel: "选择语言", languageMenuLabel: "语言", breadcrumbLabel: "面包屑导航", breadcrumbHome: "ASCII to Unicode", breadcrumbCurrent: "ASCII to Binary 转换器",
      heroEyebrow: "免费的浏览器二进制转换工具", heroTitle: "ASCII to Binary 转换器", heroLede: "立即将 ASCII 文本转为固定 8 位二进制组。如果文本包含重音字母、非拉丁文字、符号或 emoji，请使用 UTF-8 字节模式。", proofLabel: "转换器特点", proofNoSignup: "无需注册", proofFree: "在线免费转换",
      toolKicker: "可交互工具", toolTitle: "将 ASCII 字符转换为二进制", statusReady: "就绪", statusDone: "已转换", statusCopied: "已复制", statusCleared: "已清空", statusImported: "已导入", statusDownloaded: "已下载", modeAscii: "ASCII 8 位", modeUtf8: "UTF-8 字节", formatLabel: "输出排列", formatSpace: "空格分隔", formatCompact: "连续输出", formatLines: "每行一字节", autoConvert: "自动转换", formatHelp: "ASCII 模式为每个字符输出一组 8 位二进制，并标记不支持的字符，不会猜测编码。",
      inputLabel: "ASCII 输入", inputPlaceholder: "Hello", inputHelp: "输入 ASCII 文本；多语言文本请切换到 UTF-8 字节。", outputLabel: "二进制输出", outputPlaceholder: "01001000 01100101...", charsLabel: "个字符", actionsLabel: "转换器操作", btnConvert: "转换", btnCopy: "复制", btnClear: "清空", btnSwap: "交换", btnImport: "导入 TXT", btnDownload: "下载结果", examplesLabel: "尝试示例", warningEmpty: "请输入需要转换的文本。", warningNoChange: "没有发现可转换内容。", warningMalformed: "检测到可能不完整的转义序列。", warningNonAscii: "非 ASCII 字符已标记为 ????????。请使用 UTF-8 字节模式无歧义地编码。",
      howEyebrow: "转换指南", howTitle: "如何将 ASCII 转为二进制", howP1: "每个 ASCII 字符都有一个 <code>0</code> 到 <code>127</code> 之间的十进制值。转换时，先查出 ASCII 值，再写成二进制并在左侧补齐到 8 位。大写 <code>A</code> 是十进制 <code>65</code>，所以结果是 <code>01000001</code>。", howP2: "默认工具会对每个字符重复这个过程，包括空格和控制字符。例如 <code>Hi</code> 变为 <code>01001000 01101001</code>。空格分隔的输出最容易看出每组二进制与字符的对应关系。", thCharacter: "字符", thDecimal: "ASCII 十进制", thBinary: "8 位二进制", spaceCharacter: "空格",
      codeTitle: "JavaScript 中的 ASCII to Binary", codeP1: "JavaScript 可用 <code>charCodeAt</code> 读取 ASCII 值，用 <code>toString(2)</code> 转为二进制，再用 <code>padStart(8, \"0\")</code> 补齐为完整字节。对高于 <code>127</code> 的值必须先验证，否则不能称为 ASCII。", pythonTitle: "Python 中的 ASCII to Binary", pythonP1: "Python 的 <code>ord</code> 返回字符数值，<code>format(value, \"08b\")</code> 把它写成 8 位二进制。检查所有值小于 <code>128</code> 可以确保结果严格属于 ASCII。",
      boundaryTitle: "7 位 ASCII 与 8 位二进制", boundaryP1: "标准 ASCII 的最大值是 <code>127</code>，即 <code>1111111</code>，因此只需 7 位。计算机通常以 8 位字节存储数据，所以转换器会在左侧补零。因此 ASCII <code>A</code> 通常显示为 <code>01000001</code>，而不是 <code>1000001</code>。", boundaryP2: "前导零不会改变数值，只是让结果与字节宽度一致，便于分组、传输、比较和还原。", boundaryNoteTitle: "本工具中一个 ASCII 字符对应一组 8 位二进制。", boundaryNoteText: "这条规则只对标准 ASCII 可靠。U+007F 以外的字符需要指定 UTF-8 等编码。",
      utf8Title: "ASCII 二进制与 UTF-8 二进制", utf8P1: "ASCII 是 UTF-8 的子集，因此英文字母、数字、标点和控制字符在两者中都是同一个字节。非 ASCII 字符不同。<code>é</code> 不属于标准 ASCII，它在 UTF-8 中占两个字节：<code>11000011 10101001</code>。", utf8P2: "把 <code>é</code> 写成 <code>11101001</code> 假设了 Latin-1 等单字节编码，并非 ASCII 或 UTF-8。输入含重音字母、中文、日文、emoji 或任何高于 <code>U+007F</code> 的字符时，请使用 UTF-8 字节模式。",
      relatedEyebrow: "相关转换器", relatedTitle: "继续转换 ASCII 和 Unicode", relatedText: "用首页工具解码 Unicode 转义，或将多语言文本编码为 ASCII-safe 表示。", relatedHomeTitle: "ASCII to Unicode 转换器", relatedHomeText: "将 ASCII-safe 转义解码为可读 Unicode 文本。", relatedUnicodeTitle: "Unicode to ASCII 转换器", relatedUnicodeText: "转义、转写、替换或移除非 ASCII 字符。"
    },
    es: {
      topLabel: "ARRIBA", topAriaLabel: "Volver arriba", skip: "Ir al convertidor", navHow: "Cómo funciona", navCode: "Código", navBoundary: "ASCII y UTF-8", languageLabel: "Elegir idioma", languageMenuLabel: "Idioma", breadcrumbLabel: "Ruta de navegación", breadcrumbHome: "ASCII to Unicode", breadcrumbCurrent: "Convertidor ASCII to Binary",
      heroEyebrow: "Convertidor binario gratuito en el navegador", heroTitle: "Convertidor ASCII to Binary", heroLede: "Convierte texto ASCII en grupos binarios fijos de 8 bits. Usa Bytes UTF-8 cuando el texto incluya acentos, escrituras no latinas, símbolos o emoji.", proofLabel: "Ventajas del convertidor", proofNoSignup: "Sin registro", proofFree: "Conversión gratuita en línea",
      toolKicker: "Herramienta interactiva", toolTitle: "Convertir caracteres ASCII a binario", statusReady: "Listo", statusDone: "Convertido", statusCopied: "Copiado", statusCleared: "Borrado", statusImported: "Importado", statusDownloaded: "Descargado", modeAscii: "ASCII de 8 bits", modeUtf8: "Bytes UTF-8", formatLabel: "Disposición de salida", formatSpace: "Separado por espacios", formatCompact: "Compacto", formatLines: "Un byte por línea", autoConvert: "Conversión automática", formatHelp: "El modo ASCII genera un grupo de 8 bits por carácter y marca los no compatibles sin adivinar la codificación.",
      inputLabel: "Entrada ASCII", inputPlaceholder: "Hello", inputHelp: "Introduce texto ASCII o cambia a Bytes UTF-8 para texto multilingüe.", outputLabel: "Salida binaria", outputPlaceholder: "01001000 01100101...", charsLabel: "caracteres", actionsLabel: "Acciones del convertidor", btnConvert: "Convertir", btnCopy: "Copiar", btnClear: "Borrar", btnSwap: "Intercambiar", btnImport: "Importar TXT", btnDownload: "Descargar salida", examplesLabel: "Probar ejemplos", warningEmpty: "Introduce el texto que quieres convertir.", warningNoChange: "No se detectó contenido convertible.", warningMalformed: "Se detectó una secuencia posiblemente incompleta.", warningNonAscii: "Los caracteres no ASCII aparecen como ????????. Usa Bytes UTF-8 para codificarlos sin ambigüedad.",
      howEyebrow: "Guía de conversión", howTitle: "Cómo convertir ASCII a binario", howP1: "Cada carácter ASCII tiene un valor decimal de <code>0</code> a <code>127</code>. Busca ese valor, escríbelo en base 2 y completa ocho dígitos. La <code>A</code> mayúscula vale <code>65</code>, por lo que su forma de 8 bits es <code>01000001</code>.", howP2: "La herramienta repite el proceso para cada carácter, incluidos espacios y controles. <code>Hi</code> se convierte en <code>01001000 01101001</code>. Separar por espacios facilita relacionar cada grupo con su carácter.", thCharacter: "Carácter", thDecimal: "ASCII decimal", thBinary: "Binario de 8 bits", spaceCharacter: "Espacio",
      codeTitle: "ASCII to Binary en JavaScript", codeP1: "JavaScript lee el valor con <code>charCodeAt</code>, lo convierte con <code>toString(2)</code> y usa <code>padStart(8, \"0\")</code> para completar un byte. Valida cualquier valor superior a <code>127</code> antes de llamarlo ASCII.", pythonTitle: "ASCII to Binary en Python", pythonP1: "<code>ord</code> devuelve el valor del carácter y <code>format(value, \"08b\")</code> lo escribe como binario de 8 bits. Comprobar valores inferiores a <code>128</code> mantiene la conversión estrictamente ASCII.",
      boundaryTitle: "ASCII de 7 bits frente a binario de 8 bits", boundaryP1: "ASCII estándar solo necesita siete bits porque su máximo es <code>127</code>, o <code>1111111</code>. Los ordenadores almacenan bytes de 8 bits, por eso se añade un cero inicial. <code>A</code> suele mostrarse como <code>01000001</code> y no <code>1000001</code>.", boundaryP2: "El cero inicial no cambia el valor; crea un resultado de tamaño uniforme para agrupar, transmitir, comparar y recuperar texto.", boundaryNoteTitle: "Aquí un carácter ASCII equivale a un grupo de 8 bits.", boundaryNoteText: "La regla solo es fiable para ASCII estándar. Los caracteres fuera de U+007F necesitan una codificación como UTF-8.",
      utf8Title: "Binario ASCII frente a binario UTF-8", utf8P1: "ASCII es un subconjunto de UTF-8, así que letras inglesas, dígitos y signos usan el mismo byte. <code>é</code> no es ASCII estándar y en UTF-8 usa dos bytes: <code>11000011 10101001</code>.", utf8P2: "Escribir <code>é</code> como <code>11101001</code> supone una codificación de un byte como Latin-1, no ASCII ni UTF-8. Usa Bytes UTF-8 para acentos, chino, japonés, emoji o caracteres mayores que <code>U+007F</code>.", relatedEyebrow: "Convertidores relacionados", relatedTitle: "Seguir convirtiendo ASCII y Unicode", relatedText: "Usa el convertidor principal para escapes Unicode o codifica texto multilingüe en representaciones seguras para ASCII.", relatedHomeTitle: "Convertidor ASCII to Unicode", relatedHomeText: "Decodifica escapes seguros para ASCII en texto Unicode legible.", relatedUnicodeTitle: "Convertidor Unicode to ASCII", relatedUnicodeText: "Escapa, translitera, sustituye o elimina caracteres no ASCII."
    },
    pt: {
      topLabel: "TOPO", topAriaLabel: "Voltar ao topo", skip: "Ir para o conversor", navHow: "Como funciona", navCode: "Código", navBoundary: "ASCII e UTF-8", languageLabel: "Escolher idioma", languageMenuLabel: "Idioma", breadcrumbLabel: "Navegação estrutural", breadcrumbHome: "ASCII to Unicode", breadcrumbCurrent: "Conversor ASCII to Binary",
      heroEyebrow: "Conversor binário gratuito no navegador", heroTitle: "Conversor ASCII to Binary", heroLede: "Converta texto ASCII em grupos binários fixos de 8 bits. Use Bytes UTF-8 quando o texto tiver acentos, escritas não latinas, símbolos ou emoji.", proofLabel: "Destaques do conversor", proofNoSignup: "Sem cadastro", proofFree: "Conversão online gratuita",
      toolKicker: "Ferramenta interativa", toolTitle: "Converter caracteres ASCII em binário", statusReady: "Pronto", statusDone: "Convertido", statusCopied: "Copiado", statusCleared: "Limpo", statusImported: "Importado", statusDownloaded: "Baixado", modeAscii: "ASCII de 8 bits", modeUtf8: "Bytes UTF-8", formatLabel: "Layout da saída", formatSpace: "Separado por espaços", formatCompact: "Compacto", formatLines: "Um byte por linha", autoConvert: "Conversão automática", formatHelp: "O modo ASCII gera um grupo de 8 bits por caractere e marca incompatíveis sem adivinhar a codificação.",
      inputLabel: "Entrada ASCII", inputPlaceholder: "Hello", inputHelp: "Digite texto ASCII ou mude para Bytes UTF-8 para texto multilíngue.", outputLabel: "Saída binária", outputPlaceholder: "01001000 01100101...", charsLabel: "caracteres", actionsLabel: "Ações do conversor", btnConvert: "Converter", btnCopy: "Copiar", btnClear: "Limpar", btnSwap: "Trocar", btnImport: "Importar TXT", btnDownload: "Baixar saída", examplesLabel: "Testar exemplos", warningEmpty: "Digite o texto que deseja converter.", warningNoChange: "Nenhum conteúdo conversível foi detectado.", warningMalformed: "Uma sequência possivelmente incompleta foi detectada.", warningNonAscii: "Caracteres não ASCII aparecem como ????????. Use Bytes UTF-8 para codificá-los sem ambiguidade.",
      howEyebrow: "Guia de conversão", howTitle: "Como converter ASCII em binário", howP1: "Cada caractere ASCII tem um valor decimal de <code>0</code> a <code>127</code>. Consulte o valor, escreva-o na base 2 e complete oito dígitos. A letra <code>A</code> vale <code>65</code>, portanto sua forma de 8 bits é <code>01000001</code>.", howP2: "A ferramenta repete o processo para cada caractere, incluindo espaços e controles. <code>Hi</code> vira <code>01001000 01101001</code>. A separação por espaços facilita associar cada grupo ao caractere.", thCharacter: "Caractere", thDecimal: "ASCII decimal", thBinary: "Binário de 8 bits", spaceCharacter: "Espaço",
      codeTitle: "ASCII to Binary em JavaScript", codeP1: "JavaScript lê o valor com <code>charCodeAt</code>, converte com <code>toString(2)</code> e usa <code>padStart(8, \"0\")</code> para completar o byte. Valide valores acima de <code>127</code> antes de chamá-los ASCII.", pythonTitle: "ASCII to Binary em Python", pythonP1: "<code>ord</code> retorna o valor e <code>format(value, \"08b\")</code> o escreve como binário de 8 bits. Verificar valores abaixo de <code>128</code> mantém a conversão estritamente ASCII.",
      boundaryTitle: "ASCII de 7 bits vs binário de 8 bits", boundaryP1: "ASCII padrão precisa de sete bits porque seu máximo é <code>127</code>, ou <code>1111111</code>. Computadores armazenam bytes de 8 bits, por isso um zero inicial é adicionado. <code>A</code> costuma aparecer como <code>01000001</code>, não <code>1000001</code>.", boundaryP2: "O zero inicial não muda o valor; ele cria um resultado uniforme para agrupar, transmitir, comparar e recuperar texto.", boundaryNoteTitle: "Aqui um caractere ASCII equivale a um grupo de 8 bits.", boundaryNoteText: "A regra só é confiável para ASCII padrão. Caracteres fora de U+007F precisam de uma codificação como UTF-8.",
      utf8Title: "Binário ASCII vs binário UTF-8", utf8P1: "ASCII é subconjunto de UTF-8, então letras inglesas, dígitos e sinais usam o mesmo byte. <code>é</code> não é ASCII padrão e em UTF-8 usa dois bytes: <code>11000011 10101001</code>.", utf8P2: "Escrever <code>é</code> como <code>11101001</code> pressupõe uma codificação de byte único como Latin-1, não ASCII ou UTF-8. Use Bytes UTF-8 para acentos, chinês, japonês, emoji ou caracteres acima de <code>U+007F</code>.", relatedEyebrow: "Conversores relacionados", relatedTitle: "Continuar convertendo ASCII e Unicode", relatedText: "Use o conversor principal para escapes Unicode ou codifique texto multilíngue em representações seguras para ASCII.", relatedHomeTitle: "Conversor ASCII to Unicode", relatedHomeText: "Decodifique escapes seguros para ASCII em texto Unicode legível.", relatedUnicodeTitle: "Conversor Unicode to ASCII", relatedUnicodeText: "Escape, translitere, substitua ou remova caracteres não ASCII."
    },
    fr: {
      topLabel: "HAUT", topAriaLabel: "Retour en haut", skip: "Aller au convertisseur", navHow: "Fonctionnement", navCode: "Code", navBoundary: "ASCII et UTF-8", languageLabel: "Choisir la langue", languageMenuLabel: "Langue", breadcrumbLabel: "Fil d'Ariane", breadcrumbHome: "ASCII to Unicode", breadcrumbCurrent: "Convertisseur ASCII to Binary",
      heroEyebrow: "Convertisseur binaire gratuit dans le navigateur", heroTitle: "Convertisseur ASCII to Binary", heroLede: "Convertissez du texte ASCII en groupes binaires fixes de 8 bits. Utilisez Octets UTF-8 pour les accents, les écritures non latines, les symboles et les emoji.", proofLabel: "Points forts du convertisseur", proofNoSignup: "Sans inscription", proofFree: "Conversion gratuite en ligne",
      toolKicker: "Outil interactif", toolTitle: "Convertir des caractères ASCII en binaire", statusReady: "Prêt", statusDone: "Converti", statusCopied: "Copié", statusCleared: "Effacé", statusImported: "Importé", statusDownloaded: "Téléchargé", modeAscii: "ASCII sur 8 bits", modeUtf8: "Octets UTF-8", formatLabel: "Disposition de sortie", formatSpace: "Séparé par espaces", formatCompact: "Compact", formatLines: "Un octet par ligne", autoConvert: "Conversion automatique", formatHelp: "Le mode ASCII produit un groupe de 8 bits par caractère et signale les caractères incompatibles sans deviner l'encodage.",
      inputLabel: "Entrée ASCII", inputPlaceholder: "Hello", inputHelp: "Saisissez du texte ASCII ou passez aux octets UTF-8 pour du texte multilingue.", outputLabel: "Sortie binaire", outputPlaceholder: "01001000 01100101...", charsLabel: "caractères", actionsLabel: "Actions du convertisseur", btnConvert: "Convertir", btnCopy: "Copier", btnClear: "Effacer", btnSwap: "Permuter", btnImport: "Importer un TXT", btnDownload: "Télécharger la sortie", examplesLabel: "Essayer des exemples", warningEmpty: "Saisissez le texte à convertir.", warningNoChange: "Aucun contenu convertible n'a été détecté.", warningMalformed: "Une séquence peut être incomplète.", warningNonAscii: "Les caractères non ASCII sont indiqués par ????????. Utilisez Octets UTF-8 pour les encoder sans ambiguïté.",
      howEyebrow: "Guide de conversion", howTitle: "Comment convertir ASCII en binaire", howP1: "Chaque caractère ASCII a une valeur décimale de <code>0</code> à <code>127</code>. Cherchez cette valeur, écrivez-la en base 2 et complétez à huit chiffres. La lettre <code>A</code> vaut <code>65</code> et devient <code>01000001</code>.", howP2: "L'outil répète l'opération pour chaque caractère, y compris les espaces et contrôles. <code>Hi</code> devient <code>01001000 01101001</code>. Les espaces rendent la correspondance plus facile à lire.", thCharacter: "Caractère", thDecimal: "ASCII décimal", thBinary: "Binaire sur 8 bits", spaceCharacter: "Espace",
      codeTitle: "ASCII to Binary en JavaScript", codeP1: "JavaScript lit la valeur avec <code>charCodeAt</code>, la convertit avec <code>toString(2)</code> et utilise <code>padStart(8, \"0\")</code> pour former un octet. Validez les valeurs supérieures à <code>127</code> avant de les appeler ASCII.", pythonTitle: "ASCII to Binary en Python", pythonP1: "<code>ord</code> renvoie la valeur du caractère et <code>format(value, \"08b\")</code> l'écrit sur 8 bits. Vérifier que chaque valeur est inférieure à <code>128</code> maintient une conversion ASCII stricte.",
      boundaryTitle: "ASCII 7 bits et binaire 8 bits", boundaryP1: "ASCII standard ne nécessite que sept bits car sa valeur maximale est <code>127</code>, soit <code>1111111</code>. Les ordinateurs stockent des octets de 8 bits, d'où le zéro initial. <code>A</code> est donc affiché comme <code>01000001</code> plutôt que <code>1000001</code>.", boundaryP2: "Le zéro initial ne change pas la valeur ; il crée un résultat de taille uniforme pour grouper, transmettre, comparer et restaurer le texte.", boundaryNoteTitle: "Ici, un caractère ASCII correspond à un groupe de 8 bits.", boundaryNoteText: "Cette règle ne vaut que pour ASCII standard. Au-delà de U+007F, il faut un encodage comme UTF-8.",
      utf8Title: "Binaire ASCII et binaire UTF-8", utf8P1: "ASCII est inclus dans UTF-8 : lettres anglaises, chiffres et ponctuation utilisent le même octet. <code>é</code> n'est pas ASCII standard et utilise deux octets UTF-8 : <code>11000011 10101001</code>.", utf8P2: "Écrire <code>é</code> comme <code>11101001</code> suppose un encodage mono-octet comme Latin-1, et non ASCII ou UTF-8. Utilisez Octets UTF-8 pour les accents, le chinois, le japonais, les emoji et les caractères supérieurs à <code>U+007F</code>.", relatedEyebrow: "Convertisseurs associés", relatedTitle: "Continuer à convertir ASCII et Unicode", relatedText: "Utilisez le convertisseur principal pour les séquences Unicode ou encodez le texte multilingue dans une forme compatible ASCII.", relatedHomeTitle: "Convertisseur ASCII to Unicode", relatedHomeText: "Décodez les séquences compatibles ASCII en texte Unicode lisible.", relatedUnicodeTitle: "Convertisseur Unicode to ASCII", relatedUnicodeText: "Échappez, translittérez, remplacez ou supprimez les caractères non ASCII."
    },
    de: {
      topLabel: "OBEN", topAriaLabel: "Nach oben", skip: "Zum Konverter springen", navHow: "Funktionsweise", navCode: "Code", navBoundary: "ASCII und UTF-8", languageLabel: "Sprache auswählen", languageMenuLabel: "Sprache", breadcrumbLabel: "Brotkrümelnavigation", breadcrumbHome: "ASCII to Unicode", breadcrumbCurrent: "ASCII to Binary Konverter",
      heroEyebrow: "Kostenloser Binärkonverter im Browser", heroTitle: "ASCII to Binary Konverter", heroLede: "ASCII-Text in feste 8-Bit-Binärgruppen umwandeln. Für Akzente, nichtlateinische Schriften, Symbole und Emoji den Modus UTF-8-Bytes verwenden.", proofLabel: "Vorteile des Konverters", proofNoSignup: "Keine Anmeldung", proofFree: "Kostenlose Online-Konvertierung",
      toolKicker: "Interaktives Tool", toolTitle: "ASCII-Zeichen in Binärcode umwandeln", statusReady: "Bereit", statusDone: "Konvertiert", statusCopied: "Kopiert", statusCleared: "Geleert", statusImported: "Importiert", statusDownloaded: "Heruntergeladen", modeAscii: "8-Bit-ASCII", modeUtf8: "UTF-8-Bytes", formatLabel: "Ausgabelayout", formatSpace: "Mit Leerzeichen", formatCompact: "Kompakt", formatLines: "Ein Byte pro Zeile", autoConvert: "Automatisch konvertieren", formatHelp: "Der ASCII-Modus erzeugt eine 8-Bit-Gruppe pro Zeichen und markiert nicht unterstützte Zeichen, ohne eine Codierung zu erraten.",
      inputLabel: "ASCII-Eingabe", inputPlaceholder: "Hello", inputHelp: "ASCII-Text eingeben oder für mehrsprachigen Text zu UTF-8-Bytes wechseln.", outputLabel: "Binärausgabe", outputPlaceholder: "01001000 01100101...", charsLabel: "Zeichen", actionsLabel: "Konverteraktionen", btnConvert: "Konvertieren", btnCopy: "Kopieren", btnClear: "Leeren", btnSwap: "Tauschen", btnImport: "TXT importieren", btnDownload: "Ausgabe herunterladen", examplesLabel: "Beispiele testen", warningEmpty: "Geben Sie den zu konvertierenden Text ein.", warningNoChange: "Kein konvertierbarer Inhalt erkannt.", warningMalformed: "Möglicherweise unvollständige Sequenz erkannt.", warningNonAscii: "Nicht-ASCII-Zeichen werden als ???????? markiert. Verwenden Sie UTF-8-Bytes für eine eindeutige Codierung.",
      howEyebrow: "Konvertierungsleitfaden", howTitle: "ASCII in Binärcode umwandeln", howP1: "Jedes ASCII-Zeichen hat einen Dezimalwert von <code>0</code> bis <code>127</code>. Den Wert nachschlagen, zur Basis 2 schreiben und auf acht Stellen auffüllen. Das große <code>A</code> hat den Wert <code>65</code> und wird zu <code>01000001</code>.", howP2: "Das Tool wiederholt dies für jedes Zeichen, einschließlich Leer- und Steuerzeichen. <code>Hi</code> wird zu <code>01001000 01101001</code>. Leerzeichen zwischen Gruppen machen die Zuordnung leicht erkennbar.", thCharacter: "Zeichen", thDecimal: "ASCII dezimal", thBinary: "8-Bit-Binär", spaceCharacter: "Leerzeichen",
      codeTitle: "ASCII to Binary in JavaScript", codeP1: "JavaScript liest den Wert mit <code>charCodeAt</code>, konvertiert ihn mit <code>toString(2)</code> und füllt mit <code>padStart(8, \"0\")</code> auf ein Byte. Werte über <code>127</code> müssen geprüft werden, bevor sie ASCII genannt werden.", pythonTitle: "ASCII to Binary in Python", pythonP1: "<code>ord</code> liefert den Zeichenwert und <code>format(value, \"08b\")</code> schreibt ihn als 8-Bit-Binärzahl. Werte unter <code>128</code> halten die Konvertierung strikt ASCII.",
      boundaryTitle: "7-Bit-ASCII und 8-Bit-Binär", boundaryP1: "Standard-ASCII braucht nur sieben Bits, weil der Höchstwert <code>127</code> oder <code>1111111</code> ist. Computer speichern 8-Bit-Bytes, daher kommt eine führende Null hinzu. <code>A</code> erscheint als <code>01000001</code> statt <code>1000001</code>.", boundaryP2: "Die führende Null ändert den Wert nicht; sie erzeugt eine einheitliche Bytegröße zum Gruppieren, Übertragen, Vergleichen und Zurückwandeln.", boundaryNoteTitle: "Hier entspricht ein ASCII-Zeichen einer 8-Bit-Gruppe.", boundaryNoteText: "Diese Regel gilt nur für Standard-ASCII. Zeichen außerhalb von U+007F benötigen eine Codierung wie UTF-8.",
      utf8Title: "ASCII-Binär und UTF-8-Binär", utf8P1: "ASCII ist eine Teilmenge von UTF-8; englische Buchstaben, Ziffern und Satzzeichen verwenden dasselbe Byte. <code>é</code> ist kein Standard-ASCII und nutzt in UTF-8 zwei Bytes: <code>11000011 10101001</code>.", utf8P2: "<code>é</code> als <code>11101001</code> setzt eine Einbyte-Codierung wie Latin-1 voraus, nicht ASCII oder UTF-8. Verwenden Sie UTF-8-Bytes für Akzente, Chinesisch, Japanisch, Emoji und Zeichen über <code>U+007F</code>.", relatedEyebrow: "Verwandte Konverter", relatedTitle: "ASCII und Unicode weiter konvertieren", relatedText: "Den Hauptkonverter für Unicode-Escapes verwenden oder mehrsprachigen Text ASCII-sicher darstellen.", relatedHomeTitle: "ASCII to Unicode Konverter", relatedHomeText: "ASCII-sichere Escapes in lesbaren Unicode-Text decodieren.", relatedUnicodeTitle: "Unicode to ASCII Konverter", relatedUnicodeText: "Nicht-ASCII-Zeichen maskieren, transliterieren, ersetzen oder entfernen."
    },
    ja: {
      topLabel: "上へ", topAriaLabel: "ページ上部へ戻る", skip: "コンバーターへ移動", navHow: "変換方法", navCode: "コード", navBoundary: "ASCII と UTF-8", languageLabel: "言語を選択", languageMenuLabel: "言語", breadcrumbLabel: "パンくずリスト", breadcrumbHome: "ASCII to Unicode", breadcrumbCurrent: "ASCII to Binary コンバーター",
      heroEyebrow: "ブラウザで使える無料バイナリ変換", heroTitle: "ASCII to Binary コンバーター", heroLede: "ASCII テキストを固定 8 ビットのバイナリグループに変換します。アクセント、非ラテン文字、記号、絵文字には UTF-8 バイトを使用します。", proofLabel: "コンバーターの特徴", proofNoSignup: "登録不要", proofFree: "オンラインで無料",
      toolKicker: "インタラクティブツール", toolTitle: "ASCII 文字をバイナリに変換", statusReady: "準備完了", statusDone: "変換済み", statusCopied: "コピー済み", statusCleared: "クリア済み", statusImported: "読み込み済み", statusDownloaded: "ダウンロード済み", modeAscii: "ASCII 8 ビット", modeUtf8: "UTF-8 バイト", formatLabel: "出力レイアウト", formatSpace: "空白区切り", formatCompact: "連続", formatLines: "1 行 1 バイト", autoConvert: "自動変換", formatHelp: "ASCII モードは 1 文字ごとに 8 ビットを出力し、未対応文字はエンコードを推測せずに示します。",
      inputLabel: "ASCII 入力", inputPlaceholder: "Hello", inputHelp: "ASCII テキストを入力します。多言語テキストは UTF-8 バイトに切り替えます。", outputLabel: "バイナリ出力", outputPlaceholder: "01001000 01100101...", charsLabel: "文字", actionsLabel: "変換操作", btnConvert: "変換", btnCopy: "コピー", btnClear: "クリア", btnSwap: "入れ替え", btnImport: "TXT を読み込む", btnDownload: "結果をダウンロード", examplesLabel: "例を試す", warningEmpty: "変換するテキストを入力してください。", warningNoChange: "変換できる内容がありません。", warningMalformed: "不完全なシーケンスの可能性があります。", warningNonAscii: "非 ASCII 文字は ???????? で表示されます。正確なエンコードには UTF-8 バイトを使います。",
      howEyebrow: "変換ガイド", howTitle: "ASCII をバイナリに変換する方法", howP1: "ASCII 文字には <code>0</code> から <code>127</code> の 10 進値があります。その値を 2 進数で書き、8 桁にゼロ埋めします。大文字 <code>A</code> は <code>65</code> なので <code>01000001</code> です。", howP2: "ツールは空白や制御文字を含む各文字に同じ処理を行います。<code>Hi</code> は <code>01001000 01101001</code> になります。空白区切りなら文字とグループの対応が明確です。", thCharacter: "文字", thDecimal: "ASCII 10 進数", thBinary: "8 ビットバイナリ", spaceCharacter: "空白",
      codeTitle: "JavaScript で ASCII to Binary", codeP1: "JavaScript は <code>charCodeAt</code> で値を読み、<code>toString(2)</code> で変換し、<code>padStart(8, \"0\")</code> で 1 バイトに揃えます。<code>127</code> を超える値は ASCII と呼ぶ前に検証します。", pythonTitle: "Python で ASCII to Binary", pythonP1: "<code>ord</code> で文字の値を得て、<code>format(value, \"08b\")</code> で 8 ビットにします。すべてが <code>128</code> 未満か確認すると厳密な ASCII 変換になります。",
      boundaryTitle: "7 ビット ASCII と 8 ビットバイナリ", boundaryP1: "標準 ASCII の最大値は <code>127</code>、つまり <code>1111111</code> なので 7 ビットで足ります。コンピューターは 8 ビットバイトで保存するため先頭に 0 を足し、<code>A</code> は <code>01000001</code> と表します。", boundaryP2: "先頭の 0 は値を変えません。グループ化、送信、比較、テキスト復元に適した一定サイズにします。", boundaryNoteTitle: "ここでは 1 ASCII 文字が 1 つの 8 ビットグループです。", boundaryNoteText: "この規則は標準 ASCII のみです。U+007F 以外は UTF-8 などのエンコードが必要です。",
      utf8Title: "ASCII バイナリと UTF-8 バイナリ", utf8P1: "ASCII は UTF-8 の部分集合なので、英字、数字、記号は同じ 1 バイトです。<code>é</code> は標準 ASCII ではなく、UTF-8 では <code>11000011 10101001</code> の 2 バイトです。", utf8P2: "<code>é</code> を <code>11101001</code> とするのは Latin-1 などの 1 バイト符号化を想定しており、ASCII や UTF-8 ではありません。アクセント、中国語、日本語、絵文字には UTF-8 バイトを使います。", relatedEyebrow: "関連コンバーター", relatedTitle: "ASCII と Unicode の変換を続ける", relatedText: "Unicode エスケープはメインツールでデコードし、多言語テキストは ASCII セーフな形式に変換します。", relatedHomeTitle: "ASCII to Unicode コンバーター", relatedHomeText: "ASCII セーフなエスケープを読みやすい Unicode に戻します。", relatedUnicodeTitle: "Unicode to ASCII コンバーター", relatedUnicodeText: "非 ASCII 文字をエスケープ、音写、置換、削除します。"
    },
    ko: {
      topLabel: "위로", topAriaLabel: "맨 위로", skip: "변환기로 이동", navHow: "변환 방식", navCode: "코드", navBoundary: "ASCII와 UTF-8", languageLabel: "언어 선택", languageMenuLabel: "언어", breadcrumbLabel: "이동 경로", breadcrumbHome: "ASCII to Unicode", breadcrumbCurrent: "ASCII to Binary 변환기",
      heroEyebrow: "브라우저에서 실행되는 무료 2진수 변환기", heroTitle: "ASCII to Binary 변환기", heroLede: "ASCII 텍스트를 고정 8비트 2진수 그룹으로 변환합니다. 액센트, 비라틴 문자, 기호, 이모지는 UTF-8 바이트를 사용하세요.", proofLabel: "변환기 특징", proofNoSignup: "가입 불필요", proofFree: "무료 온라인 변환",
      toolKicker: "인터랙티브 도구", toolTitle: "ASCII 문자를 2진수로 변환", statusReady: "준비", statusDone: "변환됨", statusCopied: "복사됨", statusCleared: "지워짐", statusImported: "가져옴", statusDownloaded: "다운로드됨", modeAscii: "ASCII 8비트", modeUtf8: "UTF-8 바이트", formatLabel: "출력 배치", formatSpace: "공백 구분", formatCompact: "연속", formatLines: "한 줄에 1바이트", autoConvert: "자동 변환", formatHelp: "ASCII 모드는 문자당 8비트를 출력하고 인코딩을 추측하지 않은 채 지원하지 않는 문자를 표시합니다.",
      inputLabel: "ASCII 입력", inputPlaceholder: "Hello", inputHelp: "ASCII 텍스트를 입력하거나 다국어 텍스트에는 UTF-8 바이트를 선택하세요.", outputLabel: "2진수 출력", outputPlaceholder: "01001000 01100101...", charsLabel: "문자", actionsLabel: "변환 작업", btnConvert: "변환", btnCopy: "복사", btnClear: "지우기", btnSwap: "바꾸기", btnImport: "TXT 가져오기", btnDownload: "결과 다운로드", examplesLabel: "예시 실행", warningEmpty: "변환할 텍스트를 입력하세요.", warningNoChange: "변환할 내용이 없습니다.", warningMalformed: "불완전한 시퀀스가 감지되었습니다.", warningNonAscii: "비 ASCII 문자는 ????????로 표시됩니다. 명확한 인코딩에는 UTF-8 바이트를 사용하세요.",
      howEyebrow: "변환 안내", howTitle: "ASCII를 2진수로 변환하는 방법", howP1: "각 ASCII 문자에는 <code>0</code>부터 <code>127</code>까지의 10진수 값이 있습니다. 값을 2진수로 쓰고 8자리까지 0을 채웁니다. 대문자 <code>A</code>는 <code>65</code>이며 <code>01000001</code>이 됩니다.", howP2: "도구는 공백과 제어 문자를 포함해 각 문자에 같은 처리를 합니다. <code>Hi</code>는 <code>01001000 01101001</code>로 변합니다. 공백 구분은 각 그룹과 문자의 대응을 쉽게 보여 줍니다.", thCharacter: "문자", thDecimal: "ASCII 10진수", thBinary: "8비트 2진수", spaceCharacter: "공백",
      codeTitle: "JavaScript에서 ASCII to Binary", codeP1: "JavaScript는 <code>charCodeAt</code>로 값을 읽고 <code>toString(2)</code>로 변환한 뒤 <code>padStart(8, \"0\")</code>로 1바이트를 만듭니다. <code>127</code>보다 큰 값은 ASCII라고 부르기 전에 검증합니다.", pythonTitle: "Python에서 ASCII to Binary", pythonP1: "<code>ord</code>로 문자 값을 얻고 <code>format(value, \"08b\")</code>로 8비트 2진수를 만듭니다. 모든 값이 <code>128</code> 미만인지 확인하면 엄격한 ASCII 변환이 됩니다.",
      boundaryTitle: "7비트 ASCII와 8비트 2진수", boundaryP1: "표준 ASCII의 최댓값은 <code>127</code>, 즉 <code>1111111</code>이므로 7비트면 충분합니다. 컴퓨터는 8비트 바이트로 저장하므로 앞에 0을 붙여 <code>A</code>를 <code>01000001</code>로 표시합니다.", boundaryP2: "앞의 0은 값을 바꾸지 않으며, 그룹화, 전송, 비교, 텍스트 복원에 편리한 일정한 바이트 크기를 만듭니다.", boundaryNoteTitle: "여기서 ASCII 문자 하나는 8비트 그룹 하나입니다.", boundaryNoteText: "이 규칙은 표준 ASCII에만 해당합니다. U+007F 밖의 문자는 UTF-8 같은 인코딩이 필요합니다.",
      utf8Title: "ASCII 2진수와 UTF-8 2진수", utf8P1: "ASCII는 UTF-8의 부분 집합이므로 영문, 숫자, 문장 부호는 같은 1바이트를 사용합니다. <code>é</code>는 표준 ASCII가 아니며 UTF-8에서 <code>11000011 10101001</code> 두 바이트를 사용합니다.", utf8P2: "<code>é</code>를 <code>11101001</code>로 쓰는 것은 ASCII나 UTF-8이 아닌 Latin-1 같은 1바이트 인코딩을 가정합니다. 액센트, 중국어, 일본어, 이모지에는 UTF-8 바이트를 사용하세요.", relatedEyebrow: "관련 변환기", relatedTitle: "ASCII와 Unicode 변환 계속하기", relatedText: "Unicode 이스케이프는 메인 변환기로 디코딩하고 다국어 텍스트는 ASCII 안전 형식으로 인코딩하세요.", relatedHomeTitle: "ASCII to Unicode 변환기", relatedHomeText: "ASCII 안전 이스케이프를 읽기 쉬운 Unicode로 복원합니다.", relatedUnicodeTitle: "Unicode to ASCII 변환기", relatedUnicodeText: "비 ASCII 문자를 이스케이프, 독음 변환, 교체 또는 제거합니다."
    }
  };

  const reverseCopy = {
    zh: { relatedReverseTitle: "Binary to ASCII 转换器", relatedReverseText: "将 7 位或 8 位二进制组解码为 ASCII 或 UTF-8 文本。" },
    es: { relatedReverseTitle: "Convertidor Binary to ASCII", relatedReverseText: "Decodifica grupos binarios de 7 u 8 bits como texto ASCII o UTF-8." },
    pt: { relatedReverseTitle: "Conversor Binary to ASCII", relatedReverseText: "Decodifique grupos binários de 7 ou 8 bits como texto ASCII ou UTF-8." },
    fr: { relatedReverseTitle: "Convertisseur Binary to ASCII", relatedReverseText: "Décodez des groupes binaires de 7 ou 8 bits en texte ASCII ou UTF-8." },
    de: { relatedReverseTitle: "Binary to ASCII Konverter", relatedReverseText: "7- oder 8-Bit-Binärgruppen als ASCII- oder UTF-8-Text decodieren." },
    ja: { relatedReverseTitle: "Binary to ASCII コンバーター", relatedReverseText: "7/8 ビットのバイナリグループを ASCII または UTF-8 テキストに戻します。" },
    ko: { relatedReverseTitle: "Binary to ASCII 변환기", relatedReverseText: "7비트 또는 8비트 이진 그룹을 ASCII나 UTF-8 텍스트로 디코딩합니다." }
  };
  Object.entries(reverseCopy).forEach(([lang, values]) => Object.assign(config.pages.asciiToBinary[lang], values));

  config.meta.asciiToBinary = {
    zh: { title: "ASCII to Binary 转换器 - 免费在线工具", description: "在线将 ASCII 文本转为 8 位二进制，支持空格分隔、连续和逐行输出，并为非 ASCII 文本提供 UTF-8 字节模式。" },
    es: { title: "Convertidor ASCII to Binary - Herramienta gratuita", description: "Convierte texto ASCII a binario de 8 bits con salida separada, compacta o por líneas y un modo de bytes UTF-8 para texto no ASCII." },
    pt: { title: "Conversor ASCII to Binary - Ferramenta gratuita", description: "Converta texto ASCII em binário de 8 bits com saída separada, compacta ou por linhas e modo de bytes UTF-8 para texto não ASCII." },
    fr: { title: "Convertisseur ASCII to Binary - Outil gratuit", description: "Convertissez le texte ASCII en binaire sur 8 bits avec sortie espacée, compacte ou par ligne et un mode UTF-8 pour le texte non ASCII." },
    de: { title: "ASCII to Binary Konverter - Kostenloses Tool", description: "ASCII-Text in 8-Bit-Binärcode umwandeln: getrennte, kompakte oder zeilenweise Ausgabe plus UTF-8-Modus für Nicht-ASCII-Text." },
    ja: { title: "ASCII to Binary コンバーター - 無料ツール", description: "ASCII テキストを 8 ビットバイナリに変換。空白区切り、連続、行別出力と非 ASCII 用 UTF-8 モードに対応。" },
    ko: { title: "ASCII to Binary 변환기 - 무료 도구", description: "ASCII 텍스트를 8비트 2진수로 변환하세요. 공백, 연속, 행별 출력과 비 ASCII 텍스트용 UTF-8 모드를 지원합니다." }
  };
})();
